### ISSUE TITLE
Remove "Dry run" from settings

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#1011]
### Description

We discussed that we don't even know what is the meaning of a Dry run that we have in the block settings. It doesn't make sense to do some dry runs for block usage and don't know how to even try it.

If we can't find in the code how is it used or confirm that it is not used let's remove this section:
![Image](https://github.com/user-attachments/assets/09aa0ab1-36c7-416a-8d92-60f971893453)

### Is the issue you are reporting a regression

No

**Comment by HardeepAsrani** [comment]
@girishpanchal30 I saw you had added these options to the block, do you remember what exactly they are there for?

**Comment by HardeepAsrani** [comment]
@girishpanchal30 Ping on this. We closed the issue but I still don't know what it is there for. 😄

**Comment by girishpanchal30** [comment]
@HardeepAsrani For more details here - https://github.com/Codeinwp/feedzy-rss-feeds/issues/709
