### ISSUE TITLE
change shortcode order

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#107]
@contactashish13 we need to add a sorting attribute to the Feedzy shortcode.

1. Add the sorting order in the Feedzy popup in the WordPress editor. 
2. The options will be name_asc, name_desc, date_asc, date_desc. The default will be the current order. 
3. You can check this on how we can achieve this custom order, maybe it helps -> http://simplepie.org/wiki/reference/simplepie/sort_items 
4. Make sure this change will not affect older users, by changing the order of their items.

**Comment by contactashish13** [comment]
@selul by name do you mean title?

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/110

I've called the options title_asc, title_desc, date_asc and date_desc.

**Comment by selul** [comment]
@contactashish13 can we make the php unit tests for this also.

**Comment by contactashish13** [comment]
@selul added test case for title_asc and title_desc. Date sorting (desc) happens by default so I haven't added a test for that.

**Comment by selul** [comment]
@contactashish13 one thing here, it seems the build is failing, also can you solve the conflicts also ?

**Comment by contactashish13** [comment]
@selul have resolved the conflicts and the build is now passing as well. Last time it seemed like a problem with the travis configuration but this time it went well.
