### ISSUE TITLE
Display just the image on feed thumbnails

### ISSUE THREAD

**Issue by rohittm** [Codeinwp/feedzy-rss-feeds#108]
@selul 
According to my conversation here: https://wordpress.org/support/topic/default-image-problem/ I found no way to use the custom image if the feed has a default image. I mean, the feed url is: https://katikitti.com/feed/

When I use thumb="yes" or thumb="auto" in the shortcode,

![screen shot 2018-02-28 at 03 02 56](https://user-images.githubusercontent.com/3204558/36756041-fabbb83e-1c33-11e8-92dc-f80b5145227e.png)

I can see the default images from the feed. 

![screen shot 2018-02-28 at 03 03 21](https://user-images.githubusercontent.com/3204558/36756042-fabcaa00-1c33-11e8-83cc-58cd92b34b1d.png)

But When I use thumb="no". There is no image used. 

![screen shot 2018-02-28 at 03 04 06](https://user-images.githubusercontent.com/3204558/36756081-11260688-1c34-11e8-9e98-d7b2699b3ce9.png)

Is there any way to display the image we want to display, even if the feed has a image?

**Comment by selul** [comment]
@rohittm not really, the default image purpose is to be used when we don't have any image in the feed.
