### ISSUE TITLE
Constant nagging

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/feedzy-rss-feeds#121]
@selul It looks like our customers are a little bit bothered because we are continually asking for a review. I think we should ask only once. Or maybe once at three-six months. 

https://wordpress.org/support/topic/constant-nagging/

**Comment by selul** [comment]
@mileamadalin we're asking just once, maybe he has multiple products from us and get from other too.

**Comment by mileamadalin** [comment]
Thanks! I'll check it.
