### ISSUE TITLE
Add parameters to filter to enable better extensibility

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#129]
ref: https://secure.helpscout.net/conversation/577848228/161185?folderId=1362294

We need to add `$item` to filters so that the SimplePie_Item object can be used

**Comment by selul** [comment]
@contactashish13 i see that there is a conflict, can you please fix it ?

**Comment by contactashish13** [comment]
@selul done

**Comment by rodica-andronache** [comment]
@contactashish13 I tried this with twentysixteen. I add the code you mentioned on HS and this is what I got https://prnt.sc/jk8e4p.
Could you please check?

**Comment by contactashish13** [comment]
@rodica-andronache oops, I guess I need to add `<img src=` to that so that it returns the image element.

**Comment by rodica-andronache** [comment]
@contactashish13 was this fixed? I'm not able to find a PR

**Comment by contactashish13** [comment]
@rodica-andronache this did not need any code fix. Only the filter that was suggested to the client needed to be altered. Maybe @rohittm can use this filter in one of the documents?
