### ISSUE TITLE
Documentation for remove_filter is incorrect

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#133]
ref https://secure.helpscout.net/conversation/591237029/162765

The way to remove the filter is incorrect: https://docs.themeisle.com/article/542-how-to-keep-html-in-feed-items-content

The correct way is this. 

`
add_action( 'init', 'feedzy_summary_input_remove', 99 );
function feedzy_summary_input_remove() {
	remove_filter('feedzy_summary_input', array( Feedzy_Rss_Feeds::instance()->get_admin(), 'feedzy_summary_input_filter' ), 9);
}
`

Documentation all over should be tested for such instances.

cc: @rodica-andronache

**Comment by rohittm** [comment]
@contactashish13 Can you please check it now? https://docs.themeisle.com/article/542-how-to-keep-html-in-feed-items-content

**Comment by contactashish13** [comment]
@rohittm it looks okay but the proof is in the pudding. Can you test using the snippet and if it works you can close this?

**Comment by contactashish13** [comment]
done by AC
