### ISSUE TITLE
Documentation for user defined templates is incorrect

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#135]
It appears the folder should be called "feedzy_templates" and not what https://docs.themeisle.com/article/573-how-to-move-feedzy-templates-to-your-theme says. Need to check and correct.

cc @rodica-andronache

**Comment by rohittm** [comment]
@contactashish13 Can you check it now?

**Comment by contactashish13** [comment]
@rohittm can you confirm you have followed the mechanism you've written down and been able to show a custom template?

**Comment by contactashish13** [comment]
@mileamadalin can this be checked and fixed?

**Comment by mileamadalin** [comment]
Not sure if I understand. He said that was fixed? have you checked and is not working and we have to fix it? Or what exactly to check and fix?

**Comment by contactashish13** [comment]
It would be great to check if that document is okay and fix it if it is not.

**Comment by mileamadalin** [comment]
@contactashish13 yes, checked and worked as expected. However, we'll re-do it a bit to make everything more clear.
