### ISSUE TITLE
Add option to disable featured image from being added to website RSS feed

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#137]
ref: https://secure.helpscout.net/conversation/603211304/163819?folderId=1362294#thread-1679469843

**Comment by contactashish13** [comment]
@rodica-andronache 

PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/138 and https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/108

**Comment by rodica-andronache** [comment]
@contactashish13 can you please help me here? :) I don't understand where this option was added

**Comment by contactashish13** [comment]
@rodica-andronache this was added in the Setting screen under General tab.

![image](https://user-images.githubusercontent.com/12953439/42259863-dea56bfe-7f7f-11e8-9328-b5361d461c50.png)
