### ISSUE TITLE
Warning! Non-numeric value encountered 

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/feedzy-rss-feeds#140]
I am not sure if it is related to our Feedzy plugin only, or other plugins out there have the same problem. I tried to solve this ticket -> https://wordpress.org/support/topic/warning-a-non-numeric-value-encountered-10/#post-10465805 and I encountered the same issue as the client. I started looking into this and I found out that it can be fixed by rolling back the php version (lower than 7.1.16 that I am currently using) or by modifying a php line from SimplePie/Parse/Date.php. 

This second solution it's from here -> https://github.com/simplepie/simplepie/issues/534 and I simply replaced that line(694). After I did that, i tested the feed URL  (http://www.edynburg.msz.gov.pl/rss/edynburgaktualnosci.xml608, http://manchester.msz.gov.pl/rss/manchesteraktualnosci.xml733) from the client's response and it worked.

I also tested a feed (from BBC news, whatever) that it worked before I made the change, and that also worked.

**Comment by contactashish13** [comment]
Unable to reproduce this with the forthcoming release 3.3.2

**Comment by Vishakha-Patel** [comment]
+1 https://secure.helpscout.net/conversation/790658750/182385/

To replicate the issue, I created a feed block with feed URL - https://www.heise.de/rss/heise-atom.xml. It seems to be coming with specific feed URLs only and not all.

**Comment by contactashish13** [comment]
@Vishakha-Patel I cannot reproduce this. Please share the exact steps and also try to reproduce it with and without Gutenberg. Please do this for all future tickets so that the ticket can be handled by the right person (Hardeep for Gutenberg).

**Comment by Vishakha-Patel** [comment]
Hi @contactashish13 

I don't think it is Gutenberg related only. I checked the issue with Elementor - http://prntscr.com/muyng8 And it comes on both Elementor and this visual editor - http://prntscr.com/muynaq.

Maybe, the following points help in replicating: 

- Please use the same Feed URL - https://www.heise.de/rss/heise-atom.xml.  
- My PHP Version 7.2.1
- WordPress version 5.1

The user is still in our conversation. You can also check there to see the issue - https://secure.helpscout.net/conversation/790658750/182385?folderId=948378

**Comment by contactashish13** [comment]
@Vishakha-Patel the customer mentions "If I deactivate elementor the error message is no longer displayed". From your comment, I can't make out if you have tested without Elementor or not. Can you confirm that is the case?

**Comment by Vishakha-Patel** [comment]
Hi @contactashish13,

I have tested with and without Elementor. Some Screenshots:

1. With Elementor: http://prntscr.com/mxqcoh
2. Feedzy Block: 

- Backend: http://prntscr.com/mxqctf
- Frontend: http://prntscr.com/mxqd7a

3. Classic Editor: 

- Backend: http://prntscr.com/mxqdfb, 
- Frontend: http://prntscr.com/mxqdrn

Note: Classic Editor is enabled by using the plugin. 

The warning displays even after I deactivate Elementor.

**Comment by contactashish13** [comment]
Unable to reproduce this on PHP 7.2, Windows, WP 5.1 with Elementor and Feedzy

**Comment by radu-themeisle** [comment]
@contactashish13 I too have stumbled upon this PHP error and I think this time you can also replicate it.
I was testing fetching a YouTube playlist in Feedzy Categories and I got the error:
- YT playlist: thttp://prntscr.com/ocz0sx
- YT channel: http://prntscr.com/ocz1gc

These are the feeds I am using:
https://www.youtube.com/feeds/videos.xml?channel_id=UC6C0TVlx75GPEQc8Kfkh0oQ
https://www.youtube.com/feeds/videos.xml?playlist_id=PLKSjyfkuiavi3FXBJoztHcAUl0Jc8-20F
https://www.youtube.com/feeds/videos.xml?playlist_id=PLmRasCVwuvpSGO9Zf9KR-bopbC75bmz00

I am using WP 5.2.2 with PHP 7.3.7 and only Feedzy Lite and Classic Editor plugins.

**Comment by contactashish13** [comment]
@radu-themeisle can you also post the entire shortcode you tried?

**Comment by radu-themeisle** [comment]
I used the [Feedzy option from the editor](http://prntscr.com/od0qew) so I only pasted the slug, but here's the resulting shortcode anyway: `[feedzy-rss feeds="cwp" feed_title="yes" refresh="12_hours" sort="date_desc" meta="yes" summary="yes" price="yes" columns="1" ]`

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/271

@radu-themeisle can you try this?

**Comment by radu-themeisle** [comment]
@contactashish13 tested and it works
