### ISSUE TITLE
Issue with Feeds with comma in URL

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#141]
Because we separate feeds by comma, some feeds like: http://www.seloger.com/rss,recherche.xml?idtt=2&cp=33700; won't work with Feedzy. Any solution? Can we add some escaping mechanism for comma within feed URLs.

@rodica-andronache

**Comment by contactashish13** [comment]
@HardeepAsrani this seems to be a very specific case. I haven't come across many URLs that have commas but maybe if we add a filter to modify the feed separator, will that not work?

**Comment by contactashish13** [comment]
closing till there are more use cases
