### ISSUE TITLE
Widget: Excluding keywords does not work

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#142]
ref: https://secure.helpscout.net/conversation/618794359/165672

**Comment by ineagu** [comment]
@selul noticed this and I have  a vague impression that we made this pro-only at some point?

**Comment by ineagu** [comment]
I also see it here in plans : https://www.dropbox.com/s/fptfc98bovov6lv/Screenshot%202018-07-25%2010.52.37.png?dl=0, maybe it was an inconsistency

**Comment by selul** [comment]
yes, this is in pro, @contactashish13 it's related to something else?

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/143

**Comment by ineagu** [comment]
ok, I guess we might just have the code in lite for it.

**Comment by contactashish13** [comment]
@selul this issue is from the widget where you can provide include and exclude keywords. Include keywords work but exclude keywords did not because there was no support for it in the code. The user in the referenced ticket is using a pro version.

**Comment by selul** [comment]
i understand, just to confirm, free users won't have this feature?

**Comment by contactashish13** [comment]
yes, only pro users will get the field to provide include and exclude keywords in the widget. The code for this filtering, though, is present in lite.
