### ISSUE TITLE
New Feature: Feed Import > Run Now option

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/feedzy-rss-feeds#144]
When we add a new feed to import it schedules it at around 45 minutes and next run get scheduled accordingly. 

In between, if we want to import the new feeds, there is not a way. 

A "Run Now" option would be helpful in such cases. It also helps in troubleshooting some import related tickets. :) 

@selul

**Comment by HardeepAsrani** [comment]
That would be amazing. :D

**Comment by contactashish13** [comment]
@Vishakha-Patel since this is mostly for troubleshooting, won't using a plugin like WP Crontrol solve be more helpful?

**Comment by Vishakha-Patel** [comment]
+1 https://secure.helpscout.net/conversation/717632432/174446/

**Comment by shiningdreams789** [comment]
I am also facing same problem. If any one have solution "How to change the import run time? I want to extend the time from default time to 14 days.  "
Is that possible now??
kindly suggest any one...
Thanks 😊😊

**Comment by thetall82** [comment]
It is possibile installing an external plugin, like WP Crontrol. Source: https://kb.wprssaggregator.com/article/120-issues-with-cron-jobs

Once installed, go to Tools > Cron events and look for the Feedzy one. Click on edit, under it. Then choose another recurring option from the drop down menu (e.g every week etc.).

If you need to create a non existing recurrency (e.g every 3 hours), first go to Settings > Cron and there create a new cron job on the left. Set an internal name (e.g every_3_hours), a name (e.g Every 3 Hours) and the interval in seconds (e.g 10800, which corresponds to 3 hours).

Hope this helps :-)
Regards
Giorgio
