### ISSUE TITLE
do not ignore items with empty title

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#145]
User isn't able to fetch this feed with Feedzy: http://micro.fncll.org/feed.xml

It works just fine with Gutenberg block, it's able to fetch it, but shortcode part isn't able to render it. Any pointers? @selul @contactashish13

**Comment by contactashish13** [comment]
@HardeepAsrani looks like this is because the feed's items do not contain any title and we ignore the item in case the title is missing.

**Comment by HardeepAsrani** [comment]
@contactashish13 Are we gonna fix it?

**Comment by contactashish13** [comment]
Do you suggest we make the title optional? If so, how would it impact the templates?

**Comment by HardeepAsrani** [comment]
Why would it impact the template? No template is dependent on title, as much as I'm aware of. A condition can be added to stop the tag from appearing. Is there something I'm missing that might impact the templates? @contactashish13

**Comment by contactashish13** [comment]
PR: #185
