### ISSUE TITLE
Possible enhancement made by user

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/feedzy-rss-feeds#15]
User said this: 

"Hi, I use FEEDZY RSS and i really like it. Suggested update for the plug in is to make it available that the main link could be a audio file. i did the following edit: feedzy-rss-feeds/feedzy-rss-feeds-shortcode.php 

`$contentTitle .= '<span class="title"><a href="' . $item->get_permalink() . '" target="' . $target . '">'; $contentTitle .= '<audio controls style=" width:180px"> <source src="' . $item->get_permalink() . '" type="audio/mpeg"> </audio><br>';`

works even better now! - so people can play the podcast right in the sidebar"

**Comment by ineagu** [comment]
@selul we can automatically detect content type if is possible and add required markup .

Not sure how this can work for videos

**Comment by selul** [comment]
Let's tackle this in pro
