### ISSUE TITLE
<br/> display

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/feedzy-rss-feeds#153]
When using the shortcode below, the feed is displaying the `<br/>` rather than creating a new line.
[feedzy-rss feeds=”http://www.apple.com/newsroom/rss-feed.rss” feed_title=”yes” target=”_blank” refresh=”12_hours” title=”50″ meta=”yes” summary=”yes” summarylength=”300″ thumb=”yes” size=”100″]
Screenshot: https://prnt.sc/kjfqdv

CC @rodica-andronache

**Comment by contactashish13** [comment]
@poonam279 the plugin (the SimplePie component, to be precise) sanitizes the extracted content to make it HTML safe thats why `<br>` is converted to '&lt;br/&gt;`. To get around this, you can use the filter `feedzy_summary_output`

```
add_filter( 'feedzy_summary_output', 'feedzy_summary_output', 10, 4 );
function feedzy_summary_output( $contentSummary, $newLink, $feedURL, $item ) {
	return html_entity_decode($contentSummary);
}
```

**Comment by poonam279** [comment]
Thanks @contactashish13 for the code. I've created a doc for this.
