### ISSUE TITLE
Some images do not render if they contain '+' or similar symbols

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#155]
ref: https://secure.helpscout.net/conversation/642973777/167743

**Comment by contactashish13** [comment]
@rodica-andronache PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/156

**Comment by contactashish13** [comment]
shifting the conversation here from https://github.com/Codeinwp/feedzy-rss-feeds/pull/175#issuecomment-449724580.

@mileamadalin please share more details

**Comment by contactashish13** [comment]
@mileamadalin can you please respond to this or close this?

**Comment by mileamadalin** [comment]
Let me know please what details you need. 

A shortcode used by our user: 

`[feedzy-rss feeds=”https://www.bing.com/news/search?q=%22show+jumping%22&FORM=HDRSC6&format=RSS, https://news.google.com/news/rss/search/section/q/%22show%20jumping%22/%22show%20jumping%22?hl=en&gl=US&ned=us, http://www.worldofshowjumping.com/documents.rdf?idz=32&cids=9678, http://www.worldofshowjumping.com/documents.rdf?idz=32&cids=9680, http://www.worldofshowjumping.com/documents.rdf?idz=32&cids=9681, http://www.worldofshowjumping.com/documents.rdf?idz=32&cids=9682” max=”18″ feed_title=”yes” target=”_blank” title=”” meta=”yes” summary=”yes” summarylength=”160″ thumb=”yes” size=”80″ default=”https://www.clean-round.com/wp-content/uploads/tb_FRA_DelaveauPatrice_ORIENT-EXPRESS.png” `

The feed is working but bot displaying the image. 

Here is the ticket link:  https://wordpress.org/support/topic/thumbnails-not-showing-in-rss-feed-google-news/

**Comment by contactashish13** [comment]
@mileamadalin from the point of view of investigation and narrowing it down to a bug, it would be helpful if the above type of shortcodes are tested with individual URLs and then, once it is determined that it is a problem with a specific URL, assigned to me. Is it bing? Is it google news? Is it a combination of both? - a definitive answer would help in resolving such cases faster.

I see that silviu tested for google news in https://wordpress.org/support/topic/thumbnails-not-showing-in-rss-feed-google-news/#post-11326017 but is #155 related to only google or both is not clear and clarity would help a lot.

**Comment by contactashish13** [comment]
closing this as no response
