### ISSUE TITLE
Plugin modifies the website feed

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/feedzy-rss-feeds#160]
@contactashish13 

Ticket: https://secure.helpscout.net/conversation/652872312/168539?folderId=212385

The plugin adds an image in the website's feed. 

In this user's website that shows as an error in W3C validator.

We also saw this in one of the previous tickets.

**Comment by contactashish13** [comment]
@Vishakha-Patel please check https://github.com/Codeinwp/feedzy-rss-feeds/issues/137 and if that resolves this, close the issue.
