### ISSUE TITLE
Handle HTTP images

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/feedzy-rss-feeds#163]
@contactashish13 We have a feedback from a user:

"
I think we had a discussion a few years ago. We talked already about a feature to cache the images from other blogs which FEEDZY show in the list when you used the FEEDZY image option. There are a bunch of problems, because FEEDZY is taking the original Link to the original image.
"
More details here: https://wordpress.org/support/topic/caching-images-fixing-https-warning-gdpr-at-least-skipp-non-https-images/

**Comment by selul** [comment]
seems great.

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/181

the attribute is called `http` and its values can be
- `https` to force HTTPS
- `default` to fallback to default image
- `auto' to do nothing
