### ISSUE TITLE
Some feeds throw an invalid XML error but work on simplepie's demo site

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#166]
ref https://secure.helpscout.net/conversation/691778031/172001/

example: https://www.osha.gov/news/newsreleases.xml

These allegedly invalid feeds are deemed valid by feed validator. It seems that when we use `set_feed_url`, it is very finicky about the feed and cannot bear even an extra newline between elements. But `set_raw_data` seems to be much more resilient. So we can fall back to using `set_raw_data` when `set_feed_url` fails.

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/167

@SilviuDinu you can apply these changes and check if they work for you. Then you can apply it on the customer's site as well at a later time.

**Comment by SilviuDinu** [comment]
@contactashish13 I applied the changes and the feed is working now.

**Comment by contactashish13** [comment]
Some feeds that still do not work but work on http://simplepie.org/demo/ (this is a running list and will keep being updated). **DO NOT CLOSE THIS ISSUE**

- http://betakit.com/feed/ (feed validator considers this invalid)
