### ISSUE TITLE
Google News images not working

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#174]
Somehow Google News feeds don't let us fetch the images, as reported in this thread: https://wordpress.org/support/topic/thumbnails-not-showing-sometimes/#post-10839687

**Comment by HardeepAsrani** [comment]
@contactashish13 Can you take a look here soon, if possible? **The nation wants to know** the answer. 😛 

![Arnab](https://feminisminindia.com/wp-content/uploads/2017/06/The-nation-wants-to-know.jpg)

**Comment by contactashish13** [comment]
That scared me so sh*tless that I had to fix it! 

#175 should resolve this.
