### ISSUE TITLE
Feedzy RSS icon opens up dashboard screen

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/feedzy-rss-feeds#188]
Add classic editor block to the page. Then click on Feedzy RSS Icon - 
![image](https://user-images.githubusercontent.com/29881234/50222319-ec51d900-03bd-11e9-80ad-3d02c0e0c448.png)

It shows dashboard there instead of plugin option - 
![image](https://user-images.githubusercontent.com/29881234/50222336-fa9ff500-03bd-11e9-8c02-05ea87f573e6.png)
cc: @contactashish13 

Ticket: https://wordpress.org/support/topic/how-to-install-rss-new-feed-on-blog/#post-11007440

**Comment by contactashish13** [comment]
@Vishakha-Patel If you have the classic editor plugin installed I'm not sure you can access the gutenberg editor to add a classic block. Can you mention how you are adding the classic editor block?

**Comment by Vishakha-Patel** [comment]
Hey @contactashish13 ,

It is there in my installation by default. I checked in two locals and both have classic block. I have updated my WordPress from 4.9.8. So it might have been showing in that case if one does upgrade and do not install a fresh WP.

Deactivated all the plugins and still if I search classic, I see the block:

![image](https://user-images.githubusercontent.com/29881234/50329255-61d3bb80-051c-11e9-9ba2-f35513d7dcf2.png)

Anyways, I understand that classic editor might not be a part in future. So you can just remove the code to display that icon in the editor toolbar too. :D Whatever you think is correct.

**Comment by contactashish13** [comment]
@HardeepAsrani can you help here? We either need to fix the feedzy button so that it works correctly or remove it (sounds easier). But only when the classic editor is being called as a gutenberg block.

**Comment by HardeepAsrani** [comment]
Gutenberg doesn't have any way to check if the Gutenberg editor is opened, there is `$current_screen->is_block_editor()` but I can't get it to work, can you try to see if that works for you or am I using it wrong? 

```
function is_block_editor() {
		require_once(ABSPATH . 'wp-admin/includes/screen.php');
		$current_screen = get_current_screen();
		$is_block_editor =
			method_exists( $current_screen, 'is_block_editor' )
			&& $current_screen->is_block_editor();
		return $is_block_editor;
	}
```

@contactashish13

**Comment by contactashish13** [comment]
@HardeepAsrani you were on the right track and it was not working because the class was being loaded on `init`. When I changed it to `admin_enqueue_scripts` it worked.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/192
