### ISSUE TITLE
Feedzy gutenberg block doesn't work

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/feedzy-rss-feeds#194]
@contactashish13 we have an issue with the latest version of the plugin and WP 5.0.2

When you want to insert the feed directly from the post using the icon of Feedzy and not the shortcode, not happen. 

Here is a video from @dascalescuro https://www.useloom.com/share/3413a6e6e2a44cf7a4e77f459810a26a 

Poonam tested as well and had the same issue. And here is my video with the same issue: https://drive.google.com/file/d/1s_h3zYZhZz4I0P7RR9zvOKiCAL6arYJs/view

**Comment by contactashish13** [comment]
@HardeepAsrani adding feedzy as a gutenberg block doesnt seem to work. can you take a look?

**Comment by HardeepAsrani** [comment]
@contactashish13 Can you try to reproduce? I tried and it works just fine for me. Is the user using Gutenberg plugin, or any other plugin installed? is REST API disabled on his site? Is his site running on http/https? Or any relevant info that I could use to reproduce? @mileamadalin

**Comment by HardeepAsrani** [comment]
Or access to an env where this is happening would love be helpful.

**Comment by SilviuDinu** [comment]
I encountered the same issue while trying to replicate this ticket's issue -> https://wordpress.org/support/topic/feedzy-gutenberg-block/#post-11101109

Video of the issue + testing -> https://share.vidyard.com/watch/Aehgc8J7zS5YxrHAW3K2oC

A workaround for this would be to install the classic editor plugin and use it the old-fashioned way.

**Comment by mileamadalin** [comment]
@HardeepAsrani I have tested on my local machine, several times in safari and chrome with the same results as Poonam and Silviu reported. If you want, I can give you access to my laptop with TeamViewer so you can make the tests.  

Here is a test with a basic theme a clean install: https://drive.google.com/file/d/1EsJ6y5ERY9gAsHVtuDCja4QrWT9silP0/view 

It works if we add it with shortcode.

**Comment by purplecodes** [comment]
Tested this on poopy.life and I cannot replicate the issue.
Tested it on my own site and still cannot replicate it.

**Comment by contactashish13** [comment]
@purplecodes @SilviuDinu @HardeepAsrani might be best if you could all screen share as only one out of the 3 of you is able to reproduce this issue.

**Comment by contactashish13** [comment]
@HardeepAsrani @purplecodes can we close this? CC @mileamadalin

**Comment by mileamadalin** [comment]
@contactashish13 @HardeepAsrani I cannot replicate it anymore. We can close it from my point of view.

**Comment by contactashish13** [comment]
closing as per https://github.com/Codeinwp/feedzy-rss-feeds/issues/194#issuecomment-474730999
