### ISSUE TITLE
Create PRO repo and discuss/add issues for pro

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/feedzy-rss-feeds#2]
- add an editable template
- Download images
- Add tabs if multiple feeds are added
- Paramètre REL
- Type de contenu dédié
- Custom CSS
- Numérotation (list OL)
- WooComerce (product price)

**Comment by rodica-andronache** [comment]
done https://github.com/Codeinwp/feedzy-rss-feeds-pro
