### ISSUE TITLE
wp 4.7 

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#20]
@preda-bogdan using the wordpress 4.7 i get this error. Can you please check: 

http://prntscr.com/djem5l 

I saw that they recommend to use https://codex.wordpress.org/Function_Reference/fetch_feed

**Comment by preda-bogdan** [comment]
I'll solve it first thing in the morning.

**Comment by preda-bogdan** [comment]
Hey, @selul i've pushed a fix, please check and close this issue if it's ok.

**Comment by selul** [comment]
@preda-bogdan yes, now is ok. thanks
