### ISSUE TITLE
Audio part

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/feedzy-rss-feeds#204]
Encountered a few situations where the feature of importing audio from feeds was the compelling argument for using Feedzy or even upgrade to Feedzy PRO.

I'm not sure how realistic this is, but I thought we should acknowledge this feature request.

One ticket link: https://secure.helpscout.net/conversation/760814666/178529/

**Comment by contactashish13** [comment]
this is a pro feature. closed in preference to https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/166
