### ISSUE TITLE
Missing translation of "Feed has no items"

### ISSUE THREAD

**Issue by diesocke** [Codeinwp/feedzy-rss-feeds#216]
Problem: On https://www.altenheim-wahlscheid.de/karriere/ Feedzy RSS is used to display job offers. The feed is empty, when no posting is published. Because my superiors ask me to remove the posting when the job is taken, I repeatedly have an empty feed. The resulting message is posted in English: "Feed has no items." I can't find a corresponding string in feedzy-rss-feeds-de_DE.po.

Solution: Include the relevant string for translation in the language files.

**Comment by contactashish13** [comment]
@diesocke this is part of the configuration window that pops up in the editor. You can add any text to the field `Message to show when feed is empty` which, if left empty, reads "Feed has no items"

**Comment by diesocke** [comment]
Is it included in a block added in the Gutenberg editor? I use the shortcode.

I did some research and found out that I can use error_empty="$STRING" in the shortcode to display that text when the feed is empty.
