### ISSUE TITLE
Display Feedzy element only when feed contains postings

### ISSUE THREAD

**Issue by diesocke** [Codeinwp/feedzy-rss-feeds#217]
Is it possible to offer a parameter to turn of display of the feed elements when the feed is empty?

**Comment by contactashish13** [comment]
@diesocke is this related to https://github.com/Codeinwp/feedzy-rss-feeds/issues/216? If not, can you please mention a use case for this?

**Comment by diesocke** [comment]
A use case would be to publish recent job offers on a site. Jobs would be posted with a certain category. Feedzy would show the feed of that category. However, if the job is taken the posting gets depublished, so the feed eventually gets empty.

In this case it would help, if the feed was not mentioned anymore. It should reappear  when there is a new job offer.

**Comment by contactashish13** [comment]
@diesocke you can use a message to show that the feed is now empty as per #216
