### ISSUE TITLE
Autodelete posts after a cetain time period

### ISSUE THREAD

**Issue by FitzChris** [Codeinwp/feedzy-rss-feeds#229]
I had a user who made a news aggregator site and the site has blown out to 2GB. I don't think there is an easy way, if any, to remove the old posts. Could we add something that would allow users to choose between 1 day, 7 days, 15 days, 30 days? 

WP RSS Aggregator allows users to set length of storage and deletes anything outside the window.

**Comment by contactashish13** [comment]
closing this and moving to the pro repo: https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/192
