### ISSUE TITLE
Compare with WP RSS Aggregator

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#238]
reference https://secure.helpscout.net/conversation/832586352/186841

Can we see if there are somethings that plugin does better than us?

**Comment by radu-themeisle** [comment]
I'll look into it but I suggest we also involve someone with more experience regarding Feedzy, mine is pretty limited.

**Comment by DanyCaissy** [comment]
The comparison was done here: by Duong https://docs.google.com/presentation/d/1hZx3iM9nuTV1vgWhsyjmFFjJIVCRASqr5Ol8sgyXqoc/edit

I'll close this issue.
