### ISSUE TITLE
Feeds no longer display the description when using the Gutenberg block

### ISSUE THREAD

**Issue by SilviuDinu** [Codeinwp/feedzy-rss-feeds#241]
A couple of users reported that their feed URL has a description in their structure but Feedzy fails to display that description on the page. 

The description is being displayed when loading the feed in the block but it's not being displayed when Previewing the page.

I have tested using the shortocde method and the Classic editor and it works.

Tickets:
- https://secure.helpscout.net/conversation/854615882/188848/

- https://secure.helpscout.net/conversation/854268872/188804/

Video where the issue and the tests can be seen -> https://embed.vidyard.com/share/1j4bAC9Gy1S2yJffJ1Y4Xg?

**Comment by stefan-cotitosu** [comment]
@contactashish13 Can you please check this?

More users are reporting this issue, two of them last week and one this week. This is only on HelpScout.

Thanks.

**Comment by contactashish13** [comment]
@stefan-cotitosu @HardeepAsrani is the go-to person for gutenberg related stuff.

**Comment by HardeepAsrani** [comment]
@contactashish13 It was fixed in https://github.com/Codeinwp/feedzy-rss-feeds/pull/239

**Comment by stefan-cotitosu** [comment]
@HardeepAsrani @contactashish13 

Thanks, I didn't know that I should ping Hardeep for everything related to Gutenberg. Will do from now on.

So it should work properly on the next release of the plugin, great! 👍
