### ISSUE TITLE
Limit image size on mobile.

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/feedzy-rss-feeds#244]
If we add thumbnail size in block settings around 400, it is cropped on mobile - https://nimb.ws/3zYkn2.

https://secure.helpscout.net/conversation/838233362/187364/

@contactashish13

**Comment by contactashish13** [comment]
@Vishakha-Patel I don't understand what you mean by `in block settings`. Can you provide the short code that you use or a test site where I can see this happening?

**Comment by Vishakha-Patel** [comment]
@contactashish13 

In the Feedzy block settings, image size is set to 400: https://nimb.ws/1NAmue
Without image: https://comfortable-musk.jurassic.ninja/feedzy-image-test/
With image: https://comfortable-musk.jurassic.ninja/feedzy-image-test-2/

Both cases, the image div is going out of the window on mobile - https://www.dropbox.com/s/n22hllwd9ohk5d9/Screenshot%202019-06-03%2018.43.26.png?dl=0.

When the user specifies a big image size, this issue happens.

Website details:
`https://comfortable-musk.jurassic.ninja/wp-admin/index.php
WP user: demo WP/SSH password: T5aZwSy9lqWA

SFTP:sftp://user2fb15daa:T5aZwSy9lqWA@comfortable-musk.jurassic.ninja:22//srv/users/user2fb15daa/apps/user2fb15daa/public/

SSH: ssh user2fb15daa@comfortable-musk.jurassic.ninja

Server path: /srv/users/user2fb15daa/apps/user2fb15daa/public/

`

**Comment by contactashish13** [comment]
@Vishakha-Patel in https://www.dropbox.com/s/n22hllwd9ohk5d9/Screenshot%202019-06-03%2018.43.26.png?dl=0 I don't see the issue. There is no horizontal scroll and thus the div does not go out of the window. I don't see the issue when I load those pages on a mobile UI either. 

I do not understand the issue. It would be best if you can write down the exact steps to reproduce this.

**Comment by Vishakha-Patel** [comment]
Hi @contactashish13 ,

The scrollbar is not coming. However, the image is going outside.

I have tried to recreate and explain in this video - https://nimb.ws/juAfPk.

The image should be responsive. If I change the size to 600, it should not load 600 size image for smaller devices.

**Comment by Vishakha-Patel** [comment]
Hi @contactashish13,

Yes, the scrollbar is not there; however, the image is going outside the window. I have created a video here - https://nimb.ws/juAfPk.

If we change the size there as per video to 600 then it looks like this - https://www.dropbox.com/s/dcuh822yq7t7lo9/Screenshot%202019-06-04%2018.36.21.png?dl=0. 

Ideally, the image should be responsive there.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/246

@Vishakha-Patel can you please test this with different image sizes, different devices and all 3 templates (default, style1 and style2) and let me know if you find unexpected behavior?
