### ISSUE TITLE
feedzy shortcode builder icon is not available in classic editor

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/feedzy-rss-feeds#245]
@contactashish13 Feedzy RSS icon that appears in the toolbar of classic editor is not available in version 3.3.6
![Screenshot 2019-05-31 at 10 51 11 PM](https://user-images.githubusercontent.com/27731529/58723221-2b696900-83f7-11e9-90cf-e2018a45f619.png)
Test website where you can see the issue: https://functional-fiordland.jurassic.ninja 
WP user: demo 
password: hpvhEHT3geao

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/249
