### ISSUE TITLE
Add option to remove title entirely

### ISSUE THREAD

**Issue by svoeth** [Codeinwp/feedzy-rss-feeds#258]
Feature request:

It would be nice to be able to remove the title entirely instead of getting three dots.

For example by setting title="0" and replacing lines 841 to 845 in /includes/abstract/feedzy-rss-feeds-admin-abstract.php by

```
if ( is_numeric( $sc['title'] ) && strlen( $item->get_title() ) > $sc['title'] && ( $sc['title'] !== '0' ) ) {
    $content_title .= preg_replace( '/\s+?(\S+)?$/', '', substr( $item->get_title(), 0, $sc['title'] ) ) . '...';
} elseif  ( $sc['title'] !== '0' ) {
    $content_title .= $item->get_title();
}
```

**Comment by contactashish13** [comment]
@svoeth thank you for your suggestion. We will definitely try to incorporate this in a future release

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/266
