### ISSUE TITLE
test new version

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#26]
@contactashish13 i would like your help in testing this new version using the next scenarios: 

## Use Case 1 

- Download the latest production version from here: https://wordpress.org/plugins/feedzy-rss-feeds/  
- Add a some feedzy widgets using different values for the fields 
- Add some shortcodes using different attribute values   
- Update the code to the new version from git https://github.com/Codeinwp/feedzy-rss-feeds/ the development branch 
- Make sure the previously added widgets and shortcodes are working ok

## Use case 2 
 
 - Download the development version from here https://github.com/Codeinwp/feedzy-rss-feeds-pro ( is the pro addon )  and use it with the development version from git of the lite one. 
- make sure all the widgets/shortcodes are working ok. 

## Use case 3

- Make some widgets/shortcodes using both development versions of free and pro installed and make sure they are rendering properly 

Please report any problem you find using enough details for us to replicate it

**Comment by contactashish13** [comment]
@selul these are the bugs for use case 0: bugs in the production code

- single quotes are shown encoded i.e. Don&#039;t need a title...
- documentation of the attributes to be used in the short code is lacking. had to dig in the code e.g. what does meta do? and whether the booleans are yes/no or true/false or 1/0?

**Comment by contactashish13** [comment]
use case 1

- problem with shortcode not display images
[feedzy-rss feeds="http://9gag-rss.com/api/rss/get?code=9GAG&format=1" max="1" meta="yes" summary="yes" summarylength="20" thumb="yes" size="20"]

in prod version:
![image](https://cloud.githubusercontent.com/assets/12953439/21541711/9fa5c0ba-cdde-11e6-920a-4f1ed4d610c0.png)
the code is
<li style="padding: 2px 0 3px" class="rss_item"><div class="rss_image" style="width:20px; height:20px;"><a href="http://9gag.com/gag/ajqGEVx" target="_blank" title="What kind of inception is this?"><span class="default" style="width:20px; height:20px; background-image:  url(http://localhost:81/wp-content/plugins/feedzy-rss-feeds/img/feedzy-default.jpg);" alt="What kind of inception is this?"></span><span class="fetched" style="width:20px; height:20px; background-image:  url(http://img-9gag-fun.9cache.com/photo/ajqGEVx_460sa.gif);" alt="What kind of inception is this?"></span></a></div><span class="title"><a href="http://9gag.com/gag/ajqGEVx" target="_blank">What kind of inception is this?</a></span><div class="rss_content"><small>Posted by <a href="http://9gag.com" target="_blank" title="9gag.com">9gag-rss.com</a> on December 29, 2016 at 9:42 am</small><p> […]</p></div></li>

in dev:
![image](https://cloud.githubusercontent.com/assets/12953439/21541746/e695e2a2-cdde-11e6-9840-cdd2b63ea97b.png)
the code is
<li style="padding: 2px 0 3px" class="rss_item">
                
                <div class="rss_image" style="width:20px; height:20px;">
					<a href="http://9gag.com/gag/ajqGEVx" target="_blank" title="What kind of inception is this?" style="width:20px; height:20px;">
						<span class="fetched" style="background-image:  url(http://img-9gag-fun.9cache.com/photo/ajqGEVx_460sa.gif);" alt="What kind of inception is this?"></span>
					</a>
				</div>
				<span class="title">
					<a href="http://9gag.com/gag/ajqGEVx" target="_blank">
						What kind of inception is this?
					</a>
				</span>
				<div class="rss_content" style="">
					<small>
						by <a href="http://9gag.com" target="_blank" title="9gag.com">9gag-rss.com</a> on December 29, 2016 at 9:42 am
					</small>
					<p> […]</p>
				</div>
			</li>

seems to be ignoring the size parameter in the span

**Comment by contactashish13** [comment]
use case 2

- activate the pro plugin
- without making any changes to the existing widget, refresh the front end that shows the widgets
- get the attached error

![image](https://cloud.githubusercontent.com/assets/12953439/21545312/ba75c336-cdfc-11e6-877e-56e9604ea29b.png)

- field "Template to use when displaying the feed" in widget config - changes to this field do not get saved when editing the widget

**Comment by selul** [comment]
@contactashish13 thanks we should be good to go now
