### ISSUE TITLE
Add option to use default sorting when generating the shortcode

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/feedzy-rss-feeds#261]
@contactashish13 if I want to display feeds directly from the URL, right now I have to sort them either by the date or alphabetically.

Can we add another sorting option called `default` which will display the feeds directly as they are in the feed URL? So no sorting at all.

What do you think?

**Comment by contactashish13** [comment]
@stefan-cotitosu I guess you are referring to the feedzy shortcode creator popup? According to the code, if the `sort` parameter does not exist in the shortcode the feed URL is used directly. I believe an option needs to be added to the popup in this case. Can you please confirm the behavior as well?

**Comment by contactashish13** [comment]
@stefan-cotitosu let me know if this is still an issue or we can close it.

**Comment by stefan-cotitosu** [comment]
@contactashish13 Yes, an option should be added to the pop-up.

Since I am using Gutenberg editor, I can't see the shortcode and its parameters.
I understand your point, and it would be easy to remove the parameter from the shortcode, it's just that you need [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/) in order to see it.

With Gutenberg you can only used the same options as with the old shortcode creator popup but without being able to see the shortcode.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/273

@HardeepAsrani can you also add an option for this? Basically add `sort=''` or do not add the `sort` parameter.

**Comment by HardeepAsrani** [comment]
@contactashish13 I'm confused. What exactly did we change here?

**Comment by contactashish13** [comment]
@HardeepAsrani we added a default option that was missing to support `sort=""` (absence of the `sort` parameter)
