### ISSUE TITLE
change feedzy icon

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/feedzy-rss-feeds#262]
@contactashish13 here is what one user said as uninstall reason: https://i.imgur.com/OOia3QN.png, that feedzy image is slowing down his site, we can compress that image and then test again.

is impressive how people care a lot about very small things :))

**Comment by contactashish13** [comment]
@ineagu One site gave me a 0% reduction and another only a 7.1% reduction in size. I'm not sure how to achieve the 26% shown in the screenshot. Can we use optimole @selul? I've attached the image.
![feedzy-default](https://user-images.githubusercontent.com/12953439/60485590-1e23f080-9cbb-11e9-8d70-151d235558b0.jpg)

Also @ineagu can I get access to these uninstall reasons? Looks like we can learn a lot from them as well.

**Comment by ineagu** [comment]
oki, just try to put in on a site and run pagespeed insights and make sure they are ok with it :) 

@selul can help with uninstall reasons

**Comment by contactashish13** [comment]
@selul 

![image](https://user-images.githubusercontent.com/12953439/60909067-f2949d80-a29a-11e9-96cf-7c9f5394ce4d.png)

We are back to my original question. 

> One site gave me a 0% reduction and another only a 7.1% reduction in size. I'm not sure how to achieve the 26% shown in the screenshot. 

Do you have any suggestions which site I can use to achieve this reduction?

**Comment by selul** [comment]
@contactashish13 can you share with me the URL which you tested this on?

**Comment by contactashish13** [comment]
@selul https://solid-minnow.jurassic.ninja/2019/07/04/hello-world/

**Comment by selul** [comment]
@contactashish13 i'm not able to see the feedzy logo?

**Comment by contactashish13** [comment]
@selul it is loaded in the background of the image from the feed so that if the feed image is not there, the default image shows. You can see in page speed it shows all 3 images

**Comment by selul** [comment]
not sure if this is happening, on the report I'm not able to see any reference to the logo
https://developers.google.com/speed/pagespeed/insights/?url=https%3A%2F%2Fsolid-minnow.jurassic.ninja%2F2019%2F07%2F04%2Fhello-world%2F

**Comment by contactashish13** [comment]
@selul it was happening last night when I left a comment. I don't know why its not happening now.

**Comment by selul** [comment]
ok, let me know when you have a URL.

**Comment by contactashish13** [comment]
@selul can you tell me the intent of the exercise and what we want to accomplish?

**Comment by selul** [comment]
There is no exercise, I'm trying to help you by checking the issue reported and see what could have been wrong with your approach on fixing the issue.

**Comment by contactashish13** [comment]
![image](https://user-images.githubusercontent.com/12953439/60947895-56f14480-a30f-11e9-9924-74ee723f8118.png)

The feedzy image is there in the source.  I don't know why page speed does not show. It showed yesterday as I've shown the screenshot. It showed that the image could be compressed. So I'm confused about what wrong approach could be.

**Comment by selul** [comment]
Ok, so I was able to find this on the desktop tab
http://snpy.in/iA8Mb2

it seems that the report is not tied to the image compression, more related to the fact that you serve an image that is bigger than the container of that image. 

In this case, the container is 150x150 and the image is 250x250. 

One thing that we could do is to replace that using an SVG. I think we can use the SVG icon from the plugin https://ps.w.org/feedzy-rss-feeds/assets/icon.svg?rev=2089818 and replace the outdated logo from this default one too. 

I hope this helps.

**Comment by ineagu** [comment]
@contactashish13 sorry if I wasn't clear when reporting.

The problem for me was not the image size but what those speed testing tools are saying, so I've tried now to create a site with that image in it : https://hollow-nurse.jurassic.ninja/2019/07/10/sfd/ and tested those tools.

seems like both gtmetrix and pagespeed doesn't have any issue with the image size, I guess can be an old version of the image that user reported or a tool that isn't that popular so we don't care much.

However seems like marius found another issue :)
