### ISSUE TITLE
In the shortcode, separate behavior of meta into author, date and time

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#264]
Currently `meta` takes care of both `author`, `date` and `time` but if someone wants just one, they have no simple recourse

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/265

Documentation: https://docs.themeisle.com/article/1089-how-to-display-author-date-or-time-from-the-feed

The shortcode is backward compatible with the old values `yes` (implies author, date, time) and `no`.

@HardeepAsrani can you add this support to Gutenberg too?

**Comment by HardeepAsrani** [comment]
@contactashish13 Only supported values are author, date & time, right? Are we planning on adding something later too?

Asking just to know if I should leave a text field or checkboxs.

**Comment by contactashish13** [comment]
Can't think of any other field.

**Comment by contactashish13** [comment]
@HardeepAsrani related to this is https://github.com/Codeinwp/feedzy-rss-feeds/issues/278. Please check the PR against that so that you know what additional items can be added.

**Comment by HardeepAsrani** [comment]
@contactashish13 The issue here is that the user can't hide the output. If they leave it empty, it shows everything. There should be an easier way to hide the value.

**Comment by contactashish13** [comment]
`meta=no` is for hiding the output

**Comment by HardeepAsrani** [comment]
@contactashish13 That should be mentioned in the documentation at least. I guess putting any random string will result in nothing being displayed.
