### ISSUE TITLE
onboarding screen looks bad on laptop

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/feedzy-rss-feeds#268]
On what seems to be the most popular resolution here is how the screen looks like : 

https://www.dropbox.com/s/rna8pu6sksc9fw3/Screenshot%202019-07-10%2010.05.34.png?dl=0, probably we can just stack components of the page here. 

cc @contactashish13

**Comment by contactashish13** [comment]
@ineagu this is how they will look now:

![screencapture-localhost-90-wp-admin-admin-php-2019-07-11-11_30_44](https://user-images.githubusercontent.com/12953439/61025800-6637c700-a3cf-11e9-887a-0dc6f9a375fd.png)
![screencapture-localhost-90-wp-admin-admin-php-2019-07-11-11_31_52](https://user-images.githubusercontent.com/12953439/61025834-84052c00-a3cf-11e9-8fd4-64e2e5afe9f4.png)


PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/270

**Comment by ineagu** [comment]
probably those videos can stick to the original ratio, right now is squared forced. Either way those would probably need design work at some point.
