### ISSUE TITLE
Include shortcodes to the filter calls

### ISSUE THREAD

**Issue by radu-themeisle** [Codeinwp/feedzy-rss-feeds#277]
A user has a [small request](https://secure.helpscout.net/conversation/908260842/197117/): _"I need to detect the shortcodes to both of these filters in the callback functions. Can you "add" the shortcodes to the filter calls please?"_

He also provided the following solution:
- Can you change line: 784 in function: public function get_feed_array( $feed_items, $sc, $feed, $feed_url, $sizes )
from: $items = apply_filters( 'feedzy_feed_items', $feed->get_items(), $feed_url );
to: $items = apply_filters( 'feedzy_feed_items', $feed->get_items(), $feed_url , $sc );

- Can you change Line 996 at the bottom of this function: public function feedzy_retrieve_image( $item, $sc = null )
from: $the_thumbnail = apply_filters( 'feedzy_retrieve_image', $the_thumbnail, $item );
to: $the_thumbnail = apply_filters( 'feedzy_retrieve_image', $the_thumbnail, $item , $sc );

**Comment by contactashish13** [comment]
Closing this as this was no longer required after discussing with the user.
