### ISSUE TITLE
New banner and icon images for wordpress.org

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#3]

**Comment by abaicus** [comment]
![banner_feedzy](https://cloud.githubusercontent.com/assets/15010186/14708403/4c0fb216-07d3-11e6-8932-08ebbd8e1e51.png)
![icon_feedzy](https://cloud.githubusercontent.com/assets/15010186/14708402/4c0f2918-07d3-11e6-8a2b-22f9dc8ecb3d.png)
