### ISSUE TITLE
Missing link label in the Feedzy shortcode in classic editor

### ISSUE THREAD

**Issue by IosifGabriel** [Codeinwp/feedzy-rss-feeds#306]
In Other Options, there should be a link at **here** but is displayed as **%1$shere%2$s**
Tested by @SilviuDinu  as well. 

Screenshot here -> http://prntscr.com/p7spnz
version. 3.3.10 (latest)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/307
