### ISSUE TITLE
Feed to Post: Next Run Not Executing

### ISSUE THREAD

**Issue by omar-otieku** [Codeinwp/feedzy-rss-feeds#310]
With the latest version of Feedzy Lite (v3.3.11) and Feedzy (v1.6.8), I have set a new post import job. First execution and the run now feature work as expected, however the "Next Run" feature counts up instead of down to a next execution time and wp_cron never executes new posts. Has the scheduling been mixed up?

**Comment by contactashish13** [comment]
@omar-otieku can you please provide a screen shot/recording to clarify what you mean by "counts up instead of down to a next execution time"?

**Comment by omar-otieku** [comment]
This screen shot shows last execution time 17 hours ago…
![Screen Shot 2019-10-04 at 10 40 06 AM](https://user-images.githubusercontent.com/3989609/66216491-8f48ba80-e693-11e9-8194-d30844e54ae3.png)

This screenshot is in the next minute showing the next execution time increasing…
![Screen Shot 2019-10-04 at 10 40 20 AM](https://user-images.githubusercontent.com/3989609/66216516-9cfe4000-e693-11e9-9133-3fb2a3d79208.png)

Upon further investigation it seems that the scheduled execution time was exceeded and the time difference increases. I have confirmed on next successful execution that next run resets properly.

**Comment by arif497** [comment]
Facing the same problem. Can anybody help to get it fixed?
