### ISSUE TITLE
Changing cache time for widget

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#311]
https://wordpress.org/support/topic/changing-cache-time-for-widget/

**Comment by stefan-cotitosu** [comment]
@contactashish13 thanks for the suggestion, I have created the guide.
https://docs.themeisle.com/article/1159-changing-the-caching-time-interval-in-feedzy-widget

Let me know if there is something that we can improve here. I thought on creating a plugin as well, but I assume that the value can be changed, therefore a plugin would require an input field for the user, and I am not so comfortable with building it.

**Comment by contactashish13** [comment]
@stefan-cotitosu I think having documentation is good enough.
