### ISSUE TITLE
Undefined index: error_empty in /includes/admin/feedzy-wp-widget.php on line 244

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#312]
https://wordpress.org/support/topic/undefined-index-150/#post-12007359

Cannot replicate this.

**Comment by contactashish13** [comment]
@stefan-cotitosu can you please see if you can reproduce this and if you can, share the instance for me to troubleshoot?

**Comment by stefan-cotitosu** [comment]
@contactashish13 I am not able to replicate the issue.

I have tested it in a widget, as per the notice, with both a valid and an invalid feed. The notice didn't show up in either case.

Let me know if I can help you with anything else here.

**Comment by girishkrishaweb** [comment]
PR - https://github.com/Codeinwp/feedzy-rss-feeds/pull/496
