### ISSUE TITLE
Loose Item Character Limit Settings Gutenberg

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#324]
There are some issues with description length which were reported in https://wordpress.org/support/topic/loose-item-character-limit-settings-on-page-edit-in-gutenberg-blocks/

Steps to reproduce:
– Start a new Page
– Use of your Gutenberg Block in new WP Editor (Block “Feedzy RSS Feeds”)
– Set in “Item Options” the “Description Character Limit” to 300
– Save with “Update” (Publish) Button
– Close Edit Page
– Go again to Edit the Page
– See that all made changes in “Description Character Limit” are lost.

**Comment by HardeepAsrani** [comment]
Addressed in https://github.com/Codeinwp/feedzy-rss-feeds/pull/323

**Comment by stefan-cotitosu** [comment]
A similar setting is lost when using the Feedzy Gutenberg Block.

The number of feeds resets to 5, the exact steps mentioned above by Hardeep can be used to replicate the issue. 

- set the number of feeds to a different value than 5
- publish the page
- view page
- edit it back
- the number is 5 again

![feedzy-nb-of-feeds-gutenberg](https://user-images.githubusercontent.com/26867648/69634958-0418ef00-105c-11ea-8162-04c12de41f75.png)

Feedzy version: 3.3.12
WordPress version: 5.3
