### ISSUE TITLE
Notice: Undefined index: tab

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#361]
I get this notice after clicking on Feedzy > Support in the main WP menu. Once I click on the More Featured tab, the notice disappears.

![download](https://user-images.githubusercontent.com/3266155/71816472-5d2c6780-308b-11ea-9ec2-c80440261adb.png)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/381
