### ISSUE TITLE
Weird behaviour for default Number of Items

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#363]
Possibly related to https://github.com/Codeinwp/feedzy-rss-feeds/issues/349.
For **Number of Items**, when you delete the value ( to enter a new one ) it gets reset to 5, but the feeds disappear completely in the editor until you change the number of items again ( on the front-end the feeds display correctly )

https://www.loom.com/share/d812b761d3ef43ebae7c34235db8d414

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/374

**Comment by rodica-andronache** [comment]
@contactashish13 is working well. eyepatch is failing though

**Comment by contactashish13** [comment]
@rodica-andronache eyepatch has been failing for over a year on all PRs - I don't think it is relevant anymore. @selul?

**Comment by selul** [comment]
I don't know whats going on there. 

Feel free to fix it or drop the support for it as you please.

**Comment by contactashish13** [comment]
@rodica-andronache I believe this was released in 3.3.17 and can be closed.

**Comment by DanyCaissy** [comment]
Closing

**Comment by rodica-andronache** [comment]
yes, I've missed it as it wasn't in the review column. Thanks
