### ISSUE TITLE
Gutenberg: Offset works correctly in the front end but not in the backend

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#369]
https://wordpress.org/support/topic/only-displaying-5-posts-in-front-end/#post-12301231

related to #89 

Display 10, Skip 1 means show 10 items from the 2nd item onward (current behavior shows 9)
Display 7 Skip 3 means show 7 items from the 3rd item onward (current behavior shows 4)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/370

**Comment by rodica-andronache** [comment]
https://github.com/Codeinwp/feedzy-rss-feeds/pull/370 is working well for me
