### ISSUE TITLE
Gutenberg: Allow user to dictate order of meta data

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#371]
This https://github.com/Codeinwp/feedzy-rss-feeds/issues/357 is not working in the Gutenberg editor

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/375

**Comment by rodica-andronache** [comment]
@contactashish13 There's one case, where it's not working as expected, in Gutenberg.

You can't **hide the meta options**. When the field is empty, even though no meta appears in the editor, they are displayed on the frontend.

![download (1)](https://user-images.githubusercontent.com/3266155/72739384-37838000-3bac-11ea-8508-d230c5c7482b.png)
![download (2)](https://user-images.githubusercontent.com/3266155/72739404-3e11f780-3bac-11ea-878b-90bab6cc7cae.png)

In the classic editor, this is possible by using `meta=""` in the shortcode.

**Comment by contactashish13** [comment]
@rodica-andronache using `no` in the box is equivalent to `meta="no"`.  I've added a help text to make this more obvious.

PS - In the shortcode `meta=""` and leaving out `meta` should work the same way as `meta="no"` so the behavior of `meta=""` is a minor bug.

**Comment by rodica-andronache** [comment]
@contactashish13 ok, it's working well with `no` in the box. And the text you added is useful.

But when the box is empty, there is still the issue with the meta not displaying in the editor, only on the frontend.

![download (1)](https://user-images.githubusercontent.com/3266155/72739384-37838000-3bac-11ea-8508-d230c5c7482b.png)

**Comment by contactashish13** [comment]
@rodica-andronache fixed this.
