### ISSUE TITLE
WooCommerce Add to Cart Button and View Product in Russian Language 

### ISSUE THREAD

**Issue by ganijon-dev** [Codeinwp/feedzy-rss-feeds#376]
Add to Cart and View in Cart button shows inline and View in Cart Button shows totally wrong instead of displaying up and down 
![Untitled](https://user-images.githubusercontent.com/50183519/72672487-c937a400-3a6b-11ea-9f9a-324ef5c4d884.png)

**Comment by rodica-andronache** [comment]
Hi @ganijon-dev,
This doesn't look to be related to Feedzy, but with the theme you are using ( ShopIsle most likely ). 
Could you share your site URL so I can see the issue?

**Comment by DanyCaissy** [comment]
Closing this as it isn't related to Feedzy. If you still require assistance, please open a ticket on the appropriate plugin repository.
