### ISSUE TITLE
Add individual filters for each meta data

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#379]
ref https://wordpress.org/support/topic/is-there-a-way-to-show-date-as-x-days-months-ago/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/380

**Comment by rodica-andronache** [comment]
@contactashish13 how can the date format be filtered?
I've tried using
`add_filter( 'feedzy_meta_date','change_date_format',10,4 );`
function change_date_format($date,$feed,$item) {
	$newDate = date("m-d-Y", strtotime($date));
	return $newDate;
}`
but it's not returning the correct value because $date has that "on" like `on January 23, 2020`

**Comment by contactashish13** [comment]
@rodica-andronache you can check https://github.com/Codeinwp/feedzy-rss-feeds/projects/1#card-32034790 for an example

**Comment by rodica-andronache** [comment]
thanks 👍
