### ISSUE TITLE
Widget ignores offset 

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#384]
ref https://wordpress.org/support/topic/offset-for-feed-not-working/

PS - widget also ignores `multiple_meta`

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/385

**Comment by DanyCaissy** [comment]
Was this released? Can this be closed? @contactashish13

**Comment by rodica-andronache** [comment]
it was not released, the PR is not merged https://github.com/Codeinwp/feedzy-rss-feeds/pull/385. I closed the issues that were released
