### ISSUE TITLE
Warning: md5() expects parameter 1 to be string, array given in /includes/abstract/feedzy-rss-feeds-admin-abstract.php on line 790

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#386]
ref https://wordpress.org/support/topic/warning-showing-in-widget/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/387

**Comment by rodica-andronache** [comment]
@contactashish13 if there's a specific feed that you've used to replicate this or other specific things that need to be done to replicate the issue, please let me know, so I can test it. I've tried with some feeds but couldn't replicate it

**Comment by contactashish13** [comment]
This happens with multiple feeds in the shortcode.

**Comment by rodica-andronache** [comment]
I couldn't replicate it. can you please share a short video maybe?

**Comment by contactashish13** [comment]
@rodica-andronache it throws no error but it should - if you check https://github.com/Codeinwp/feedzy-rss-feeds/pull/387/commits/f9f61c3dcdf6a01301204b841b51da0ef008ff0e#diff-d0269333c4896cf97aa706ab2830ca9cL790 `md5` function should not accept an array. Nevertheless, it is a problem because the class becomes `feedzy-` instead of `feedzy-<some md5 string>`
