### ISSUE TITLE
Add support to lazy load feed items

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#388]
This happens because the short code goes to fetch/parse the feed the moment the page is loaded. 

One way around this could be:
- fetch/parse the feed in the background every X minutes (Question: X can be given as a shortcode parameter or in the settings screen)
- when the page is loaded, load the above stale data 
- show a spinner that says "fetching new items" which then fetches the new items and displays them (Question: using ajax?)

Question: Does this slowdown happen with the block editor too?

**Comment by contactashish13** [comment]
@DanyCaissy can you check if the above solution is feasible from an end user point of view? If it is, we need to conclude on the best approach/behavior for this.

**Comment by DanyCaissy** [comment]
@contactashish13 

Unless I misunderstood, I think refreshing every X minutes should be a separate enhancement, it could be useful for users but would not solve the problem described (slow initial page load).

For that, I think loading the page first, and then loading the feeds once the page is ready (with ajax) would be a good idea, although we'd have to try it out to be sure. Using a spinner whilst it loads would be a nice addition.

**Comment by selul** [comment]
just an idea here in case you find it useful, this kind of behavior can be called lazyloading and can be turned into a shortcode/block option. 

The lazyload feature basically would show a spinner, call a WP-Rest API route which could return the item feeds once ready and replace spinner with the feed content.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/390

An additional parameter `lazy='yes'` in the shortcode enables this. In the block editor, this translates to an additional toggle.

**Comment by rodica-andronache** [comment]
I've tested the shortcode, the GB block and the widget and everything was ok, except these notices that appear when using the GB block with the Lazy Load feature
![download](https://user-images.githubusercontent.com/3266155/74250515-66949980-4cf3-11ea-89df-8599bd0f6641.png)
![download (1)](https://user-images.githubusercontent.com/3266155/74250538-6e543e00-4cf3-11ea-909a-192b8fd005ca.png)
![download (2)](https://user-images.githubusercontent.com/3266155/74250553-7613e280-4cf3-11ea-9324-9ea33d11be34.png)

**Comment by rodica-andronache** [comment]
@contactashish13 I still get those notices. As a note, the notices don't appear in the editor, but on the frontend.
![Screenshot](https://user-images.githubusercontent.com/3266155/74840137-20f95180-532f-11ea-8692-e59856b5573e.png)

**Comment by contactashish13** [comment]
@rodica-andronache I cannot reproduce it.  Can you please mention all the field values so that I can test with the same values as you? (also for the future)

**Comment by contactashish13** [comment]
@rodica-andronache this should be okay now.

**Comment by rodica-andronache** [comment]
https://docs.themeisle.com/article/1220-lazy-loading-feed-items-with-feedzy
