### ISSUE TITLE
Add feedzy button to classic editor in gutenberg

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#389]
As per the tutorial video, on the classic editor, you can add a feedzy feed this way: https://i.imgur.com/IDEnyE1.png

When I tried to do so, the button did not seem to exist: 

https://i.imgur.com/Stk8nZm.png

This can be reproduced on this instance: 

https://formal-crab.jurassic.ninja/wp-admin/post.php?post=1&action=edit
WP user: demo WP/SSH password: SvW9h0QQTYyc

**Comment by contactashish13** [comment]
@DanyCaissy this is not the classic editor; it is a rich text editor (RTE) in gutenberg. Classic editor is the whole interface which happens to contain the RTE. If other plugins that create a button in the classic editor also create a button in the RTE in gutenberg, we can try to add it too and this can be added as an enhancement. It is not a bug.

**Comment by DanyCaissy** [comment]
@contactashish13 

Yeah I wasn't sure what to call this editor, I know it's not the true classic, but it's called classic editor.

Visualizer does have a button on this editor: https://i.imgur.com/Bf7KyDL.png

I'll list this as an enhancement then.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/391
