### ISSUE TITLE
Using widget with page builders throws notice 

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#394]
https://wordpress.org/support/topic/php-fatal-error-197/

https://wordpress.org/support/topic/wp-error-unless-feedzy-deactivated/

```
[13-Feb-2020 04:05:18 America/New_York]
PHP Fatal error: Uncaught Error: Call to undefined function get_current_screen() in …/wp-content/plugins/feedzy-rss-feeds/includes/admin/feedzy-wp-widget.php:82
Stack trace:
#0 …/wp-content/plugins/fusion-builder/inc/helpers.php(2379): feedzy_wp_widget->form(Array)
#1 …/wp-content/plugins/fusion-builder/inc/helpers.php(2348): fusion_get_widget_data()
#2 …/wp-content/plugins/fusion-builder/shortcodes/fusion-widget.php(492): fusion_get_available_widgets()
#3 …/wp-includes/class-wp-hook.php(288): fusion_element_widget(”)
#4 …/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#5 …/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 …/wp-settings.php(545): do_action(‘wp_loaded’)
# in …/wp-content/plugins/feedzy-rss-feeds/includes/admin/feedzy-wp-widget.php on line 82
```

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/395

**Comment by purplecodes** [comment]
+1 on this issue
- issue occurs after updating to Avada v6.2
https://secure.helpscout.net/conversation/1084682836/216857/

**Comment by rodica-andronache** [comment]
@contactashish13 whenever possible, could you please offer all the details needed on how to replicate/test an issue/PR? It takes additional time to read all the tickets as well, and sometimes I can't figure it out anyway. If it helps, here's an example of a PR that helps me with testing https://github.com/Codeinwp/neve-pro-addon/pull/562
In this case, for example, I've tried activating Avada, installed SiteOrigin but couldn't replicate this.
Thanks

**Comment by contactashish13** [comment]
@rodica-andronache there are some tickets, like this one, that I am not able to reproduce but the error is obvious as shown in the error logs shared by the user and so the solution, from a code point of view, becomes obvious. Maybe this got fixed with the new version of Avada, I don't know.

**Comment by rodica-andronache** [comment]
@contactashish13 ok, and for this case do you think we should merge https://github.com/Codeinwp/feedzy-rss-feeds/pull/395?
I've tested with both that and the latest version of Feedzy and couldn't replicate that issue in Avada. From what I've seen they've had a patch for that from within the theme, and it looks to be working well.

I was thinking we could close the PR for now, if you think so.

Apart from that, I've noticed two other notices when using the Feedzy widget inside Avada's Fusion Builder, which I think could be fixed.
![download (1)](https://user-images.githubusercontent.com/3266155/75678526-84bc3c80-5c96-11ea-8ea0-1985640e89c5.png)
![download (2)](https://user-images.githubusercontent.com/3266155/75678534-88e85a00-5c96-11ea-801b-6cf953cf9b79.png)

I've tested with `https://www.codeinwp.com/feed/` and didn't make any other changes in the widget.

**Comment by contactashish13** [comment]
@rodica-andronache I've closed the PR.

can you please check if https://github.com/Codeinwp/feedzy-rss-feeds/issues/312 is related to the errors you get?

**Comment by rodica-andronache** [comment]
@contactashish13 not sure how to check if those are related. It looks to be different errors

**Comment by contactashish13** [comment]
@rodica-andronache can you please add a video that shows the steps you took to add the widget using avada?

**Comment by rodica-andronache** [comment]
@contactashish13 
https://www.loom.com/share/98654176019a4ea4bc6452c5cd9efac8
Make sure Fusion Core and Fusion Builder are installed
![download (2)](https://user-images.githubusercontent.com/3266155/75860082-e77f1680-5e03-11ea-9237-9875ca13a09b.png)

**Comment by contactashish13** [comment]
@rodica-andronache I don't seem to have `widget` in the list of elements; only `widget area`.  I have avada 5.8.2

**Comment by rodica-andronache** [comment]
@contactashish13 I've tested with Avada 6.2.1. I'll share the archive on slack

**Comment by contactashish13** [comment]
@rodica-andronache I've updated the theme and the dependent plugins but still no `widget`

![image](https://user-images.githubusercontent.com/12953439/76726552-76cae900-6777-11ea-93bc-61be47385046.png)

Anyways, I've tried to fix it in PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/406, Can you test it?

**Comment by rodica-andronache** [comment]
@contactashish13 there's a warning for `lazy` as well, I guess the same check can be applied.
![download (3)](https://user-images.githubusercontent.com/3266155/76738340-1c2f8e00-6773-11ea-8e66-f0021c8a6f30.png)

This PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/406 also contains the changes you've done here https://github.com/Codeinwp/feedzy-rss-feeds/pull/395 and closed as it looked to be related to Avada. Shouldn't it removed from here as well?

**Comment by contactashish13** [comment]
@rodica-andronache have created a new PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/407 so that its clean.
