### ISSUE TITLE
Icon links keep reappearing in Zelle Lite front page widgets

### ISSUE THREAD

**Issue by JustMelBell** [Codeinwp/feedzy-rss-feeds#396]
One the frontpage Our Team section of the Zelle Lite template, the icons for social media links keep showing up despite there being nothing in those fields of the widget for that person. When I go in to delete the blank spaces (that auto populated in that field out of nowhere), it disappears. Then when I go down and do the next one, the first one reappears. And it does this again and again.

**Comment by contactashish13** [comment]
closing as this is not related to feedzy
