### ISSUE TITLE
Add the "help us improve!" tab for surveys

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#397]
Similar to Visualizer: https://i.imgur.com/SPFlkU0.png

We can add this tab in the support menu, the survey links are:

Free: https://forms.gle/yQUGSrKEa7XJTGLx8
Pro:  https://forms.gle/FZXhL3D48KJUhb7q9

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/405

**Comment by DanyCaissy** [comment]
@contactashish13 

When pro is installed, the link is still for the free version for me.

https://ideological-booby.jurassic.ninja 
WP user: demo WP/SSH password: 2wcAhYqZMh8P

**Comment by rodica-andronache** [comment]
for me, it's working well

**Comment by DanyCaissy** [comment]
@contactashish13 @rodica-andronache 

This is still happening to me, Rodica can you describe the steps you've done?

When pro is installed I still get the link to the free survey.

This is the free survey, not pro: https://docs.google.com/forms/d/e/1FAIpQLScg9Lt_XSFI_WCuWe-Q_lyfDqIdBOjDxrFkytq_9sYdk3WlPQ/viewform

I have installed the files below, you can check on this instance:

https://living-petrel.jurassic.ninja 
WP user: demo WP/SSH password: WpJPrUG3no3R

[feedzy-rss-feeds.zip](https://github.com/Codeinwp/feedzy-rss-feeds/files/4368965/feedzy-rss-feeds.zip)
[feedzy-rss-feeds-pro.zip](https://github.com/Codeinwp/feedzy-rss-feeds/files/4368966/feedzy-rss-feeds-pro.zip)

**Comment by rodica-andronache** [comment]
@DanyCaissy I've tested again and it's working well for me.
I've installed the development branch from https://github.com/Codeinwp/feedzy-rss-feeds and for the PRO version I downloaded it from store.themeisle.com. I've also tested with the development version from Github.
I've tried multiple times and I get the PRO form https://docs.google.com/forms/d/e/1FAIpQLSc9TkrviS3KBkgVTC29lLZ4vmqm5fGQ3korQKlvOTqQ0GlsEg/viewform

I've checked your instance and indeed it's not working properly. I checked on my local with the archives you provided and it's not working. So, there must be something wrong with those, I suppose

**Comment by DanyCaissy** [comment]
@rodica-andronache 

[2020-03-23_20-20-55.zip](https://github.com/Codeinwp/feedzy-rss-feeds/files/4369284/2020-03-23_20-20-55.zip)

I've done the whole process in the video above and I still get the free link. Can you tell me what I did wrong here then?

**Comment by rodica-andronache** [comment]
@DanyCaissy I honestly don't know. I've tried on a Jurassic as well and it's working
https://deep-asp.jurassic.ninja/wp-admin/
`demo / e#o3eijqI%fN$7U2VwudYGB!`

**Comment by DanyCaissy** [comment]
@rodica-andronache I've removed pro and installed mine, it was fine.

I've removed free and installed mine, then it's showing the free link again. This seems related to the free installation.

The free installation as you saw I just used your link this time, did composer update, and rezipped it. There is nothing else about it that I've done.

Have you done these exact steps? There must be a difference.

http://github.com/Codeinwp/feedzy-rss-feeds/archive/development.zip
[feedzy-rss-feeds-development.zip](https://github.com/Codeinwp/feedzy-rss-feeds/files/4369413/feedzy-rss-feeds-development.zip)

**Comment by rodica-andronache** [comment]
@DanyCaissy I run `composer install`, I think that's the only difference

**Comment by DanyCaissy** [comment]
@rodica-andronache 

It doesn't make a difference.

Can you take a video of you getting the free development version from scratch and installing it on the same instance you created earlier?

**Comment by rodica-andronache** [comment]
@DanyCaissy https://www.loom.com/share/8fc37b88d6ca49c5a0c4b81d38f41f15

**Comment by DanyCaissy** [comment]
@rodica-andronache 

It seems to do that if the folder name is different. Your steps worked for me, but if I renamed the folder to anything else, it shows the wrong link. When downloading the file instead of cloning it the folder name is different.

I tested it with the correct folder name earlier, but I still had the issue, maybe I had a typo somewhere..

Either way, this means that for this specific link, it determines whether free is installed based on the folder name. The message "This theme requires the following plugin: Feedzy RSS Feeds Lite." also goes off of that assumption.

Do you think we should use a different way to determine whether free is installed or not?

**Comment by rodica-andronache** [comment]
@DanyCaissy I'm not completely sure, but I think yes, that shouldn't be checked based on the name of the folder. At least, for Neve, we had a similar thing, and we've changed it.

**Comment by contactashish13** [comment]
@DanyCaissy @rodica-andronache existence of pro is determined by the existence of a filter **not* the folder name. If that were the case then no functionality of pro would work.

**Comment by DanyCaissy** [comment]
@contactashish13 You're welcome to attempt it, change the folder name of feedzy free and install it, you'll see the " "This theme requires the following plugin: Feedzy RSS Feeds Lite." " message and the survey link will be wrong.

The message also happens with Visualizer ever since I've started working on it.
