### ISSUE TITLE
Use Visualizer's font/spacing for support/settings pages

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#398]
Feedzy: https://i.imgur.com/mol1G5d.png
Visualizer: https://i.imgur.com/BtugYjK.png

Comparing both, it seems to me that Feedzy's support pages use larger fonts and contain more unnecessary whitespace. 

I think Visualizer's is more readable and and it'd be a good idea to standardize both.

**Comment by DanyCaissy** [comment]
In addition to that, I'd like to add an intro, same as on Visualizer's page. I've included the HTML in the file below, although it will have to be adapted (format, URLs, is_pro condition)

[feedzy-intro.txt](https://github.com/Codeinwp/feedzy-rss-feeds/files/4378222/feedzy-intro.txt)

**Comment by contactashish13** [comment]
PRs https://github.com/Codeinwp/feedzy-rss-feeds/pull/427  (this addresses #416 as well) and https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/330 

In new free/old pro, the contact us tab will look a little drab but that should not be a big problem.

@rodica-andronache @DanyCaissy this can be released in the current version as well if you want.

**Comment by DanyCaissy** [comment]
This is fine. I think it can wait for next release as its not time-sensitive.

**Comment by rodica-andronache** [comment]
the only issue I saw was that in the free version we have this link to import a post, which does not exist in the free version
![download (1)](https://user-images.githubusercontent.com/3266155/81812813-5200b100-952f-11ea-89ad-994162e280f9.png)
![download (2)](https://user-images.githubusercontent.com/3266155/81812888-693f9e80-952f-11ea-8264-cbfe9ee668ec.png)

**Comment by rodica-andronache** [comment]
actually I've just remembered that we'll have the Feed to Post in the lite version as well. everything's ok
