### ISSUE TITLE
Valid feeds not importing

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#399]
Some feeds will not import through Feedzy even though they are valid feeds. 

They are valid as per w3 (https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Ffurtherafrica.com%2Ffeed%2F) and also work with RSS Aggregator:

https://karishmachugani.com/category/this-body-is-human/feed/
https://analytik.news/fachartikel/rss.xml
http://www.mezzacotta.net/100proofs/feed
https://furtherafrica.com/feed/
https://www.iis.unam.mx/event/feed/

Please investigate the reason why these don't work with Feedzy and see if that can be resolved.

**Comment by sufehmi** [comment]
Why is this issue closed already ? 

I have similar problem with https://turnbackhoax.id/feed/?s=corona , 

Feedzy won't import anything from it, even though it works fine on https://simplepie.org/demo/

Any ideas ?

**Comment by DanyCaissy** [comment]
@sufehmi 

These ended up working on the current version.

The reason it's not importing might be due to missing settings.

Notably, on the last page, please make sure the title and the content fields are both filled. Your feed worked for me that way: https://i.imgur.com/8i9VY7U.png
