### ISSUE TITLE
Nothing getting imported

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#400]
On a fresh install, after installing current free + pro, it does not seem like anything is getting imported:

https://i.imgur.com/lXnnSbZ.png

Instance:

https://silent-hedgehog.jurassic.ninja 
WP user: demo WP/SSH password: xeabFv94Bac7

**Comment by DanyCaissy** [comment]
@contactashish13 Can you take a look? Did I miss something?

**Comment by contactashish13** [comment]
@DanyCaissy is there a reason you did not add **anything** to the last screen? If either title or content is empty, nothing will be imported as this is not a valid use case.

**Comment by DanyCaissy** [comment]
I think I assumed there was a default or that validations wouldn't have let me save if the entry was invalid. I think this assumption is shared as many users complained of "nothing getting imported" in uninstall reasons, I'll address changes to that in future tickets.

**Comment by contactashish13** [comment]
I don't think that was their reason. Theirs would have been using an invalid feed. Defaults don't make sense and we have had no tickets that suggest defaults

**Comment by DanyCaissy** [comment]
What makes no sense is an import that succeeds yet imports nothing when the feed is valid. This gives no feedback to the user as to what went wrong. The expected behavior of an import with no content would be posts with no content, not the absence of posts being created, as the later implies the feed is invalid or empty.

Defaults obviously make sense, you can't expect every useful change to be suggested before-hand. If we relied only on suggestions we'd still be asking for "faster horses".

**Comment by contactashish13** [comment]
Posts with no content and no title? You may have to take this up with the creators of WordPress then as they, in their infinite wisdom, decided that such posts cannot be created programmatically. Had you selected either of those, posts would have been created as per your expectation.

**Comment by DanyCaissy** [comment]
I'm just saying that's the expected behavior of such a scenario, not that it should be implemented like that. 

We just need some kind of warning/error/validation to be put in place, or defaults, or both.
