### ISSUE TITLE
Conflict with Rss Aggregator in gutenberg editor

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#403]
**Description:** 

When adding a feed with the gutenberg editor, IF rss aggregator is installed, it will say "Feed URL invalid"

**Steps to reproduce:** 

* Create a new instance
* Install Feedzy 
* Install Rss Aggregator non-activated
* Add a feed on the gutenberg editor (ex: https://rss.nytimes.com/services/xml/rss/nyt/US.xml)
* Activate Rss aggregator
* Add the same feed again (it will cause the error then)

![2020-03-07_20-58-44](https://user-images.githubusercontent.com/5183243/76144027-386a6580-60b7-11ea-9e00-fa2148c010e0.gif)

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/404

**Comment by DanyCaissy** [comment]
@contactashish13 Could not reproduce anymore, issue fixed.
