### ISSUE TITLE
bulk activation of plugin aborts activation of subsequent plugins

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#417]
tested in reference to https://wordpress.org/support/topic/bug-in-plugin-activation/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/418

**Comment by rodica-andronache** [comment]
this is also not working for me, similar to https://github.com/Codeinwp/visualizer/issues/679

**Comment by contactashish13** [comment]
@rodica-andronache I've changed the methodology and it should work anywhere.
