### ISSUE TITLE
Sync item image options between classic and block editor

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#429]
Not all options (highlighted), that are available in the classic editor, are available through the block editor.

Classic editor:

![image](https://user-images.githubusercontent.com/12953439/82296482-e014e580-99ce-11ea-96d9-f4cce02552c0.png)

Block editor:

![image](https://user-images.githubusercontent.com/12953439/82296572-02a6fe80-99cf-11ea-9d1b-68b21ee10906.png)

+ Improvements suggested in https://github.com/Codeinwp/feedzy-rss-feeds/issues/440

**Comment by rodica-andronache** [comment]
@contactashish13 I'm not exactly sure what's the correct behaviour, but there are some inconsistencies between classic and block editor.

**In the Classic editor**
If I chose `Auto, with a fallback image` and for the HTTP option I chose `Ignore and show the default image instead`, **on frontend there is no image**
![1](https://user-images.githubusercontent.com/3266155/88026470-98c9e300-cb3e-11ea-8021-708a58609409.png)
![2](https://user-images.githubusercontent.com/3266155/88026505-a1bab480-cb3e-11ea-89db-1543cf5a96c4.png)

**In the Block editor**
If I chose `Auto, with a fallback image` and for the HTTP option I chose `Ignore and show the default image instead`, **in the editor I see the default fallback image, on frontend I see my custom fallback image.**
![3](https://user-images.githubusercontent.com/3266155/88026673-e0e90580-cb3e-11ea-9cfe-485e3812122e.png)
![4](https://user-images.githubusercontent.com/3266155/88026686-e5152300-cb3e-11ea-8776-aafb87e493ec.png)

**Comment by contactashish13** [comment]
@rodica-andronache Assuming the shortcode will contain the attributes ```thumb="yes"  http="default" default="..."```, the behavior, I believe, should be as follows:

- if a default image is not provided, it is assumed to be the feedzy icon
- the default image now becomes the image to be used for the item (if the item does not have an image)
- the `http` attribute is then used to check if that image needs to be overridden or ignored

I've addressed this as follows:

- the `default` attribute in the shortcode that corresponds to the fallback image, if provided, will override the feedzy icon
- in the block editor when a fallback image is chosen, the block will refresh and show the chosen image
- in the block editor when a fallback image is removed, the block will refresh and show the feedzy icon

Thus the behavior across both the editors and back/front end should be identical.

When I tested before making these changes, the behavior in both editors was consistent. I'm not sure why you see a different behavior. Could it be because you chose `auto` when it means `without fallback image` and that's why you get no image? Can you check that the values of the attributes are as above when you use the popup wizard to generate the shortcode?

**Comment by rodica-andronache** [comment]
@contactashish13 the only case where things are different now on editor/front-end is in the `Gutenberg block`, with `Yes ( with a fallback image)` + `Force HTTPS`. 
In the editor you don't see any image and on the frontend, you see the fallback image
![2](https://user-images.githubusercontent.com/3266155/88163861-f41dd300-cc1b-11ea-9254-e0e0cd3c3b8a.png)
![1](https://user-images.githubusercontent.com/3266155/88163870-f849f080-cc1b-11ea-991a-16e6f0a5fa19.png)

**Comment by contactashish13** [comment]
@rodica-andronache I cannot reproduce this. I get images on both back end and front. That said, can we avoid testing with themeisle/codeinwp/wild feeds? I test with a local feed that seems to be more consistent in terms of behavior. I would suggest using a similar feed. You can use either of these as these are what we use in cypress too: https://s3.amazonaws.com/downloads.themeisle.com/sample-feed.xml, https://s3.amazonaws.com/downloads.themeisle.com/sample-feed-multiple1.xml, https://s3.amazonaws.com/downloads.themeisle.com/sample-feed-multiple2.xml

**Comment by rodica-andronache** [comment]
@contactashish13 on my local is the same, testing with those feeds. But I've realised that I don't have HTTPS enabled there, so I gues that's the issue, even though I don't understand why on frontend, the images appear. If you feel is ok, we can leave it like this
