### ISSUE TITLE
Present Feed2Post in the free version

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#435]
@DanyCaissy now that we have a basic version of Feed2Post in Feedzy Free, maybe we can make small updates on these pages for it
https://wordpress.org/plugins/feedzy-rss-feeds/
https://themeisle.com/plugins/feedzy-rss-feeds/upgrade/
https://themeisle.com/plugins/feedzy-rss-feeds/

**Comment by DanyCaissy** [comment]
The readme has been modified here: https://github.com/Codeinwp/feedzy-rss-feeds/pull/437

**Comment by DanyCaissy** [comment]
@rodica-andronache 

I've tried editing the https://themeisle.com/plugins/feedzy-rss-feeds/ page however if I change a picture the entire page gets out of alignment even though the new picture has the same dimensions.

Could you take a look at why that is?

The only change I want to do is to change this: https://i.imgur.com/XqlF58K.png

To using this text and image, on both pages:

"Filter which posts you want to include when using our feed to post feature. Include or exclude posts based on keywords and control how many feed items get imported"

![FeedFilters](https://user-images.githubusercontent.com/5183243/83375364-a82d7b00-a39c-11ea-8155-b1735ca5bb6e.png)

**Comment by rodica-andronache** [comment]
@cosmin-serbanescu can you please help Danny with this?

**Comment by cosmin-serbanescu** [comment]
@rodica-andronache @DanyCaissy it's replaced now but really had no issues in updating it. 

However in the past there was such a problem when updating a post/page/cpt - the easiest solution was to clear the Autoptimize cache so if it happens again: https://prnt.sc/t1dbzn

**Comment by rodica-andronache** [comment]
thanks 👍
