### ISSUE TITLE
Feed2Post: Give user clarity on import error

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#436]
### Description:
Right now, if something goes wrong we just say `Nothing Imported`. This may end up confusing users and creating more tickets.

We can provide more clarity on 
- what went wrong
- how many duplicates were found

**Comment by contactashish13** [comment]
@DanyCaissy do you have any suggestions here?

**Comment by DanyCaissy** [comment]
@contactashish13 I haven't looked into this yet. Please don't push new features ahead until they've been defined and I've put them into next/current release.

**Comment by DanyCaissy** [comment]
I think this would be an important improvement, I don't have many specific suggestion, the more details we can give in the error the better.

I think we might need to show the errors in the popup (opens when you click "click here for import errors") as they could get large. A few things I can think of:

- Feed is empty
- Feed is invalid (show url to validator website)
- Warning: There were X duplicates: (list of links of all duplicates)
- Anything else you can think off

**Comment by contactashish13** [comment]
PRs https://github.com/Codeinwp/feedzy-rss-feeds/pull/446 and https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/343

Changes:
- show a `source` column
- show `items imported across runs`
- show errors with an icon and separated by a horizontal rule

![image](https://user-images.githubusercontent.com/12953439/84740062-599df480-afca-11ea-9b3c-b639d27b6aeb.png)

- show `Total items found` and `Duplicates found` with a clickable number that opens a pop-up. If duplicates are 0, that message will not show.

![image](https://user-images.githubusercontent.com/12953439/84740206-99fd7280-afca-11ea-973d-ab601fc908bd.png)

**Comment by contactashish13** [comment]
PRs https://github.com/Codeinwp/feedzy-rss-feeds/pull/454 and https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/352 will additionally notify any validation errors (e.g. license invalid ) from the full content service.
