### ISSUE TITLE
Lazy loading not being applied

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#438]
### Description:

When adding an RSS feed as a block and applying lazy loading, it does not seem to apply.

### How to reproduce:

1. Create a Feedzy block
2. Add > 40 items
3. Apply lazy loading
4. View the page generated, all items are loaded at the start

### Reference:

![2020-06-01_00-36-51](https://user-images.githubusercontent.com/5183243/83376461-4b33c400-a3a0-11ea-98de-f3b8b84996b7.gif)

### Technical info
* WordPress version: 5.4.1
* Plugin version: 3.4.0

**Comment by contactashish13** [comment]
@DanyCaissy the items loaded at the start are from the cache that is built when you save the block (or the last time the feed was loaded). The lazy loading comes **after** that. There is no point showing an empty block and then showing a lazy load. 

It's the same behavior with the shortcode.

**Comment by DanyCaissy** [comment]
@contactashish13 I'm not sure I understand your comment. As per the scrollbar all items are loaded after the refresh of the page, I didn't notice a difference with or without the option.

**Comment by contactashish13** [comment]
@DanyCaissy you may want to reduce the number of items to 1 and see that the loading icon appears, reloads the feeds and then disappears. With 40+ items, you won't see this behavior as it loads in the middle of the entire block.

**Comment by DanyCaissy** [comment]
@contactashish13 So the lazy loading feature loads all the feeds at once, but it does so after the rest of the page is loaded?

I expected it to load say 10 feeds and only load the rest upon scrolling down. But it does specify front-end only, so I understand the limitation.

The next refresh is then faster, is the result cached in the browser, or?

**Comment by contactashish13** [comment]
@DanyCaissy When you create the block, the feed is parsed and cached. When you load the feed on the front end, the cached data is shown. This caching is done at the WP end not in the browser. When you load the feed on the front end, the cached data is shown first and then the feed is reloaded.
