### ISSUE TITLE
Default option to remove duplicates

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#439]
### Description:

A category that contains one or multiple feeds, in which an article is duplicated, it will post that article twice. We'd like the user to have an option to purge all duplicates.

Current this can be achieved with this: https://docs.themeisle.com/article/638-how-to-eliminate-duplicate-feed-item

However it'd benefit non-technical users to be able to do this with a checkbox as it is a common request.

### How to reproduce:
1. Create a category with the two Feeds (I'll provide them below)
2. Create a new import based on that category alone
3. Run the import

### Current behaviour:

Ten posts are created but include duplicates (https://i.imgur.com/K8s4YFf.png)

### Desired behaviour:

Ten non-duplicate posts are created

### Details of implementation

This would be a simple checkbox here at the bottom, Free+Pro: https://i.imgur.com/BaJzXHn.png
It would be called "Remove Duplicates", 

There would be the following disclaimer below the field: "To understand how duplicates will be removed, check out our [documentation](doc link).

Our existing documentation page will be updated to explain how we remove duplicates, and there will still be an add_filter section for those who want to customize the behavior.

Regarding how it should work in practice:

A) Assuming the example above, 10 non-duplicate posts should be created, meaning if there are 4 duplicates, we'd actually 'read' 14 posts.
B) A post will be considered duplicate if it contains the same url as another post
C) An import job will never import a duplicate for that same job, even if the duplicate is in a previous run. This will require the completion of https://github.com/Codeinwp/feedzy-rss-feeds/issues/445 first.

###Reference:

You can use the following feeds as example:

https://rss.nytimes.com/services/xml/rss/nyt/MediaandAdvertising.xml
https://rss.nytimes.com/services/xml/rss/nyt/Business.xml

However, these may not have the duplicates anymore at the time you test this. So I am providing them in their current state below:

[rssfeeds.zip](https://github.com/Codeinwp/feedzy-rss-feeds/files/4714652/rssfeeds.zip)

### QA

We will have to test these scenarios:

1- Single feed that contains duplicates inside it
2- Multiple feeds added separately that contain duplicates
3- Category that contains multiple feeds which have duplicates

In all those scenarios there should be no duplicates.

**Comment by DanyCaissy** [comment]
C) Will require us linking import jobs to posts, which I don't think we do yet. This feature will be developer after we link these.

**Comment by girishkrishaweb** [comment]
@DanyCaissy We have added a new feature as you describe in the ticket description.

Here is the screenshot of the plugin settings page from the admin interface 
![duplicate-post-plugin-settings](https://user-images.githubusercontent.com/79647963/114389221-5bb4ed80-9bb2-11eb-8830-3501412c8100.png)
(duplicate-post-plugin-settings.png) where you can enable and disable duplicate feed import using the checkbox. Also, the filter is working as it should be.

To test this function, You need to follow the above setup which you describe in the ticket description of the implementation.

**Comment by irinelenache** [comment]
@girishkrishaweb @selul Tested it and the feature works fine, but i don't know if the numbers in the run status are ok. For a feed with 10 items (2 of them duplicates) i get this output https://prnt.sc/123ewi2 . Shouldn't it be `Found: 10 , Imported: 8` ?

**Comment by selul** [comment]
yes, they should

**Comment by girishkrishaweb** [comment]
@irinelenache Yes, It should be like that. and we have added a new patch to match the above output.
