### ISSUE TITLE
Improve text of Item Image Options

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#440]
### Description:

Currently we have this: https://i.imgur.com/CwVafBS.png

We could do the following changes to improve the UX:

1- Remove the "auto" option, default should be set to yes. The default thumbnail feature should be visible right away.

2- Ensure the image does not clip over the "remove" button. It does currently on my screen: https://i.imgur.com/0JIQgKG.png

**Comment by contactashish13** [comment]
@DanyCaissy there is a big difference between `yes` and `auto`. Auto shows the image if available and leaves it blank if not found. Yes means show the default image (feedzy icon) if the image is not found. This option should remain as it is. It would be a good idea for you to check the documentation for these options and update them in case such things are not mentioned.

**Comment by DanyCaissy** [comment]
@contactashish13 Where is the documentation for this field? I couldn't find it.

**Comment by contactashish13** [comment]
@DanyCaissy it would be part of the same document that shows the shortcode parameters. If you cannot find it, that's another part of the problem - a ready reference to all documents is not available.

**Comment by DanyCaissy** [comment]
@contactashish13 I see the property listed [here](https://docs.themeisle.com/article/1130-how-to-use-feedzy-with-a-shortcode), although it's not explained.

Before I add detail to that, I'm struggling to understand your description of the behaviour. You say "yes" shows the feedzy icon, but the question is "Should we display the first image of the content if it is available?", so it should show that first image and not the default based on that question, no?

Other than the documentation change, for this ticket, we can do the following changes:

1- Add the link to the shortcode documentation (above) below the title in the shortcode block: https://i.imgur.com/ZWa0PIS.png
2- Ensure the image does not clip over the "remove" button. It does currently on my screen: https://i.imgur.com/0JIQgKG.png

**Comment by contactashish13** [comment]
@DanyCaissy I think you are misunderstanding the context. Can you review https://github.com/Codeinwp/feedzy-rss-feeds/issues/440#issuecomment-643064669 again?

> Yes means show the default image (feedzy icon) if the image is not found

The changes you have suggested will be done as part of #429

**Comment by DanyCaissy** [comment]
@contactashish13 Re-reading it doesn't make more sense to me. It doesn't make sense in the context of the question for that field.

**Comment by rodica-andronache** [comment]
@DanyCaissy I just wanted to share my opinion too, if you find it useful. I find the option a bit confusing too.
But I don't think removing the `Auto` option would be the best solution as it would change the current behavior for clients that already use it.
What I would do ( if just updating the documentation is not enough ) is to rename the options to something like:
`Auto` to `Yes (without a fallback image)`
`Yes` to `Yes( with a fallback image )`
`No` to remain `No`

**Comment by DanyCaissy** [comment]
@rodica-andronache Yes I think that would be easier to interpret and wouldn't require technical changes. That sounds good for me.

**Comment by contactashish13** [comment]
@DanyCaissy I don't see the second problem. @rodica-andronache can you reproduce this?

![image](https://user-images.githubusercontent.com/12953439/86894575-ded77d80-c120-11ea-8d15-c0bf66be78ea.png)

**Comment by rodica-andronache** [comment]
@contactashish13 can't replicate it either. maybe @DanyCaissy can share on which device/browser is testing

**Comment by DanyCaissy** [comment]
I'm not able to reproduce it anymore. Maybe there was something odd with the image dimensions I had used then. We can ignore that issue unless it reoccurs.

**Comment by rodica-andronache** [comment]
@contactashish13 I think you've reversed the options here.
Auto should be Yes (without a fallback image)
Yes should be Yes( with a fallback image )

**Comment by rodica-andronache** [comment]
@contactashish13 we should also update the options in the Classic Editor
<img width="1099" alt="Screenshot 2020-07-21 at 10 34 08" src="https://user-images.githubusercontent.com/3266155/88026007-d843ff80-cb3d-11ea-832e-dcdeb406f89e.png">

**Comment by contactashish13** [comment]
addressed both your observations @rodica-andronache

**Comment by rodica-andronache** [comment]
Thanks, @contactashish13. 
I was thinking now, that it would also be a good idea to rename the `Default thumbnail URL if no image is found.` option to
`Fallback image used if no image is found.` to have some consistency, if you feel is a good idea as well.
![99](https://user-images.githubusercontent.com/3266155/88030064-74bcd080-cb43-11ea-9ba2-c1e806b7be61.png)
![100](https://user-images.githubusercontent.com/3266155/88030076-771f2a80-cb43-11ea-9ff4-d129aef5ee3b.png)

**Comment by contactashish13** [comment]
@rodica-andronache done
