### ISSUE TITLE
Feed2Post - Default Featured Image

### ISSUE THREAD

**Issue by DanyCaissy** [Codeinwp/feedzy-rss-feeds#441]
### Description:

In the featured image section: https://i.imgur.com/wwt1Eux.png

We want to add:

1- An "exclude posts with no images" checkbox. By default this won't be checked.
2- IF the above checkbox is NOT checked, the option "Default image (if post does not contain any)" will appear. This will contain an upload button that will function identically to the one in image options: https://i.imgur.com/l03Du9o.png

Important note: The checkbox should hide/show the "Default Image" whenever clicked. There is a possibility someone would upload an image and THEN click the checkbox. In that case, the checkbox takes precedence and the default image will be ignored.

Reminder: Once this feature is live, it might be worth reaching out to some recent users that requested it (https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/262)

**Comment by contactashish13** [comment]
@DanyCaissy  I'm not sure the suggested behavior works well with the already available option of `'Featured Image`. Can you think of all the possible scenarios by taking the options of `'Featured Image` into account?

**Comment by DanyCaissy** [comment]
@contactashish13 

Yeah I think I see what you mean. There might be extra edge cases. One thing is, none of those options matter if the the "featured image" field is empty, so we could show them only if the field was filled.

So all the fields above should only be displayed if "featured image" contains something (more than spaces), otherwise they shouldn't be visible to the user. Another way to implement it would be to have a checkbox "include featured image" that would show ALL fields if checked-on, and make featured-image a required field whilst checked.

If featured-image is empty, none of the above new fields should apply.

Let me know if that makes sense.

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/481 adds this feature with the following controls:

![image](https://user-images.githubusercontent.com/12953439/100107518-bc57be00-2e8f-11eb-9214-39086c8fc80b.png)

![image](https://user-images.githubusercontent.com/12953439/100107811-13f62980-2e90-11eb-9b38-d0e4bc9ffe22.png)
