### ISSUE TITLE
The plugin's page on WordPress.org

### ISSUE THREAD

**Issue by carlosinho** [Codeinwp/feedzy-rss-feeds#442]
@contactashish13 our page on https://wordpress.org/plugins/feedzy-rss-feeds/ could benefit from additional links to:

https://themeisle.com/blog/wordpress-news-aggregator-website/
https://themeisle.com/blog/create-an-autoblogging-site-wordpress/

It would be cool if you can add them.

Ionut told me to best contact you here.

**Comment by contactashish13** [comment]
@DanyCaissy can you update the readme for this along with https://github.com/Codeinwp/feedzy-rss-feeds/issues/435?

**Comment by DanyCaissy** [comment]
@carlosinho As the page is mostly focused on describing the product I'm not sure exactly where I could find in these articles. There is already quite a lot of content on it and many links. Do you have a suggestion?

**Comment by carlosinho** [comment]
@DanyCaissy sure, you can just add links on these phrases: https://prnt.sc/su8x4d

the first underline can be linked to https://themeisle.com/blog/wordpress-news-aggregator-website/

and the second one to https://themeisle.com/blog/create-an-autoblogging-site-wordpress/

**Comment by DanyCaissy** [comment]
@carlosinho Ok, this has been done here: https://github.com/Codeinwp/feedzy-rss-feeds/pull/437/commits/c20daa5a0154c3ed1102add78b05f3c843d30e1c

**Comment by carlosinho** [comment]
@DanyCaissy I don't see any links added here https://prnt.sc/sxuy3n

**Comment by DanyCaissy** [comment]
@carlosinho It won't be live until Rodica merges the pull request.

**Comment by carlosinho** [comment]
okay, thanks!

**Comment by contactashish13** [comment]
@DanyCaissy you don't have to wait for PRs to be merged. These things can be changed directly in the master branch and they will get updated on wp.org without a new release/version. FYI for the future

**Comment by rodica-andronache** [comment]
it should be live
