### ISSUE TITLE
Feed2Post: Ability to clear data of already imported items to reimport those again

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#452]
### Description:
Currently, when a new import job is created and run - items (posts) are imported and cached in the database so the same items cannot be imported again to prevent duplicates. 

Even if you delete imported posts from WordPress and run import job - nothing will get imported and that's expected, however, especially when you are working to build a new import job that imports everything, as you want it to be, this becomes very time-consuming as you need to re-create the import job every time.

Can we have a button that clears cached data of that import job so items can be imported again using the same import job without creating a new one?

### Alternatives:
Recreating the import job or deleting metadata from the database (not user friendly).

HS Ticket: https://secure.helpscout.net/conversation/1219424111/235888/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/455 wipes everything about this import (list of imported items used for duplicate check, last run time and last run status) when you click the purge & reset option. 

![image](https://user-images.githubusercontent.com/12953439/87908237-b38b5180-ca83-11ea-948b-7e978a4ad75c.png)

@vytisbulkevicius let me know if you feel it should wipe out the posts created as well, although I'm not sure that is a good idea.

**Comment by vytisbulkevicius** [comment]
Looks great! I agree that this shouldn't delete posts created by the import job.

If there is such a demand by the clients in the future maybe it could be an additional option to delete all the posts created by a specific import job. It actually sounds pretty useful but only as a separate option and not sure how much effort it would require on your end develop.
