### ISSUE TITLE
Check validity of feeds specified

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#453]
#### category
When users add many URLs in a feed category, they tend to blindly add URLs without verifying whether they are valid or not. I see many instances where website URLs are present. We should try to validate each feed to make sure it is at least in XML format before allowing the users to save them in the category.

#### feed2post
When a feed (not a category, because we will assume URLs in a category are all valid) is added, we do not verify. The user finds out the feed is not valid only when the import runs. We should try to validate this beforehand, when it is saved maybe as an error on the listing page and do not allow the user to enable this import till the URL is not fixed. 

Note: It is likely that a feed becomes corrupt during an import. That will **not** disable the import.

#### shortcode
We should try to validate this as well. Maybe show an error in the post editor screen?

**Comment by contactashish13** [comment]
@DanyCaissy @rodica-andronache @vytisbulkevicius can you please review this and see if this can be improved in any way before we conclude on how to implement?

**Comment by vytisbulkevicius** [comment]
@contactashish13,

Agree that this is needed. For **feed2post** I think it can be either validated on the creation of category/saving the import job **or** when they press Run Now depending on which is easier. 

If it's also possible to print the actual URL of the feed which is invalid it would be great as I faced a few cases where the client used 10+ feeds so it takes time to find the invalid feed (in those cases the feed was XML format and looked valid it just was one of those that Feedzy failed to parse).

_If there is no difference (regarding the amount of work) I agree that it's better to validate feeds on saving the import job not on run now._

**Comment by contactashish13** [comment]
PR addresses this in the following manner:

#### category
If I provide invalid feeds as below

![image](https://user-images.githubusercontent.com/12953439/88757142-056a6080-d183-11ea-8044-9ad49127936e.png)

it removes the invalid URLs and shows a notice. 

![image](https://user-images.githubusercontent.com/12953439/88757224-2b900080-d183-11ea-9086-500d36360913.png)

#### feed2post edit
![image](https://user-images.githubusercontent.com/12953439/88757371-73af2300-d183-11ea-8b18-6f1ae8761984.png)

When you click save or save and activate, it will not activate it. It will take you back to the edit screen (instead of the listing screen) and show a notice.

![image](https://user-images.githubusercontent.com/12953439/88757388-7d388b00-d183-11ea-80bf-06d1964d9c43.png)

#### feed2post toggle status on listing screen

Let's say the user quits that screen and goes to the listing screen to activate the import. It will deactivate it and show this notice. 

![image](https://user-images.githubusercontent.com/12953439/88757589-0fd92a00-d184-11ea-813e-0cd810cdf6b4.png)

#### shortcode

I decided not to implement this restriction here as this will automatically be seen by the user when they view the page with the shortcode in it. 


This PR does not affect existing/configured imports/categories unless they are edited or their status is changed.

**Comment by vytisbulkevicius** [comment]
Thanks, @contactashish13 - could you elaborate a little how the check works? In provided screenshots, those are not links and if a link is added that is not a valid XML feed - will it be removed also and error is thrown? 

Also, if it's valid XML feed but SimplePie for some reason is not able to parse it - is there also an error thrown during this validation? Just to understand what's exactly being validated on this step to know ourselves and explain to users.

**Comment by contactashish13** [comment]
@vytisbulkevicius an invalid feed can be a link or cannot be a link. It does not matter to the plugin as both would be considered unparseable. The validation is not shallow - it as being sent through simplepie just like any other feed is and any error there results in the feed being removed.

**Comment by rodica-andronache** [comment]
@contactashish13 for Categories, the notices doesn't appear when you first publish it, but only after you update the category, which I don't think is correct
https://www.loom.com/share/7372d02dafda4cb78c8a07534d4e0154

**Comment by contactashish13** [comment]
@rodica-andronache fixed this.

**Comment by rodica-andronache** [comment]
@contactashish13 there are some cases where the check is not working well for Categories.
For example, if you just enter a valid feed like `https://www.codeinwp.com/feed/` I get the error when first publishing the category, which shouldn't happen. When updating the category, the errors dissappears.

https://www.loom.com/share/c26d44ae275d4e7aa26a282982aa553e

**Comment by contactashish13** [comment]
@rodica-andronache this doesn't happen for me. Can you make sure you have taken the updated code as this was happening in one of the interim checkins, not the final commit?

**Comment by rodica-andronache** [comment]
@contactashish13 I got the latest update, and tested on both wp 5.4 and 5.5 and is still happening for me.

You can check it out here:
https://blind-right.jurassic.ninja/wp-admin/
user: demo
pass: oHy5kYWPflVs2R43(bN77BMl

**Comment by contactashish13** [comment]
@rodica-andronache fixed this. Interestingly, this was happening when the category got saved as an auto-draft

**Comment by irinelenache** [comment]
@contactashish13 Tested it and it works fine . The only problem (don't know if it's really a problem) is when i add a valid feed without `https://` before.
feed with https:// -> https://prnt.sc/ubiier
feed without https:// -> https://prnt.sc/ubiiqa

**Comment by contactashish13** [comment]
@irinelenache I've addressed this. It will automatically append the scheme (`http`) to such URLs

**Comment by irinelenache** [comment]
@contactashish13 Tested it now and it works fine!

**Comment by contactashish13** [comment]
The latest commit adds this button that allows users to clean their categories to weed out incorrect URLs:

![image](https://user-images.githubusercontent.com/12953439/93072325-dbbbb900-f69e-11ea-8891-80556bd40625.png)

**Comment by irinelenache** [comment]
@contactashish13 it works fine with correct feeds, incorrect feeds, incomplete feeds (without http://)!
