### ISSUE TITLE
HTML tags are trimmed on save of the import job

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#464]
### Description:
With the latest version of the plugin - 3.4.1 it's not possible to add HTML tags anymore and they are being trimmed on save of the import job. Works fine with version 3.4.0.

Tried to add HTML tags to the content field: 
![image](https://user-images.githubusercontent.com/36594177/89987504-d83fa700-dc86-11ea-8cac-640f2e1c4963.png)

When the import job is saved and I go back to edit the same import job all HTML tags are trimmed:
![image](https://user-images.githubusercontent.com/36594177/89987581-f73e3900-dc86-11ea-86c2-da326fb1e802.png)

### How to reproduce:
1. Create a new import job
2. Add HTML tags to the content and save the import job
3. Try to edit the same import job - HTML tags were trimmed on save

### Expected behaviour:

HTML tags might be useful add some custom content or move another tag to the next line so I expect those to work.

### Current behaviour:

HTML tags are being trimmed on save of the import job.

### Reference:
Provided in the description.

### Technical info
* WordPress version: 5.4.2
* Plugin version: 3.4.1

**Comment by vytisbulkevicius** [comment]
https://secure.helpscout.net/conversation/1238345305/238386/

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/465 fixes this.
