### ISSUE TITLE
Improve UI of the import listing page

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#467]

**Comment by contactashish13** [comment]
PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/469 adds a separate table for showing the last run details.

This is how it behaves:

![feedzy](https://user-images.githubusercontent.com/12953439/91408589-b8e97200-e861-11ea-9cb4-a8fb5d82b85c.gif)

and looks like on the mobile interface:

![image](https://user-images.githubusercontent.com/12953439/91408729-f0f0b500-e861-11ea-88f6-d1a275f7e24b.png)

**Comment by rodica-andronache** [comment]
@contactashish13 on smaller resolutions, the found/duplicates/imported, etc badges are not properly visible. Even in your mobile screenshot, the `duplicates` and `cumulative` words are not ok.
![z](https://user-images.githubusercontent.com/3266155/91444985-286d5a80-e87e-11ea-84e0-517b2ffbcc72.png)
![zz](https://user-images.githubusercontent.com/3266155/91445015-33c08600-e87e-11ea-9b07-3d3e68dad5d0.png)

apart from that, I don't understand how the duplicates and cumulative counts work.
if I click Purge & Reset I can import the same posts twice, but that number doesn't appear in the stats.
![zzz](https://user-images.githubusercontent.com/3266155/91445236-89952e00-e87e-11ea-82c6-ea7d658af89a.png)

**Comment by contactashish13** [comment]
@rodica-andronache I've fixed the font size in the mobile interface.

Your confusion about cumulative counts and purge and reset feature has been addressed previously in another issue. I thought it was cleared there :) Anyways, purge and reset only resets the counters of feedzy - it does not delete the posts. That was the behavior of purge and reset when it was introduced. Let me know if you expect some other behavior.

**Comment by irinelenache** [comment]
@contactashish13 
The functionality works fine, but on mobile, text overlaps on narrow screens
https://prnt.sc/ubkfir

**Comment by contactashish13** [comment]
@irinelenache we can't do much for this on some smaller screens because the words are too big. It looks fine on iphone 6/7/8 plus

![image](https://user-images.githubusercontent.com/12953439/92348524-fdda9780-f0f0-11ea-851e-2cfdcde9d51b.png)
