### ISSUE TITLE
Impoper vertical display of categories on 'Shop' page for Neve Pro/ 'Shop' starter site 

### ISSUE THREAD

**Issue by StellaTI** [Codeinwp/feedzy-rss-feeds#470]
### Description:

There is an impoper vertical display of categories on 'Shop' page for Neve / 'Shop' starter site 

### How to reproduce:

1. clean install of Neve Pro/ Shop starter site
2. go to Shop page

### Expected behaviour:
we expect an easy readable content on the page

### Current behaviour:
we see [mpoper vertical display of categories on 'Shop' page for Neve Pro/ 'Shop' starter site 

### Reference:

![home_shop page](https://user-images.githubusercontent.com/69237124/91487632-afd6c000-e8b6-11ea-902e-4640037d98e1.jpg)

### Technical info
* WordPress version: 5.5
* Plugin version: 2.7.7

**Comment by rodica-andronache** [comment]
@StellaTI this isn't related to Feedzy, I think you're supposed to add this to Neve
