### ISSUE TITLE
With debug mode enabled Feedzy throws PHP Notices about Undefined index in one of the files.

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#474]
### Description:

With debug mode enabled:
```
define( 'WP_DEBUG', true );
define( 'WP_DEBUG_LOG', true );
```

Feedzy throws PHP Notices about Undefined index in one of the files.
PHP notices are written to the debug.log WordPress file that lives in /wp-content/ directory.

I have installed Feedzy to a fresh WordPress instance and after creating an import job and running it - debug file was populated with notices:

```
[24-Sep-2020 12:02:01 UTC] PHP Notice:  Undefined index: feedzy_category_meta_noncename in /srv/users/userdda638ba/apps/userdda638ba/public/wp-content/plugins/feedzy-rss-feeds/includes/admin/feedzy-rss-feeds-import.php on line 343
[24-Sep-2020 12:02:01 UTC] PHP Notice:  Undefined index: feedzy_category_meta_noncename in /srv/users/userdda638ba/apps/userdda638ba/public/wp-content/plugins/feedzy-rss-feeds/includes/admin/feedzy-rss-feeds-admin.php on line 271
```

### How to reproduce:
1. Enable debug mode as provided in the description.
2. Create a new import job with Feedzy and Run the import.
3. Go to /wp-content/ directory and check debug.log file

### Expected behaviour:

PHP Notices about the undefined index shouldn't be thrown.

### Current behaviour:

PHP Notices about the undefined index are being thrown.

### Reference:
![image](https://user-images.githubusercontent.com/36594177/94143003-d701bc80-fe77-11ea-9052-92e94051bbef.png)

Can be checked here:
https://specified-hippopotamus.jurassic.ninja/wp-admin
User: demo
Password: 2UNXvBR9EVRO

### Technical info
* WordPress version: 5.5.1
* Plugin version: 3.4.3

**Comment by vytisbulkevicius** [comment]
Reported here: https://wordpress.org/support/topic/php-notice-undefined-index-feedzy_category_meta_noncename/

**Comment by contactashish13** [comment]
This will be addressed in https://github.com/Codeinwp/feedzy-rss-feeds/pull/456/. @rodica-andronache any plans of releasing these PRs that are getting stale?

**Comment by rodica-andronache** [comment]
@contactashish13 https://github.com/Codeinwp/feedzy-rss-feeds/pull/456 was merged on development. I tried with that version, and still got the PHP notices mentioned in the issue

**Comment by contactashish13** [comment]
@rodica-andronache I don't get this with the development branch. I've tried with an import with a feed url and also with a category. Both work for me without any notice.

**Comment by rodica-andronache** [comment]
@irinelenache can you please check too with the latest version of Feedzy?

**Comment by irinelenache** [comment]
@rodica-andronache i get the same notices in the log
[debug.log](https://github.com/Codeinwp/feedzy-rss-feeds/files/5377628/debug.log)

**Comment by girishkrishaweb** [comment]
PR - https://github.com/Codeinwp/feedzy-rss-feeds/pull/495

**Comment by topher1kenobe** [comment]
I'm getting this when I save a menu, but NOT when I run an import.

` Warning: Undefined array key "feedzy_category_meta_noncename" in /home/customer/www/topher.how/public_html/wp-content/plugins/feedzy-rss-feeds/includes/admin/feedzy-rss-feeds-admin.php on line 300`

<img width="1680" alt="Screen Shot 2021-03-15 at 2 22 47 PM" src="https://user-images.githubusercontent.com/341412/111202900-cca8bb80-859a-11eb-9c7c-765a947b1103.png">

**Comment by tudor-themeisle** [comment]
I got the same error ( https://prnt.sc/10od22t ), ( https://prnt.sc/10od2z0 ).

This is happening when I saved the menu after I added a page to it, and it does the same when I deleted the page and saved it.

**Comment by girishkrishaweb** [comment]
@tudor-themeisle & @topher1kenobe  Can you please confirm here that you were testing the issue after applying the latest patch? As I can see in the screenshot, you are getting the issue on this line `Warning: Undefined array key "feedzy_category_meta_noncename" in /home/customer/www/topher.how/public_html/wp-content/plugins/feedzy-rss-feeds/includes/admin/feedzy-rss-feeds-admin.php on line 300` but after the applying patch, the array key does not exist on this line number.

**Comment by irinelenache** [comment]
@girishkrishaweb with the patch applied, no errors are shown neither with Neve or Kadence installed

**Comment by tudor-themeisle** [comment]
Sorry @girishkrishaweb, I think I didn't use the current patch, I tested again and got the same result as @irinelenache.
