### ISSUE TITLE
Cannot save <iframe></iframe> tag in the content field - gets trimmed on Save

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#475]
### Description:

Previously it was possible to add <iframe></iframe> tag into the content field and it was useful to import embed videos by passing custom field to **_src_** attribute. Now it's not possible to save import with <iframe></iframe> because it gets trimmed when saving the import.

### How to reproduce:
1. Create a new import and add <iframe></iframe> to the content field:
![image](https://user-images.githubusercontent.com/36594177/94153197-269ab500-fe85-11ea-8145-13edeca373fa.png)

2. Save the import.
3. Open the import again and check the Content field - <iframe></iframe> is no longer there:
![image](https://user-images.githubusercontent.com/36594177/94153361-5b0e7100-fe85-11ea-8709-97e2dd1f90ce.png)

### Expected behaviour:

I expect to be able to save <iframe></iframe> if the user wants to have it and add intentionally. 

### Current behaviour:

<iframe></iframe> tags are getting trimmed.

### Reference:

Video: https://www.loom.com/share/bb2e2feb38904a48a1acf48dfcd4780f

### Technical info
* WordPress version: 5.5.1
* Plugin version: 3.4.3

**Comment by contactashish13** [comment]
@vytisbulkevicius the user may intentionally want to save `<script>` tags as well. Should we be allowing that as well? Should we basically allow **anything** without sanitization and allow the user to compromise his system? I don't think that's wise. 

Instead, my suggestion is to use this filter https://gist.github.com/bjorn2404/8afe35383a29d2dd1135ae0a39dc018c for such users (you can try it at your end).

**Comment by girishkrishaweb** [comment]
PR - https://github.com/Codeinwp/feedzy-rss-feeds/pull/497
