### ISSUE TITLE
Add ability to use external images instead of uploading featured image to media library

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#492]
### Description:
From time to time there are requests to have an option and use external images as featured images because storing every image in the media library increases disk space and also creates duplicates.

We got a suggestion to integrate functionality with another plugin in this thread:
https://wordpress.org/support/topic/integration-with-fifu-plugin/

> Today a Feedzy user asked me to integrate that with FIFU because he doesn’t want the images in the media library. Fortunately that’s pretty easy thing using this integration function
> fifu_dev_set_image($post_id, $image_url)
> 
> So editing the file feedzy-rss-feeds/includes/admin/feedzy-rss-feeds-import.php and adding this code it would be enough to set the external image as the featured image of a post.
> 
> 1305	if (!empty($item['item_img_path'])) {
> 1306	    if (is_plugin_active('featured-image-from-url/featured-image-from-url.php') || is_plugin_active('fifu-premium/fifu-premium.php')) {
> 1307            fifu_dev_set_image($new_post_id, $item['item_img_path']);
> 1308	    }
> 1309	}
> Of course that’s just a quick integration. I don’t know all details about Feedzy, so only you are able to create the perfect code for that. I’m just saying that the integration is possible and it could be a good opportunity to get more users. Please let me know if it’s something that could be done or if you have any questions.
> 

### Alternatives:
We don't have a known alternative.

**Comment by girishkrishaweb** [comment]
PR - https://github.com/Codeinwp/feedzy-rss-feeds/pull/498
