### ISSUE TITLE
Non-Latin categories are split into lines when searching for a Post Taxonomy

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#493]
### Description:
When categories with non-latin characters exist in WordPress and you try to search for those in Feedzy Import settings - only the first letter of that taxonomy appears in the search results.

Example keywords that are tested:
她今天看起来很悲伤 (Chinese)
![image](https://user-images.githubusercontent.com/36594177/108771046-bee7b380-7563-11eb-8c5e-068594977494.png)

Новини (Russian)
![image](https://user-images.githubusercontent.com/36594177/108771029-b7280f00-7563-11eb-824d-180e55528804.png)

They show up fine in the list without search:
![image](https://user-images.githubusercontent.com/36594177/108771068-c73fee80-7563-11eb-9c32-b40cc6b05582.png)

### How to reproduce:
1. Create a category for WordPress post and use non-latin characters for the name.
2. Try to create a new import and search for that category in the list of taxonomies
3. Only the first character appears in the search results instead of the full name

### Expected behaviour:

The full category should appear in the results.

### Current behaviour:

Only the first character appears in the search results instead of the full name

### Reference:
Screenshots provided

### Technical info
* WordPress version: 5.6.2
* Plugin version: 3.5.2

**Comment by vytisbulkevicius** [comment]
Reported here: https://wordpress.org/support/topic/non-latin-terms-are-mutilated-in-live-search/

**Comment by girishkrishaweb** [comment]
PR - https://github.com/Codeinwp/feedzy-rss-feeds/pull/494
