### ISSUE TITLE
Themeisle page text

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#5]
seo-friendly titles/description

We need to talk to @mariusghitulescu for this

**Comment by rodica-andronache** [comment]
@abaicus you should talk with Adelina and MariusG for this

**Comment by abaicus** [comment]
De la **Adelina**:

> Feedzy RSS Feeds
> 
> A fast and easy way to add lots of RSS feeds to your WordPress site
> 
> Transfer all your favorite RSS feeds to your site in seconds
> The best collector of RSS feeds. It copies them to your site through shortcodes and widgets
> 
> Features
> 
> Multiple Shortcodes & Widgets
> You can copy a RSS feed quickly through shortcodes and widgets. The plugin will automatically generate codes for each feed you want to add. You can use the same shortcode for other pages and widgets as well.
> 
> Feeds Caching
> If you add too many feeds to your site, the plugin automatically adds caching to not affect the website's speed. The feeds' caching will reduce the page loading times.
> 
> SimplePie Class PHP included
> After you install the plugin, it automatically adds a button to your WordPress editor. You just need to click on it, fill out a few fields with your preferences, and the shortcode is inserted into your post/page.
> 
> Display images in feeds
> You can also choose to display images in feeds if they are available. If not, the plugin will give you a default image parameter.
