### ISSUE TITLE
Undefined array key  php error on line 300

### ISSUE THREAD

**Issue by tudor-themeisle** [Codeinwp/feedzy-rss-feeds#513]
### Description:

This is happening when I saved the menu after I added a page to it, and it does the same when I deleted the page and saved it.

### How to reproduce:

1. Fresh instance on Neve 2.10.2
2. Install Feedzy RSS Feeds Lite | Version 3.5.2 
3. Add a page to the menu and save it. 

### Expected behaviour:

It should not have the error.

### Current behaviour:

https://prnt.sc/10od22t

### Reference:

https://prnt.sc/10od22t, 
https://prnt.sc/10od2z0.

### Technical info
PHP version | 8.0.3 (Supports 64bit values)
WP 5.7
Feedzy RSS Feeds Lite | Version 3.5.2

**Comment by girishkrishaweb** [comment]
@tudor-themeisle Duplicate ticket https://github.com/Codeinwp/feedzy-rss-feeds/issues/474 - Solved
