### ISSUE TITLE
Allow leaving specific HTML tags unstripped

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#522]
### Description:
When importing items as posts XML RSS Feeds sometimes contain specific HTML tags that might be insecure like <iframe>, <script> etc.

SimplePie allows stripping them and we do so:
https://simplepie.org/wiki/reference/simplepie/strip_htmltags#don_t_strip_any_tags_not_recommended

However, sometimes users want to keep those tags and import them as content into a post. Example feed:
https://ayende.com/blog/rss/ravendb-net?token=mg9yE3AkYgTmvHtA%2Ft8CW9gBXr%2FWp%2FXWZNyYNK3PHoJNDqZQWVoZpl6vayRGqHj8XNvF9%2FMetZGtnnCYEPp6AB30pRk5Q1oW1nz7UDhUZStQ1SdOMAnqRyO2qC2z4hYx

This feed contains `<blockquote> <script src=""></script></<blockquote>` tags where src is a link to github to show some code snippets.
For example:
<blockquote><script src="https://gist.github.com/ayende/136f056d656df128b47130e494950a9e.js"></script></blockquote>

When Feedzy imports such an item - empty `<blockquote> </<blockquote>` gets imported.

Can we have an option in UI when the import job is configured to allow keeping HTML tags (either all or insert/select from the dropdown those that the user wants to keep) or have a filter that could be used to leave them unstripped?

### Alternatives:

Create a filter and add it to our documentation, however, I'm not able to find or create one that would work for imports.

The question was raised here - https://secure.helpscout.net/conversation/1479063920/274342

**Comment by selul** [comment]
we can turn this on/off based on a constant, i.e FEEDZY_ALLOW_UNSAFE_HTML

**Comment by girishkrishaweb** [comment]
We have defined a constant which will help to make it true on and off. By default, the setting will be trued off. you have to enable by using define constant with true value.

**How to test it - QA**

1. You need to open wp-config.php
2. Add the code `define( 'FEEDZY_ALLOW_UNSAFE_HTML', true );` into file.
