### ISSUE TITLE
Youtube feeds do not validate in the Import (F2P) settings

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#527]
### Description:
None of youtube feeds validate in the import settings so it's not possible to import items from youtube feeds.

Example feed - https://www.youtube.com/feeds/videos.xml?playlist_id=PLubHZPzx6RlpDOXh4F6pjrUrO5mvejHFw

When trying to save an import - error is thrown:
![image](https://user-images.githubusercontent.com/36594177/115715356-b7386580-a380-11eb-9542-43ef08f5ffe9.png)

Works fine when using Feedzy shortcode/widget:
![image](https://user-images.githubusercontent.com/36594177/115715461-d2a37080-a380-11eb-81d0-abb2865b9562.png)

Our guide for reference - https://docs.themeisle.com/article/1113-how-to-get-videos-from-youtube-with-feedzy

**It works fine with **version 3.5.1:****

![image](https://user-images.githubusercontent.com/36594177/115715913-49406e00-a381-11eb-8f5c-3fd1299ca4d4.png)

### How to reproduce:
1. Try to create a new import job
2. Add Youtube URL in the source
3. Try to save the import - error is thrown

### Expected behaviour:

It should be possible to import items as posts from YouTube feeds.

### Current behaviour:

Youtube feeds are marked as invalid.

### Reference:
Screenshots provided

### Technical info
* WordPress version: 5.7.1
* Plugin version:  3.6.1

Reported here - https://secure.helpscout.net/conversation/1490641666/275819/

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/1468539936/272948 (to inform client once fixed)

**Comment by vytisbulkevicius** [comment]
Seems like this happens not only with YouTube feeds.

Another client reported that his feeds stopped working and provided this one as an example:
https://multipolar-magazin.de/atom.xml

Again, I can replicate the same issue:
![image](https://user-images.githubusercontent.com/36594177/115774384-2da58980-a3ba-11eb-9c12-99432f38fe36.png)


**Works fine with Feedzy 3.5.1** 

Reported - https://secure.helpscout.net/conversation/1491187615/275878/

**Comment by selul** [comment]
fixed in the latest version.

**Comment by vytisbulkevicius** [comment]
Hi @girishkrishaweb,

Seems like it was fixed for feeds reported before, however, another example that is still failing is this feed:
https://www.globenewswire.com/rssfeed/organization/cs3rDGAwI9v7mcwG3KV1IA==

It's a valid feed, tested here - https://codebeautify.org/xmlvalidator
SimplePie also shows items - http://simplepie.org/demo/
