### ISSUE TITLE
custom fields input box don't appear in the import wizard

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/feedzy-rss-feeds#529]
### Description:

In the import wizard, when we click the **Add custom fields button**, no input fields appear there. 

### How to reproduce:

1. Create an import job
2. Click Add custom fields button

### Expected behavior:
I expected the empty custom fields input boxes to appear when I click the "add custom fields" button.

### Current behaviour:
No input fields, only the bin icon appears

### Reference:

![Markup 2021-04-22 at 23 02 17](https://user-images.githubusercontent.com/27731529/115761772-56c91880-a3c0-11eb-8788-ede78341c665.png)

### Technical info
* WordPress version: 5.7.1
* Plugin version: 3.6.1 (lite) and 1.7.1(pro)

HS Tickets: https://secure.helpscout.net/conversation/1491053732/275861?folderId=212385
https://secure.helpscout.net/conversation/1491788431/275966

**Comment by selul** [comment]
fixed in the latest version
