### ISSUE TITLE
Source doesn't show in feed

### ISSUE THREAD

**Issue by uniphonic** [Codeinwp/feedzy-rss-feeds#543]
### Description:
Source doesn't show in feed

### How to reproduce:
1. Enter multiple feeds
2. Enable showing sources, by putting "source" into the Item Options field labeled "When using multiple sources, should we display additional meta fields? - source (comma-separated list)."
3. The source doesn't show?

### Expected behavior:
The source of the RSS feed should show.

### Current behavior:
It doesn't show any source.

### Reference:
Here is one of the feeds where the issue can be seen:
https://accelermedia.com/sites/

### Technical info
* WordPress version: 5.7.1
* Plugin version: 3.6.4

**Comment by girishkrishaweb** [comment]
@uniphonic Thank you for the reporting. We have tried to reproduce the source issue but we haven't got anything with **source**.

Can you please follow the below steps for more clarification?
**Test step**

1. Create feed importer posts or feed categories with multiple URLs.
2. After that add Gutenberg block in page/post where you want to show the feed.
3. Now, edit Gutenberg block setting and expand item options from the panel
4. Go to "When using multiple sources, should we display additional meta fields? - source (comma-separated list)." setting and add **source** as an input
5. Click on Save / Update to save the post/page.

![Gutenberg-block-source](https://user-images.githubusercontent.com/79647963/117797427-a1c2a700-b26d-11eb-97e6-4d64d4f46bd8.png)
