### ISSUE TITLE
Import as Attachment works but ignores standard item_description

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/feedzy-rss-feeds#548]
### Description:
Importing from a valid RSS feed as post type set as ‘Attachment’ is ignoring the [#item_description] field.

It correctly imports the [#item_description] field (and also item_title and item_date ) if the Post Type is set to ‘Post’, but not when I set it to ‘Attachment’. Only the Item_Title and the actual image imports. However, it creates a second entry in the media library with the correct title, date and published date but without the image! Seems to be creating 2 separate records.

### How to reproduce:

1. Click New Import in the Feedzy Plugin
2. Setup everything as in the "Settings" screenshot below
3. Click Save
4. Click Run Now
5. Check Media Library. 2 Files have appeared

### Expected behaviour:
 Import images with a description (or caption) into WordPress Media Library, using a valid RSS2.0 

### Current behaviour:

Imports 2 files into Wordpress Media Library. An image with title but no description or feeded published date and a file with all the correct feed info but no Image.

### Reference:
1. [RSS FEED USED](https://prestatyn-scala.info/content/rss/4-gallery.xml/)
2. [Settings](https://www.dropbox.com/s/ghpo4ygmr9mzzxq/Screenshot%202021-05-27%20005718.jpg?dl=0)
2. [Succesful Import Message](https://www.dropbox.com/s/vuwl1yjsptqjnxc/Screenshot%202021-05-27%20010212.jpg?dl=0)
3. [Media Library – Image imported but description ignored](https://www.dropbox.com/s/qtlsfxcf1vlj9bt/Screenshot%202021-05-27%20010858.jpg?dl=0)
4. [Imported Image in the Media Library](https://www.dropbox.com/s/t4pye3xkedvhcg0/Screenshot%202021-05-27%20011100.jpg?dl=0)
5. [Media with correct data but missing image](https://ibb.co/QJQN0QM)

### Technical info
* WordPress version: 5.7.2
* Plugin version: RSS Feeds Lite v3.7.0

**Comment by girishkrishaweb** [comment]
@vytisbulkevicius The RSS feed URL is not working. Can I have a new feed URL?

**Comment by vytisbulkevicius** [comment]
@girishkrishaweb,

Sure, this should be replicable with any feed that has images, so this is one that could be used to test - http://colmcille.net/colmcille-1500-events/feed
