### ISSUE TITLE
When posts are imported with "external image" - they do not show up in Posts blocks (Gutenberg, Elementor and similar)

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#549]
### Description:
Feedzy has a feature to import posts without downloading images and use the external image URL:
![image](https://user-images.githubusercontent.com/36594177/121032910-65269480-c7b4-11eb-83e3-6fd292c1fa8c.png)

When this option is used image shows fine on single post page:
https://vertis.d.pr/LtQxAY
or category/archive pages:
https://vertis.d.pr/DR50lF

But if you're using Gutenberg Latest Posts block or Elementor Pro Posts block - images are not shown next to the items.
This is how it shows up:
![image](https://user-images.githubusercontent.com/36594177/121032428-ef222d80-c7b3-11eb-90f4-776364be5bc1.png)

This is how it shows up when images are imported as featured images:
![image](https://user-images.githubusercontent.com/36594177/121032533-052fee00-c7b4-11eb-829c-d7fd6bc8b7c5.png)

Can we make some change in terms of setting external URL so these plugins can the "external" image when "featured" image is not set for the post?

### Alternatives:
I'm not aware of an alternative so if a user wants to import items to his instance and also show them somewhere using a block/widget - images should be downloaded and stored as featured images.

Reported here - https://secure.helpscout.net/conversation/1527486382/280454/

**Comment by girishkrishaweb** [comment]
@vytisbulkevicius We have verified all the possibilities to show the external images as featured images in the admin visual editor( Gutenberg, Elementor, and similar ) but there is no to do this in the admin interface.

**Comment by irinelenache** [comment]
@vytisbulkevicius I see that Gutenberg **Latest posts block** has a setting for displaying the featured image (https://vertis.d.pr/5Nw1tH) that seems to work only in front-end (https://vertis.d.pr/fAjaET) and the **Image dimensions can't be changed**.

**Comment by girishkrishaweb** [comment]
@irinelenache I have added front-end image dimension support and I'm working on working on add external images support in the visual editor(Gutenberg, Elementor, and similar).

**Comment by girishkrishaweb** [comment]
@irinelenache I have verified all the possibilities for printing external media into the visual editor and found there is no way to render the external images within the visual editor.

The reason behind it that the recent default block get posts using REST {site_url}/wp-json/wp/v2/posts API and this API returns post data with attachment ID as a featured_media parameter after that it runs a second API [{site_url}/wp-json/wp/v2/media/11227] to get attachment data and render it into visula editor using JavaScript
