### ISSUE TITLE
Issue with Freemius

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#55]
I installed the plugin, skipped the tracking option and the plugin appears in the footer of my Plugins.php in Dashboard: https://nimbus.everhelper.me/client/notes/share/954539/znh3reocuxfxd2509qte

It was half hidden inside admin menu but adding margin to show for this issue.

**Comment by ineagu** [comment]
I think is our sdk @selul

**Comment by selul** [comment]
@HardeepAsrani it's not from feedzy it's from adblock, and yes, you see that because you have adblock enabled.
