### ISSUE TITLE
Feedzy is not compatible with PHP 8 when some specific feeds are used in Elementor/Gutenberg blocks

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#556]
### Description:
With PHP 8 when using Elementor or Gutenberg Blocks fatal error is thrown when some specific feeds are added to the Feedzy category.

The issue can be replicated using these feeds, for example:
http://bado-badosblog.blogspot.com/feeds/posts/default, http://dailycartoonist.com/index.php/feed/

If you create a category using these feeds:
![image](https://user-images.githubusercontent.com/36594177/124467428-858c4380-dda0-11eb-8223-f8f105bfada5.png)

And then you add that category inside Elementor's block or via Gutenberg block:
![image](https://user-images.githubusercontent.com/36594177/124467675-d865fb00-dda0-11eb-9e35-c1c1e76aa262.png)
doesn't matter if it's added as a category or just comma-separated feeds:
![image](https://user-images.githubusercontent.com/36594177/124467751-f0d61580-dda0-11eb-87b7-7db39c2c3fb3.png)

In the front-end or Elementor Editor you get a fatal error:
![image](https://user-images.githubusercontent.com/36594177/124467842-119e6b00-dda1-11eb-943d-80a8bf6063cb.png)

With PHP 7.4 the fatal error doesn't appear and items are shown using the same feeds - https://vertis.d.pr/QlwwFw

### How to reproduce:
1. Create a WordPress instance using PHP 8 version.
2. Use mentioned feeds (as an example) to populate items using Elementor's or Gutenberg blocks.
3. You should get a fatal error (doesn't happen with PHP 7.4 version).

### Expected behaviour:
No fatal error.

### Current behaviour:
Fatal error occurs.

### Reference:
Screenshots attached.

Reported here - https://secure.helpscout.net/conversation/1560371248/284265
Issue also reported here: https://secure.helpscout.net/conversation/1564559949/284821?folderId=212385

### Technical info
* WordPress version: 5.7.2
* Plugin version: 3.7.0
* PHP version: 8.0.7 (Supports 64bit values)

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/1564559949/284821?folderId=2749618
