### ISSUE TITLE
Sort feed by title/etc

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#57]
A feature to sort feeds by their titles/author or anything. Suggested by a user. @selul

**Comment by selul** [comment]
This looks like a good idea.  however we need to see more traction in order to spend time on this.

**Comment by HardeepAsrani** [comment]
@selul I can take care of this one, if you want. :)

**Comment by HardeepAsrani** [comment]
We can have these options:

- Sort By: Title, Date or Author
- Sort Order: Ascending, Descending

I've a PR ready for it, if you want me to send. (Of the function, need to add it to the shortcode/UI itself.)

Thoughts?

**Comment by selul** [comment]
@HardeepAsrani  we have a doc published for this scenario. I dont see many requests regarding this feature and i dont want to complicate the builder too much.
