### ISSUE TITLE
Automatic import not working in 3.7.3 & 3.7.4

### ISSUE THREAD

**Issue by umm-wdc** [Codeinwp/feedzy-rss-feeds#594]
### How to reproduce:

1.
2.
3.

### Technical info
* WordPress version: x.x.x
* Plugin version: x.x.x

**Comment by girishkrishaweb** [comment]
@selul I can not reproduce this issue in 3.7.4. Because we have fixed this in 3.7.4

**Comment by selul** [comment]
@umm-wdc thanks for sharing this out. Can you share more details about the environment?

**Comment by umm-wdc** [comment]
@girishpanchal30 , even in 3.7.4, the automatic import of posts from feed is not working , I have close to 30feeds out of which only 10 or 15 is running the rest just doesn't run .

**Comment by umm-wdc** [comment]
@selul , running WP 5.8, elementor pro, hello theme, Feedzy Pro , hosted in WP engine Managed wordpress, any other specific detail you is needed ? please let me know thanks

**Comment by selul** [comment]
hi @umm-wdc, 

Can you get in touch with the support team on store.themeisle.com/contact to help you troubleshoot the issue. Ideally, we would need some access to replicate this on our end, or similar since on my end is working fine.

**Comment by umm-wdc** [comment]
@selul , raised multiple support request regarding this, but the support seems to take time to respond to this.  Also now when i tried to debug the issue by uninstalling and reinstalling all the imports disappeared. :(
