### ISSUE TITLE
Images are not importing with some feeds in versions 3.7.3 and 3.7.4

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#596]
### Description:
It could be related to issue https://github.com/Codeinwp/feedzy-rss-feeds/issues/591 but as behavior of widgets is mentioned there and this one is related to the posts import I'm adding it separately.

With version 3.7.3 and 3.7.4 images are not downloaded and attached as featured images from some feeds.
Example feed - https://valdarno24.it/?cat=sport&feed=rss2
Items have images and they show up in SimplePie also - http://simplepie.org/demo/?feed=https%3A%2F%2Fvaldarno24.it%2F%3Fcat%3Dsport%26feed%3Drss2

However, with versions 3.7.3 and 3.7.4 when import items images are not downloaded and not attached as featured images:
![image](https://user-images.githubusercontent.com/36594177/132166436-70c2e57e-ebfd-4688-b583-0b2fa182f15c.png)

In the Parrot plugin I see the logs and there are such errors when trying to download each image:
`Error feedzy-rss-feeds-import.php:1641 - Unable to download file = WP_Error Object ( [errors] => Array ( [http_404] => Array ( [0] => Not Found ) ) [error_data] => Array ( [http_404] => Array ( [code] => 404 [body] => <!doctype html > <!--[if IE 8]> <html class="ie8" lang="en"> <![endif]--> <!--[if IE 9]> <html class="ie9" lang="en"> <![endif]--> <!--[if gt IE 8]><!--> <html lang="it-IT"> <!--<![endif]--> <head> <title>Pagina non trovata - Valdarno 24</title> <meta charset="UTF-8" /> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <link rel="pingback" href="https://www.valdarno24.it/xmlrpc.php" /> <meta name='robots' content='noindex, follow' /> <!-- Google Tag Manager for WordPress by gtm4wp.com --> <script data-cfasync="false" data-pagespeed-no-defer type="text/javascript">//<![CDATA[ var gtm4wp_datalayer_name = "dataLayer"; var dataLayer = dataLayer || []; //]]> </script> <!-- End Google Tag Manager for WordPress by gtm4wp.com --><link rel="icon" type="image/png" href="https://www.valdarno24.it/wp-content/uploads/2020/02/favicon2020.png"><link rel="apple-touch-icon-precomposed" sizes="76x76" href="https://www.valdarno24.it/wp-content/uploads/2017/01/v24_76x76. ) ) [additional_data:protected] => Array ( ) ) and postID 813`
Screenshot: 
![image](https://user-images.githubusercontent.com/36594177/132166568-084e0bb7-f07c-45f0-97bd-e37d95455b57.png)

### How to reproduce:
1. Create a new import and use https://valdarno24.it/?cat=sport&feed=rss2 feed as the source
2. Add default magic tag [#item_image] to import images of the posts
3. Try to run the import, images should not get attached as featured images. If you rollback to 3.7.2 the images will get imported.

### Expected behaviour:
Featured images should get imported.

### Current behaviour:
Featured images are not imported.

### Reference:
Screenshots attached
Reported here - https://secure.helpscout.net/conversation/1620465701/290839
And Here: https://secure.helpscout.net/conversation/1620119839/290792?folderId=212385

### Technical info
* WordPress version: 5.8
* Plugin version: 3.7.4 and 3.7.3

**Comment by girishpanchal30** [comment]
The issue has already been fixed in the #591 `bugfix/591` branch. So we need to merge PR - #592 

Ref - https://www.awesomescreenshot.com/image/13002538?key=0a68bd170ecd54a32b7157475e81da31

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/1616763230/290373/ (to inform the user when a fix is released)

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Can I have access to HelpScout?

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

We're adding these comments/notes so the support team can inform the clients after a fix is released but in case you need access not for this reason but to get more information and details about the issue reported we can ask Marius.

@selul can we provide the shared HS user that developers user or create a dedicated for @girishpanchal30?
