### ISSUE TITLE
Images are not shown with using shortcode (behavior inconsistent)

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#617]
### Description:
This is a bug that happens not all the time but from time and based on my tests happens on a fresh instance.
I think the same behavior occurs when the feed is refreshed/has new items.

This is the shortcode used for testing:
`[feedzy-rss feeds="https://radio.securenetsystems.net/dx/get_podcasts_connect.cfm?stationCallSign=MRSPEAKER&pcId=254" max="4" offset="0" feed_title="no" refresh="12_hours" sort="date_desc" target="_self" lazy="no" summary="yes" summarylength="350" size="250" http="default" price="no" columns="1" template="default" ]
`
So I've added this shortcode to my test instance and on the website indeed I see the default Feedzy fallback image instead of images belonging to items:
https://vertis.d.pr/8h6YiS

Then, after some time the images appeared and they are visible:
https://vertis.d.pr/J0F3tJ (screenshot from the client website where it shows up for me now). 
Same happened in my test instance, after some time images starter appearing same as the summary.

It's really weird because when client reported the issue on his website I was seeing those default Feedzy images also but after some time checking the page and trying to replicate the issue on my website when I got back to his website images appeared.

It's the same as what the client is telling also:

> We have communicated about this same issue about a month ago and the problem still persists. When a podcast is uploaded and feed through the plugin the featured images disappear and is replaced by a blue RSS Feed icon. After refreshing the site or a little time passes the images will re-appear. 

Screencast - https://vertis.d.pr/v282VP

### How to reproduce:
1. Create a new instance and use the shortcode provided above to populate Feedzy content.
2. Check the page and you should see default content while Feed contains images.
3. After some time check the page again with multiple refreshes, there should be a time when you see images appearing.

### Expected behaviour:
Images, if available, should be displayed all the time without interruptions.

### Current behaviour:
Images sometimes are not shown/disappear.

### Reference:
Screenshots/screencasts provided above.

Reported here - https://secure.helpscout.net/conversation/1670442640/296692/

### Technical info
* WordPress version: 5.8.1
* Plugin version: 3.8.0

**Comment by girishpanchal30** [comment]
@vytisbulkevicius 

I have tried to reproduce the issue without and with a cron job but, I couldn't reproduce this in my local and test environment.

@irinelenache Could you try to reproduce it?

**Comment by irinelenache** [comment]
@girishpanchal30 I couldn't reproduce it on a jurassic instance, but i managed to do it on tastewp https://vertis.d.pr/aHdieQ

You can check it here:
```
 Admin area URL: https://unpackcow.tastewp.com/wp-admin 
 Username: irinel 
 Password: c1n25MTTujY 
```

For reproduction, i only created the default tastewp instance, installed feedzy and created a post with the mentioned shortcode

**Comment by girishpanchal30** [comment]
@irinelenache @vytisbulkevicius The feed URL is working on a test environment now, the issue was related to iTunes feed URL.
Ref - https://unpackcow.tastewp.com/?page_id=14
Ref - https://tinyurl.com/yeqe3lxs

**Comment by irinelenache** [comment]
@girishpanchal30  Thanks for checking 👍 Can something be done so the issue won't happen again?

**Comment by girishpanchal30** [comment]
@irinelenache This issue is related to the iTunes feed source where the images are missing sometimes, so we can't fix it without replicating the actual issue. I hope it does make sense for you as well.

**Comment by vytisbulkevicius** [comment]
Hm, to me it didn't look like that. I checked if the feed thas images and I saw images there but when I created a new widget images there not showing up, after some time and refreshing the page made them show up but the structure of the feed hasn't changed. 

@girishpanchal30,
I tried to create a new test instance now and images are not showing up - https://vertis.d.pr/uYQk3A
But they are available in the feed (as always when I checked) - https://vertis.d.pr/02E1ix

I'm sure that in several minutes after more refreshes they will also appear on the page so maybe when you check https://vital-copperhead.jurassic.ninja/2021/11/16/5/ they will already be there but this doesn't look to be related to the feed.

**Comment by vytisbulkevicius** [comment]
Items started appearing as I said after some time now: https://vertis.d.pr/GFIuPf (I haven't made any changes, nor the feed's structure changed). Just refreshed the same page after a few hours and it works now.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Due to the large image size, we can't show images within the block. I have checked this feed URL with the podcasts feed validator tool and it returns **Your image is too large** in the artwork test. https://castfeedvalidator.com/

Ref - https://tinyurl.com/yex6xces

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

But why does it show up then now after some time - https://vital-copperhead.jurassic.ninja/2021/11/16/5/ if images are too big?

And even you provided an example above where it worked for you so if it's not working all the time that would make sense and explain it, however, why it works after some time and then stops working again (according to the client after some time which I assume happens when there are new items in the feed and we refresh it again).

**Comment by girishpanchal30** [comment]
@vytisbulkevicius We are on it and will update you soon

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Can you please provide another iTunes feed source URL? So I can compare it with the existing iTunes feed URL.

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

I found this one - https://bbemusicpodcasts.podomatic.com/rss2.xml
also this one - view-source:https://chrisc416podcast.podomatic.com/rss2.xml

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I have checked the feed URL and found that the `xmlns:itunes` namespace URL with HTTPS but it should be HTTP only see the URL  `iTunes RSS feed`.
`<rss version="2.0" xmlns:itunes="https://www.itunes.com/dtds/podcast-1.0.dtd">` it should be `<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">`

Ref - https://tinyurl.com/yemfxytp

I have tested in my local after applying the change and it is working fine!

Note: We can't modify any namespace URL by ourself because all namespace defines in PHP constants so we can't override it.

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Great finding, I will let the client know and maybe he's able to contact the authors to make the change.
It's still weird to me why those images appear after some time if the problem is with the feed but let's see how it goes, we haven't received other complaints about this yet.

Let's keep this issue open for a little longer in case something new pops up, thank you!
