### ISSUE TITLE
Custom refresh rate for modern Feedzy widget

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#625]
### Description:
We already had a custom code for this feature, however, it stopped working.
Here is the documentation:
https://docs.themeisle.com/article/1159-changing-the-caching-time-interval-in-feedzy-widget

The code that was working before:
```
add_filter('feedzy_get_form_elements_filter', function($elements) {
   $screen = get_current_screen();
   if ( ! empty( $screen ) && in_array( $screen->id, array( 'widgets', 'customize' ), true ) ) {
      $elements['section_feed']['elements']['refresh']['opts'] = array_merge( $elements['section_feed']['elements']['refresh']['opts'], array('1_mins'  => array(
         'label' => '1' . ' ' . __( 'Minute', 'feedzy-rss-feeds' ),
         'value' => '1_mins',
      )));
   }
   return $elements;
});
```

We noticed that it's no longer working and giving this error in the widgets section:
![image](https://user-images.githubusercontent.com/36594177/146928955-6fc73000-2c65-46c9-8efb-a93f9b7e8f26.png)

I've removed the check for screen and left the code like this:

```
add_filter('feedzy_get_form_elements_filter', function($elements) {
		 $elements['section_feed']['elements']['refresh']['opts'] = array_merge( $elements['section_feed']['elements']['refresh']['opts'], array('1_mins'  => array(
         'label' => '1' . ' ' . __( 'Minute', 'feedzy-rss-feeds' ),
         'value' => '1_mins',
      )));
		 return $elements;
	
});
```

Then it works with the Feedzy Legacy widget:
![image](https://user-images.githubusercontent.com/36594177/146929112-5890a947-127a-4de5-8011-bd6ea726ffe9.png)

However, still doesn't work with the one everyone uses now:
![image](https://user-images.githubusercontent.com/36594177/146929233-e32de891-dc04-40ea-ae25-1a94a8c63b50.png)

Can we modify the existing code to affect also the new widget and not only legacy? I've tried to check but didn't find a way to re-use it for the new widget.

### Alternatives:
-

**Comment by girishpanchal30** [comment]
Hello, @vytisbulkevicius We can't use the existing PHP filter in Gutenberg block javascript code.
Ref - https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/gutenberg/src/inspector.js#L116

I have added a new filter for the Gutenberg block so users can change feed caching time.

Here code:

```
add_action(
  'admin_footer',
  function() { ?>
  <script type="text/javascript">
    wp.hooks.addFilter( 'feedzy_widget_refresh_feed', 'feedzy-rss-feeds/feedzy-block', function( options ) {
      options.push( { label: '1 Minute', value: '1_mins' }, { label: '2 Minute', value: '2_mins' } );
      return options;
    } );
  </script>
    <?php
  }
);
```

cc @cristian-ungureanu
Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

I've downloaded the build and it works as expected (the refresh times appears) in the widgets section:
https://vertis.d.pr/XWLqrG

But even a more common usage is to use Feedzy block when creating Posts/Pages and it doesn't seem to affect refresh times there: https://vertis.d.pr/XWLqrG

Can we make the code universal so it affects the Feedzy block in any place wherever it's added? (the code for the legacy block was affecting it in all areas)


Thank you!

**Comment by girishpanchal30** [comment]
Hello, @vytisbulkevicius The above filter also apply in Posts/Pages

Ref: https://tinyurl.com/y4zdf569

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested the filter and it is not applied when creating a post/page. Let me know if any more steps are required in order to make it work.

**Comment by girishpanchal30** [comment]
@irinelenache Can you share test instance login details?
Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 
```
https://lameswim.tastewp.com/2022/01/12/test-custom-refresh-time/
user: irinel
password: 7nxuf8agbpI
```

**Comment by girishpanchal30** [comment]
@irinelenache Here is the updated filter:
```
add_action(
  'admin_print_footer_scripts',
  function() { ?>
  <script type="text/javascript">
    wp.hooks.addFilter( 'feedzy_widget_refresh_feed', 'feedzy-rss-feeds/feedzy-block', function( options ) {
      options.push( { label: '1 Minute', value: '1_mins' }, { label: '2 Minute', value: '2_mins' } );
      return options;
    } );
  </script>
    <?php
  }
);
```

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and now the filter works as expected, thanks 👍
