### ISSUE TITLE
Feedzy widget missing in Elementor editor since Elementor's version 3.5

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#628]
### Description:
Feedzy widget is no longer available in Elementor if you upgrade to Elementor 3.5 or later [latest one is 3.5.3]:
https://vertis.d.pr/HY6S64

If you roll back to Elementor 3.4.8 (the version before 3.5) it works:
https://vertis.d.pr/QoksFJ

_Rolling back Feedzy version doesn't fix it so it doesn't look like caused by some change that we recently made when solving this one:
https://github.com/Codeinwp/feedzy-rss-feeds/issues/586_

### How to reproduce:
1. Install Elementor Free and Feedzy Free version
2. Create any post/page or edit existing [With Elementor]
3. Try to search for Feedzy widget - it's not there
4. Rollback Elementor to version 3.4.8 and search again [Feedzy widget should be visible]

### Expected behaviour:
Feedzy widget should be present in the newest version of Elementor.

### Current behaviour:
Feedzy widget is missing.

### Reference:
Could be checked here for a few days:
Admin area URL: https://jamcalculator.tastewp.com/wp-admin
Username: bvytis  
Password: hCjgY46UTAk

Reported here - https://secure.helpscout.net/conversation/1749426581/305245/

### Technical info
* WordPress version: 5.8.2
* Feedzy Plugin version [Free]: 3.8.1
* Elementor version [Free]: 3.5.3

**Comment by girishpanchal30** [comment]
Hello, @vytisbulkevicius I have checked and found the feedzy widget is available in the WordPress category, but I have noticed the Elementor search widget excludes the WordPress category in the latest version.

Ref: https://tinyurl.com/yyvoop6n

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Thank you for your finding, I see it there now also.
I also checked Elementor's notes for that release here - https://wordpress.org/plugins/elementor/#developers
And it should related to: https://vertis.d.pr/d2TxKk

The question here, maybe it's possible to change the way our plugin adds itself to Elementor's sidebar?
Because I tried to install another plugin WpForms - https://wordpress.org/plugins/wpforms-lite/

And this plugin appears in Basic section - https://vertis.d.pr/o3cXfH which makes it searchable: https://vertis.d.pr/pinfga

I'm trying to understand the difference between why Feedzy plugin appears as a native WordPress widget and let's say wpforms plugin appears in the Basic section.

cc @cristian-ungureanu if you have any advice here, thank you!

**Comment by girishpanchal30** [comment]
Hello, @vytisbulkevicius WpForms plugin widget does not register with the default WordPress widget method, it registers using the custom elementor widget method with `Basic Category` category, so it displays and searchable.

Also, we have already registered feedzy elementor widget for Pro plugin users only.

Here - https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/233
Ref - https://tinyurl.com/y4qsgvp4

Thanks

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

So maybe we should also use Basic category to make Feedzy widget available in search? This will prevent confusion from users when they can't find the widget.

Yes, I'm aware of Feedzy Loop available for PRO version but it does not replace the Feedzy widget, it's additional functionality that allows creating a custom template that could be later used with Feedzy widget to show content in a custom way so we still need Feedzy widget to be findable easily.

**Comment by girishpanchal30** [comment]
Hello, @vytisbulkevicius The basic category is part of elementor widget, We couldn't change the widget category directly.

We can contact elementor support for this issue in the latest release

cc @cristian-ungureanu

Thanks

**Comment by cristian-ungureanu** [comment]
@girishpanchal30 so from my understanding the widget does not appear because it's registered via WP_Widget and Elementor is not indexing them anymore.  I think we could check and see what changed in Elementor, maybe we can use a filter to add it back.
If that's not working I think we can create a dedicated widget for Elementor https://developers.elementor.com/docs/widgets/

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Fixed the Elementor search widget issue, Please check and verify.

cc @cristian-ungureanu
Thanks

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

Thank you! I've checked with the new **build** and I see Feedzy widget in the search: https://vertis.d.pr/ZNKO0Q 👏
