### ISSUE TITLE
Question: Can we check the feed asynchronously so the page doesn't have to wait for the feed?

### ISSUE THREAD

**Issue by Skystream96** [Codeinwp/feedzy-rss-feeds#636]
### Description:
There is one user that reported that he is using a slow feed which in turn leads to a slow rendering of the page where the feed is used because Feedzy is waiting for the content to be fetched before displaying. I do have to mention that he is using the display feature, not the feed to post one.

The user reported:
**_I don’t think you have to check feeds synchronously on every call. I think you could simply collect feed entries of used feeds_** **_asynchronous without making the page response time of your own web page bad, when one of the used feeds has bad load times._**

**_In my case today, only one of many feeds which I used had high load time, and this also affected the web page very badly, on which I used feedzy with this specific feed._**
**_By verifying all used feeds and deleting the high response time external feed, the problem was fixed._**

[User reported here.](https://wordpress.org/support/topic/about-caching-and-page-speed-using-feedzy/#post-15302846)

What do you think about this?

**Comment by girishpanchal30** [comment]
@Skystream96 What do think if we implement a background lazy load image?
Ref: http://jquery.eisbehr.de/lazy/example_load-background-images
Thanks

**Comment by Skystream96** [comment]
Hello @girishpanchal30 ,

Well, that would be good too although I personally prefer the "Loading" spinner that you can also customize. Since we already have a lazy load feature, maybe we could implement a message when checking the feeds that will say "This feed has high load times that might result in a slow page. We suggest eliminating it or replacing it with a better one" 

Would this be feasible?

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

I agree with your suggestion to have lazy-loading images just to make it optional, of course, not hardcoded as some users might not like it.

What @Skystream96 mentioned also makes sense to make a notification for the admin user that this feed is making the website slow but only if it's a small quick-change for you as I don't think it's a big change we need to put many resources on as I haven't heard such complaints before.

As we already have caching time, lazy-loading of the whole widget should be enough to reduce the loading time significantly so if we also add it for images everything should be fine.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius
> I agree with your suggestion to have lazy-loading images just to make it optional, of course, not hardcoded as some users might not like it.

Sure, We can add a new global setting field here(https://tinyurl.com/y79ghw7e) so users can enable lazy load images, by default setting is disabled.

> What @Skystream96 mentioned also makes sense to make a notification for the admin user that this feed is making the website slow but only if it's a small quick-change for you as I don't think it's a big change we need to put many resources on as I haven't heard such complaints before.

I doubt that we can identify whether the feed is taking more load time or not.

Thanks

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

Good, no need for the 2nd point them about evaluating the time feed will take to load. ✅

Regarding the lazy-loading for images, have you added this setting in this area just because it's the only place we can control something globally? I just want to be sure we're on the same page and we're talking about Feedzy block/shortcode functionality and not the imported posts because if I'm a user and I see this setting here my understanding will be that it is for importing posts because all the other settings here are related to the import.

If we add it here we need to highlight/make a note that this functionality is a global setting to all the shortcodes/blocks added by Feedzy and is not related to importing posts. Something like this - https://vertis.d.pr/6YEb0u

**Comment by girishpanchal30** [comment]
@vytisbulkevicius I understand your opinion, I think we need to add new setting support here...

1) Widget - https://tinyurl.com/yapms368
2) Block - https://tinyurl.com/yau8jw5u
3) [feedzy-rss feeds="https://s3.amazonaws.com/downloads.themeisle.com/sample-feed-import.xml" lazy-images="yes|no"]

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,

I agree that this way it's better and more clear. We can document this new feature after it's released. Thank you.

**Comment by girishpanchal30** [comment]
Hello, @vytisbulkevicius as per our discussion I have added lazy load image support.

Added a new setting field here.

Block - https://tinyurl.com/ya6bq34a
Widget - https://tinyurl.com/y8qobk2b
ShortCode - [feedzy-rss feeds="https://s3.amazonaws.com/downloads.themeisle.com/sample-feed-import.xml" **lazy-images="yes|no"**]

PR - Codeinwp/feedzy-rss-feeds/pull/640, Codeinwp/feedzy-rss-feeds-pro/pull/456

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the feature seems to work fine, except for the feedzy shortcode. 

You can check here, the **feedzy-lazy-img** class is not present for the images in the post.
```
https://forceshoe.tastewp.com/2022/02/11/test-feedzy/
Username: irinel  
Password: CvL_VMoJ9qY
```

**Comment by girishpanchal30** [comment]
@irinelenache Please use this shortcode attribute `lazy_images="yes|no"` instead of `lazy-images="yes|no"`
Sorry for this I have added the wrong shortcode attribute in my previous comment.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested again and i see that the lazy load is working fine with the shortcode too, thank you 👍

**Comment by selul** [comment]
@girishpanchal30 I realized now that is not something that I would add in the plugin: 

- Lazy load of images is a whole topic and adds a lot of complexity, which is not in the scope of what feedzy can offer. Implementing a lazyload for images mechanism when there are numerous plugins that people can have to use lazyload looks like over-engineering and is not something that I would add in the plugin. Ofc, not saying about when they have both, feedzy one and the lazyload from the 3rd party plugin which will turn into a cat and mouse game to fix compatibility. 
- What we can do to have something meaningful for the user end is to add the native lazyload attribute to all images, see https://web.dev/browser-level-image-lazy-loading/

That being said, let's revert this and add just the native lazyload by default.

**Comment by selul** [comment]
@vytisbulkevicius @Skystream96 please review this and keep in mind when such decisions are made in the future.

**Comment by girishpanchal30** [comment]
> That being said, let's revert this and add just the native lazyload by default.

@selul In our plugin structure, the images come as a background image and those are not in img tag where a default lazy loader needs img tag.
See this is an example: https://github.com/Codeinwp/feedzy-rss-feeds/commit/4467e138752ed3e1ee70fe2e9f3f0d3aeea9e6a9#diff-5ed08dc376008699ed28840a8f1f2e149073a6ccc4b0dcf043edc036754f995dR1305

**Comment by selul** [comment]
@girishpanchal30 thanks for the reminder, I totally forgot about this. 

In this case what I would do is to implement for images content visibility: auto using some CSS class. For more details see https://developer.mozilla.org/en-US/docs/Web/CSS/content-visibility



Also, another thing related to the lazyload implementation that you used is the fact that we load a 3rd party script from an external domain. I think doing another request, on a different domain and loading a good payload of JS might have a similar downside vs non-lazyloading the images.

**Comment by girishpanchal30** [comment]
> Also, another thing related to the lazyload implementation that you used is the fact that we load a 3rd party script from an external domain. I think doing another request, on a different domain and loading a good payload of JS might have a similar downside vs non-lazyloading the images.

@selul Should I load the script locally instead of using CDN URL Right?
Thanks

**Comment by selul** [comment]
@girishpanchal30 as I mentioned, we don't need to implement any lazyload based on a 3rd party script and use standard HTML/CSS to improve this. For bg images, we can experiment with content-visibility prop.

**Comment by girishpanchal30** [comment]
@selul Okay, I'll check the HTML/CSS method and update you here.
Thanks

**Comment by girishpanchal30** [comment]
@selul I have removed 3rd party script and added content-visibility: auto support for feed images.
I have checked rendering statistics in the chrome performance tool. Please check and do let me know if you have any issues.

Thanks

**Comment by selul** [comment]
@girishpanchal30 looking good
