### ISSUE TITLE
Feedzy tags and Elementor Dynamic tags

### ISSUE THREAD

**Issue by m-vdv** [Codeinwp/feedzy-rss-feeds#650]
### Description:
Feedzy feed item tags are not properly displayed in Elementor when using Feed to Post.

### How to reproduce:
1. Install Elementor, Elementor Pro, Feedzy & Feedzy Pro with Elementor Hello theme.
2. Import a Feed through Feedzy > Import Posts (Feed to Post)
3. Create a Single post template in Elementor
4. Add an Elementor widget with Dynamic tag support
5. Select Dynamic tag: Feedzy Feed Items > Feed tags > Item title _(or any other tag)_
6. Outputs: `[#item_title]`

### Expected behaviour:
Should output actual item title

### Current behaviour:
Outputs: `[#item_title]`

### Reference:
<img width="291" alt="image" src="https://user-images.githubusercontent.com/1878691/162077630-ca8e2b5c-13f3-4626-a8a9-3ffcfba32ad2.png">
<img width="130" alt="image" src="https://user-images.githubusercontent.com/1878691/162077673-0efa0b6e-5bc3-4c03-89b5-6a5346e7f1e8.png">

### Technical info
* WordPress version: WordPress 5.9.3
* Plugin version: 3.8.2
* Pro plugin version: 1.8.2
* Elementor version: 3.6.2
* Elementor Pro version: 3.6.4

**Comment by girishpanchal30** [comment]
@m-vdv Feedzy tags work only if Elementor template is Feedzy Loop. Please create a template using Feedzy Loop then you can use the template in a single post.

Please follow this document: https://docs.themeisle.com/article/1396-elementor-compatibility-in-feedzy
Do let me know if you have any query.

Thanks

**Comment by girishpanchal30** [comment]
@m-vdv 

As per the document (https://docs.themeisle.com/article/1396-elementor-compatibility-in-feedzy)

 Feedzy tags works with Feedzy Loop Template Only. So I have did modification in feedzy tag. so now feedzy tags will only display if Elementor template is  "Feedzy Loop" it will not display if you choose single post or any other template from Elementor.  
 
 for details refer below video link.
[(https://www.awesomescreenshot.com/video/9066340)]
