### ISSUE TITLE
Video thumbnail is displayed instead of image from the description element

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/feedzy-rss-feeds#652]
### Description:
The feed is displayed using the shortcode method. When the feed contains a media, i.e YouTube video, and the **<media:thumbnail>** tag is available - this will be the one displayed as the thumbnail image and not the image within the description element.

Feed: https://my.sjcme.edu/home/feed/

### How to reproduce:

1. Create a new post and add the Feedzy RSS block
2. Enter the feed: https://my.sjcme.edu/home/feed. https://vertis.d.pr/HtBK9S
The highlighted feed contains a YouTube video and the thumbnail is an image of the video.
3.  Here is a snippet of the feed: https://vertis.d.pr/w7ySE9

### Expected behavior:
The image thumbnail should be coming from within the description tag.

### Current behavior:
The image thumbnail is pulled up from the <media:thumbnail> when the feed contains a media or if the <media:thumbnail> tag is available.
### Reference:
https://secure.helpscout.net/conversation/1860711787/319032/

**Comment by vytisbulkevicius** [comment]
To add additional context here, for me it's not clear the reason behind the result not that it's wrong. We use SimplePie with Feedzy and if we check the same feed in simplePie demo here:
http://simplepie.org/demo/?feed=https%3A%2F%2Fmy.sjcme.edu%2Fhome%2Ffeed%2F

We see that image from the description is being taken: https://vertis.d.pr/aphhQT

So I wouldn't say which case is good or bad as other users might want the image that is added next to the video element as the thumbnail and they would like the result they are getting with Feedzy but we would like to understand the reason why is there a difference between what we get in SimplePie demo and the result that Feeedzy shows.

What are the criteria that we use when selecting an image if there are multiple images? I thought we take the first one but then it would be the one from the description.

**Comment by girishpanchal30** [comment]
Hello @vytisbulkevicius,

I have fixed the display image issue. Please check and do let me know if you have any issues.

Thanks

**Comment by purplecodes** [comment]
I tested this and it is now the displaying the correct image.
Thanks.

cc: @vytisbulkevicius , @girishpanchal30
