### ISSUE TITLE
Category added as a source to Feedzy block appears as invalid after page refresh in dashboard

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#655]
### Description:
If you create a category in Feedzy, even if you add only one valid XML RSS Feed URL, once that category is used for Feedzy block it appears as invalid after you refresh the page.

Here is a screencast about it: https://vertis.d.pr/ZwQIOS (in front-end it works fine, the issue happens in the dashboard only)

Feed to try: http://dailycoffeenews.com/feed/

**If you try the same Feed but not as a category the issue doesn't happen.**

### How to reproduce:
1. Create a new category and add one or multiple feeds, you can try this one - http://dailycoffeenews.com/feed/
2. To to any post/page and add Feedzy block, select the category you create and save it, click to publish/update the post/page created.
3. Refresh the page and you'll see the error, it fetches items again only if you click "Load Feed"
<img width="644" alt="image" src="https://user-images.githubusercontent.com/36594177/169717516-7981bfdb-0c3a-4ab6-8f45-c40a76a18b18.png">

### Expected behaviour:
The valid category should be fetched automatically on page load in dashboard.
### Current behaviour:
Error is thrown that category is invalid.
### Reference:
Screencast above.
Reported here - https://secure.helpscout.net/conversation/1889304000/323505/

### Technical info
* WordPress version: 5.9.3
* Plugin version: 3.8.3

**Comment by girishpanchal30** [comment]
@vytisbulkevicius 
I have already fix it. So please test it with below ticket. Please test and let me know if facing any issue.
https://github.com/Codeinwp/feedzy-rss-feeds/issues/645

**Comment by vytisbulkevicius** [comment]
@girishpanchal30,
Indeed, it's fixed there already, been a while since that issue was raised so forgot about it. Thanks!
Closing this one as it's a duplicate.
