### ISSUE TITLE
Feedzy icon not visible with the Classic Editor plugin

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/feedzy-rss-feeds#667]
### Description:

If the Classic Editor plugin is used, the Feedzy icon can't be seen in the bar even though it is there and it can be clicked and the functionality of displaying the feed items is working properly. A square and the Feedzy Lite tag appear only when you hover on that space.

### How to reproduce:

1. Install the Classic Editor plugin
2. Open a page and check the bar from the classic editor, the button for Feedzy is after Toolbar Toggle but it isn't visible

### Expected behaviour:
The icon is visible.

### Current behaviour:
The icon can't be seen.

### Reference:

![capture3](https://user-images.githubusercontent.com/86592341/183861592-15b7cf1d-bb93-4aaf-8413-6fafa52666a6.png)

### Technical info
* WordPress version: 6.0.1
* Plugin version: 4.0.1

**Comment by girishpanchal30** [comment]
Hello @MarinescuLucia,
I have fixed the TinyMce UI issue, Please check and verify.

Before: https://tinyurl.com/2mlon7uf
After: https://tinyurl.com/2za73pb4

cc @irinelenache
Thanks

**Comment by MarinescuLucia** [comment]
@girishpanchal30 Checked it and it is displayed properly now. Thank you!
