### ISSUE TITLE
Duplicated upsell card in support section

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/feedzy-rss-feeds#669]
### Description:

There is a duplicated upsell card in the support section of feedzy, in dashboard https://d.pr/XW9xUY
### How to reproduce:

1. Install feedzy and go to Dashboard > Feedzy > Support

### Expected behaviour:
The card should not be duplicated
### Current behaviour:
The card is duplicated
### Reference:

https://d.pr/XW9xUY
### Technical info
* WordPress version: 6.0.1
* Plugin version: 4.0.1

**Comment by girishpanchal30** [comment]
Hey @irinelenache,

I have removed the duplicate card and added a new card( Spintax Text ). 
Also, I have changed some duplicate learn more links, please check and do let me know if you have any issues.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Everything's fine now, thank you 🚀
