### ISSUE TITLE
enter on gutenberg block should load the feed

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#675]
### Description:
Right now if I want to use the Feedzy block I need to click on load feed btn to load the feed. 
We can look into adding enter key support and whenever the user presses ENTER key, to load the feed.

**Comment by selul** [comment]
Same thing on the import screen https://vertis.d.pr/xrfpV0, clicking enter should behave the same as clicking plus icon.

**Comment by selul** [comment]
@girishpanchal30 reading the code change you have added this to gutenberg block only, not to the import screen. Can you add to the import screen too, ie: 
https://github.com/Codeinwp/feedzy-rss-feeds/issues/675#issuecomment-1240965857

**Comment by girishpanchal30** [comment]
@selul It seems working from my end. You can check the code here - https://github.com/Codeinwp/feedzy-rss-feeds/blob/development/includes/views/js/import-metabox-edit.js#L247
Can you please provide system/browser details so I can check quickly?

Thanks

**Comment by selul** [comment]
@girishpanchal30 thanks, I confused things here, for import there is another thing that we can do better: 
- clicking on validate should add the feed automatically
- moving out of focus should automatically consider the feed.

Basically, the issue right now is that I'm adding the feed and unless I click the plus icon or enter, the feed is not saved.

**Comment by girishpanchal30** [comment]
@selul Fixed/Applied your suggestions, please check with the latest commit.

Thanks
