### ISSUE TITLE
Text duplicated on the Help us Improve Tab

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/feedzy-rss-feeds#679]
### Description:

This text appears twice in the same box: _If your feedback is especially helpful and we choose to do an interview with you to discuss your suggestions, you will even gain a yearly membership for free for your trouble._

![Screenshot 2022-09-15 at 12 24 44](https://user-images.githubusercontent.com/52494172/190394568-fc51fad8-56eb-458c-9e6f-183f2c226ce8.png)

### How to reproduce:

1.
2.
3.

### Technical info
* WordPress version: 6.0.2
* Plugin version: 4.0.2

**Comment by irinelenache** [comment]
@girishpanchal30 The duplicated text is fine now 👍
