### ISSUE TITLE
Minor upsell improvements 

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/feedzy-rss-feeds#681]
### Description:

While working on the Amazon integration, I noticed a few things that can be improved:

- [x] **Upsell section in Elementor**
 Here the idea of the section is to upsell Feedzy Pro, and have a link to the docs - as a secondary action.
 Right now the learn more button points to the Docs
<img width="1287" alt="Screenshot 2022-09-19 at 17 15 29" src="https://user-images.githubusercontent.com/52494172/191039240-528fa170-7aed-49a0-ba25-8708f125fe88.png">

___

- [x] I the widget area of Elementor, I see that **we have 2 Feedzy widgets. Do we need both of them?** one is legacy and one new, or why do we need both?

https://user-images.githubusercontent.com/52494172/191040038-933435ac-d8ef-47e8-b339-9a70455bea46.mov

___

- [x] Lets **increase a bit the Opacity for all the locked fields** in Gutenberg, as at the moment those are barely visible. 
Right now the opacity is .2 , **let's change that to .40**:
 
<img width="1721" alt="Screenshot 2022-09-20 at 13 57 58" src="https://user-images.githubusercontent.com/52494172/191240757-99ca71bb-6411-4a87-ae17-5d3b7de4ab04.png">

**Comment by selul** [comment]
@girishpanchal30 yes, if we can remove the old one from listing and keep it working for users that use it, would be good.

**Comment by girishpanchal30** [comment]
> if we can remove the old one from listing and keep it working for users that use it, would be good.

@mghenciu @selul I have removed the legacy widget as per your suggestion.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and everything seems to work fine, found a small thing only:

- [ ] Now in the elementor widget, the feedzy docs link is also [a button](https://vertis.d.pr/DLQ4t8). @mghenciu can you confirm if this is/isn't the desired behaviour?

**Comment by girishpanchal30** [comment]
@irinelenache it seems cache issue, please do a hard refresh

**Comment by mghenciu** [comment]
> @girishpanchal30 Tested and everything seems to work fine, found a small thing only:
> 
> * [ ]  Now in the elementor widget, the feedzy docs link is also [a button](https://vertis.d.pr/DLQ4t8). @mghenciu can you confirm if this is/isn't the desired behaviour?

The Docs link should be a **text link**, not a button  @girishpanchal30

**Comment by girishpanchal30** [comment]
@mghenciu  On my end, it's looks like this - https://tinyurl.com/2lx3a3re

**Comment by irinelenache** [comment]
@girishpanchal30 @mghenciu I checked again on incognito mode and it works fine actually, thank you for checking 👍 
Will move this to **Ready to merge** 🚀
