### ISSUE TITLE
External Image feature is not working correctly.

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/feedzy-rss-feeds#683]
### Description:
When you use the External Image feature for posts imports on feedzy then you will observe that the thumbnail images loaded on the post archive page will have a distorted size (irregular than the normal featured images). 

Note: I already checked this issue with multiple RSS feed URLs.
### How to reproduce:

1. Install feedzy and create a New feedzy feed by using any RSS feed of your choice.
2. Go to Map settings > General and add the [#item_image] tag in the Featured Image section.
3. Now go to Map settings > Advanced option settings. 
4. Enable the External Image toggle.
5. Publish the import and run the importer from the Feedzy library.
6. Now Go to the Blog/post archive page.
7. You will observe that the size of the featured image of posts is not regular.

### Expected behavior:
The Featured images should have a regular size.
![new1](https://user-images.githubusercontent.com/110405452/192001951-9802ff63-8097-457e-b31a-63cab03f096c.png)

### Current behavior:
The Featured Image width of feedzy import posts is disturbed: 
![new2](https://user-images.githubusercontent.com/110405452/192002366-a9c77cd7-d305-4c46-8af9-115f72607c10.png)

### Reference:

You can use this RSS feed: https://it.cryptonews.com/news/feed/

![new3](https://user-images.githubusercontent.com/110405452/192003008-6fbd3651-e3ad-4951-ba00-d07a34db1aad.png)

![new4](https://user-images.githubusercontent.com/110405452/192002983-af9f693c-564b-4652-87d6-d4807f959bb2.png)
![new1](https://user-images.githubusercontent.com/110405452/192003360-8b021331-6a93-49a0-b159-bb591403f695.png)
![new2](https://user-images.githubusercontent.com/110405452/192003400-61d5d3df-1162-4e9f-acb8-c5a47f351620.png)
### Technical info
* WordPress version: 6.0.2
* Plugin version: 4.0.2

**Comment by girishpanchal30** [comment]
Hey @kushh23

Fixed external image size issue. Please check with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/684

Thanks

**Comment by kushh23** [comment]
Hey @girishpanchal30,

I Checked the PR and this issue has been fixed!

Thanks
