### ISSUE TITLE
possible fatal error when removing the legacy widget support for elementor

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#686]
### Description:
https://wordpress.org/support/topic/fatal-error-instead-of-404-page/

Seems like the checks you have added @girishpanchal30 can be reviewed.

**Comment by irinelenache** [comment]
@girishpanchal30 @selul I couldn't reproduce the issue but made some tests with the Elementor widget and some feeds and everything seems to work fine with the PR
