### ISSUE TITLE
possible cache duration issue

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#687]
### Description:
We have this doc that instructs users on how to change the caching https://docs.themeisle.com/article/942-in-feedzy-how-do-i#lifetime-cache

One user reported that is no longer the filter value https://wordpress.org/support/topic/version-4-0-3-breaks-caching-4-0-2-works-fine/ and looking at the code from  #678  I think he might be right, so we need to investigate this. 

If an issue is found we need to fix it and also add a PHP unit test to avoid this kind of issue from happening.

**Comment by girishpanchal30** [comment]
Hey @selul,

I have checked and fixed this issue. I think no need to add a PHP unit test for the filter test.

I've made changes as per the WordPress core. Please review and do let me know if you have found any issues.
Ref: https://github.com/WordPress/wordpress-develop/blob/trunk/src/wp-includes/feed.php#L817

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested the fix and the snippet works fine for me now 👍

**Comment by MarinescuLucia** [comment]
The user came back mentioning that the issue still occurs for him with the latest version https://wordpress.org/support/topic/version-4-0-3-breaks-caching-4-0-2-works-fine/#post-16089810.

**Comment by girishpanchal30** [comment]
Hello @MarinescuLucia,

I have fixed the issue. Can you please check with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/694?

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Can you give me some more info about how to test this? The feed was refreshing for me before this PR but i don't know how to properly check the filter. Thank you

**Comment by girishpanchal30** [comment]
Hey @irinelenache,

Please add the below filter in your active theme functions.php file and check the feed updates the data based on the filter value or not.
```
function bweb_feedzy_cache_duration( $feedCacheDuration, $feedURL ) {
        // Set cache duration for specific feeds only.
	if ( 'https://copiague.librarycalendar.com/events/feed/rss' == $feedURL ) {
		return 60 * 5; // 5 minutes
	}
	return $feedCacheDuration;
}
add_filter( 'wp_feed_cache_transient_lifetime', 'bweb_feedzy_cache_duration', 10, 2 );
```

Also, Please change the feed URL according to your feed in the filter.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Thank you, i waited some time for the feed to update and the filter is working fine on my end, will move this to **Ready to merge** 👍
