### ISSUE TITLE
Unable to add all the Magic tags in one flow.

### ISSUE THREAD

**Issue by kushh23** [Codeinwp/feedzy-rss-feeds#697]
### Description:
Hey there, I noticed this minor bug in the import job process of the feedzy. When you will create an import job and try to add the magic tags to the **Content field**, then you will notice that you are not able to add all the tags in one flow from the dropdown.

In order to add another tag you will have to click out somewhere on the screen, and only then you will be able to add other tags.

I tried to do the same thing with the **Title field** and it is working fine, we can add multiple tags in one flow.

Thank you.

### How to reproduce:

1. Create an Import job.
2. See the screencast video replicating this issue.

### Reference:
See this screencast: https://vertis.d.pr/v/FcpMdH

### Technical info
* WordPress version: 6.1
* Plugin version: 4.0.5

**Comment by girishpanchal30** [comment]
Hey @kushh23,

It seems not possible with tagify(https://yaireo.github.io/tagify/) mix content method. we need to always click on the box after adding a tag.

I've added some changes to improve the textarea box focus.
PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/699

Thanks

**Comment by kushh23** [comment]
Thanks @girishpanchal30 !!

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and everything works fine with this PR 👍
