### ISSUE TITLE
Question about caching when the shortcode is used

### ISSUE THREAD

**Issue by MarinescuLucia** [Codeinwp/feedzy-rss-feeds#706]
### Description:

A user mentioned that new `_transient_feed_ ` entries appear in the wp_options table for each user that visits the page where a shortcode with a feed is displayed, instead of only one entry appearing once for each feed. We checked this and it seems like he is right - [here](https://vertis.d.pr/v/Zw6vRb) is a screencast where this behaviour can be seen. Is this the desired behaviour or can it be improved to increase efficiency?

Reported [here](https://wordpress.org/support/topic/caching-for-widget-feeds-does-not-work-efficiently/).

### Technical info
* WordPress version:6.1.1
* Plugin version: 4.1.0

**Comment by girishpanchal30** [comment]
Hey @MarinescuLucia,

I can't replicate this issue in my local system. Can you please share your test instance details here?

Tested with codeinwp feed - https://www.codeinwp.com/feed/

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Have you tried visiting the page using incognito mode/private browsing? If you are using same session a new transient is not created. I was able to replicate this also. I see @MarinescuLucia  hasn't mentioned it.

I can replicate the issue on https://app.instawp.io/dashboard

Shortcode used:
`[feedzy-rss feeds="https://www.codeinwp.com/feed/" max="2" feed_title="yes" meta="author"]` (doesn't really matter what is the feed)

Page - https://n-for-kids-yuco.instawp.xyz/hello-world/

instawp has an option to check database also so every time a new session of browser is used to open that page additional transient is registered:
<img width="908" alt="image" src="https://user-images.githubusercontent.com/36594177/209238248-48b1a5a3-c72e-4140-9b9e-0b2457d1b985.png">

You can log in to the dashboard here - https://app.instawp.io/wordpress-auto-login?site=$2y$10$PXUG2gLwfO6vM8I6xAnQBOGO9ylFAYHD5mKe8HnixTvUaLadsiqDu

I just can't provide credentials to the database management tool but let me know if it still doesn't happen for you.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

Thank you for the information, I got this issue and it's fixed now with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/713/

How to replicate the issue?

1. Create page with feedzy shortcode
2. Open the page in the chrome browser
3. Check transient in the database
4. Now open the page in another browser and you can see the new transient in database

Check the screencast [video](https://www.loom.com/share/cefd13e33b0541e5a69b4f62b0330a1c) for a better understanding

Thanks

**Comment by MarinescuLucia** [comment]
@girishpanchal30  @vytisbulkevicius  I'm so sorry, I don't know how I missed this. I think I may have opened the mail received from GitHub when Girish tagged me, didn't reply right away for some reason and forgot to reply after that. I'm so sorry. Thanks for providing details about your test instance, Vytis! Let me know if anything else is needed here.

**Comment by girishpanchal30** [comment]
> Let me know if anything else is needed here.

@MarinescuLucia No need for more details, please check with attached PR and let me know if you encounter any problems.

**Comment by MarinescuLucia** [comment]
@girishpanchal30 I tested this on three browsers and it seems to be ok now, no new transients are created every time I check the page from a different browser.

Thank you!

**Comment by selul** [comment]
@girishpanchal30 checks are failing, please review them.

**Comment by girishpanchal30** [comment]
@selul checklist issue is fixed in this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/704, Can you please merge this PR?

Ref: https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/483#issuecomment-1360863867

Thanks
