### ISSUE TITLE
"className" parameter in shortcode

### ISSUE THREAD

**Issue by poonam279** [Codeinwp/feedzy-rss-feeds#707]
### Description:

A user reported that we have "className" parameter in the shortcode. However, the WordPress shortcode case is insensitive. So this shortcode parameter does not work in the plugin at the moment. 
More info: https://core.trac.wordpress.org/ticket/46412

The parameter can be found in this source code:
https://plugins.trac.wordpress.org/browser/feedzy-rss-feeds/tags/4.1.0/includes/abstract/feedzy-rss-feeds-admin-abstract.php#L622

### Reference:

https://secure.helpscout.net/conversation/2096537274/348437?folderId=212385

### Technical info
* WordPress version: 6.1.1
* Plugin version: 4.1.0

**Comment by girishpanchal30** [comment]
Hello @poonam279,
I've fixed this issue, now user can use "className" or "classname"

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the classname parameter works fine now 🚀
