### ISSUE TITLE
have a no style option for shortcote/block/widget

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#710]
Let's add an option for feedzy in all contexts where people can inherit the style of their theme and avoid adding any CSS by us. 

This will be available for free.

Here is the full context: 

> The design is still not clean https://share.cleanshot.com/zVWPcBjn - https://share.cleanshot.com/DHgZ021n - and there doesn't seem to be an option to remove those. that class=title addition is the most problematic. Since most sites will have a class named like that, so it applies random styles for the most part. An option to have no style at all - just a regular ul list with no other markup

Additionally when that option is used, we should not add the CSS for that. 

THe option can be globally, in the settings area and will have the option to use locally too, per block/shortcode/widget and the global one will act as default.

**Comment by selul** [comment]
@girishpanchal30 can you add here you dev plan to avoid going in a different direction from what the issue had in mind.

**Comment by girishpanchal30** [comment]
Yes sure, I'll add the top WordPress theme name checklist here and test with feedzy shortcode/block/widget one by one.

**Comment by girishpanchal30** [comment]
@selul Below is the dev plan. Please review and let me know if I missed any points.

1) Register new setting options in the widget/block/shortcode and global settings area.
   - **_Setting Name:_** `Disable default style`
   - **_Description:_** `This setting will be used to inherit the current theme style instead of the default plugin style.`
   - **_Field Type:_** `Toggle buttion`
   - **_Default:_** `Off`

   Note: The setting in widget/block/shortcode will be inherited from the global setting.

2) If the setting is enabled then inherit the current theme style instead of feedzy default style.
   - Inherit apply to ul, li, a, p, img, etc tags.
   - Add a new class in the parent element to exclude default CSS by class name.

3) When everything is finished, we will review the top 20 themes and inspect the feed design.

Thanks

**Comment by selul** [comment]
@girishpanchal30 this looks good, the only thing to mention is related to 2, I would like ideally if the default style is not used, to not load it at all in frontend.

**Comment by girishpanchal30** [comment]
> I would like ideally if the default style is not used, to not load it at all in frontend.

@selul Okay, I'll dequeue/deregister the default style if the setting is enabled.

**Comment by girishpanchal30** [comment]
@selul I've implemented inherit style support as per the dev plan.

> Register new setting options in the widget/block/shortcode and global settings area.
```
Elementor Widget - https://tinyurl.com/2plwbr5t
Block - https://tinyurl.com/2gmwvrpt
Shortcode - [feedzy-rss feeds="https://s3.amazonaws.com/downloads.themeisle.com/sample-feed-import.xml" disable_default_style="yes|no"]
```

### I've tested with below theme list ###

1) Hestia - https://tinyurl.com/2hu5v5l9
2) GeneratePress - https://tinyurl.com/2mce73q2
3) Hello Elementor - https://tinyurl.com/2glagufa
4) Neve - https://tinyurl.com/2luf9f3p
5) Newspaper - https://tinyurl.com/2jqz7a7v
6) Twenty Nineteen - https://tinyurl.com/2qh4eqdz
7) Twenty Twenty - https://tinyurl.com/2louuf5p
8) Twenty Twenty-One - https://tinyurl.com/2lxyvhc4
9) Twenty Twenty-Two - https://tinyurl.com/2k5ljnvv
10) Twenty Twenty-Three - https://tinyurl.com/2hhw8b3u
11) Astra - https://tinyurl.com/2etj4psv
12) OceanWP - https://tinyurl.com/2esu4253
12) Storefront - https://tinyurl.com/2lxvym47
13) Sydney - https://tinyurl.com/2rytfzxs
14) OnePress - https://tinyurl.com/2p7jwrgo
15) Kadence - https://tinyurl.com/2qrfnlt9
16) PopularFX - https://tinyurl.com/2h7cbwzl
17) Raft - https://tinyurl.com/2hsr53pd
18) Go - https://tinyurl.com/2ntjybcn
19) ColorMag - https://tinyurl.com/2j47hsvc
20) Newsup - https://tinyurl.com/2ktatojj

Check the following PRs, and let me know if you see any issues.
Free - https://github.com/Codeinwp/feedzy-rss-feeds/pull/720
Pro - https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/527

Thanks

**Comment by selul** [comment]
@girishpanchal30 do we have also a global switch ?

**Comment by girishpanchal30** [comment]
@selul Yes
WordPress Default widgets - https://tinyurl.com/2zvkyrrq
Feedzy settings - https://tinyurl.com/2kfl92mt

**Comment by selul** [comment]
LGTM, we can move to test. Thanks for this.

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and didn't find any problem here 🚀
