### ISSUE TITLE
add general settings

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#72]
@contactashish13 i would like to add a general settings page, under the Feedzy main menu. 

this will provide 4 fields which will be used when fetching the feed content: 

1. User agent - add a input field for allowing users to add custom user agents. The user agent will be set in this function https://github.com/Codeinwp/feedzy-rss-feeds/blob/4e64b0fefe29f040513c5774c8089983037d05cd/includes/abstract/feedzy-rss-feeds-admin-abstract.php#L363 and using the `http_headers_useragent` filter. Make sure after the fetch is done, to remove the function hooked to that filter in order to avoid problems with other requests. 
2. Proxy settings, proxy host, port user and password  . you need to setup the some constants to use proxies, you have them detailed here: https://github.com/WordPress/WordPress/blob/master/wp-includes/class-wp-http-proxy.php as well as hooking into pre_http_send_through_proxy fitering for allowing using proxy only for that specific url and not other. Also when defining the constans you need to make sure those were not defined before.

**Comment by contactashish13** [comment]
@selul i've moved all these from awaiting triage to current week. can you prioritize them as you wish to?

**Comment by contactashish13** [comment]
@selul It seems like every feed url will be called twice because a custom simple pie implementation is being used along with the default WP one: 

https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/abstract/feedzy-rss-feeds-admin-abstract.php#L327

https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/abstract/feedzy-rss-feeds-admin-abstract.php#L369

Either implementation should be used but not both. Is this as per design?

**Comment by selul** [comment]
yes, the one with init_feed is valid.

**Comment by contactashish13** [comment]
so the whole block https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/abstract/feedzy-rss-feeds-admin-abstract.php#L364-L384 should be commented out?

**Comment by selul** [comment]
not really, only the 369, but we can leave them there, it will not affect anything.

**Comment by contactashish13** [comment]
@selul well it makes 2 request per URL so it is inefficient. But its alright if you want to leave it there.

Also, the implementation you want through HTTP will only work on 4.8+. On 4.7+ WP_HTTP is not used by simplepie. Is that alright?

**Comment by selul** [comment]
yes, that's ok.

**Comment by contactashish13** [comment]
@selul It took me a long time to figure out that the cache was on and thats why none of the requests were passing through HTTP. So I don't think 4.7 is a problem. PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/

Have also added support for the parrot plugin.

**Comment by selul** [comment]
@contactashish13 i liked how you used actions and filters to hook/unhook the useragent and proxy, well done. 

I have added 2 comments in the pr.

**Comment by contactashish13** [comment]
@selul i can't see the comments. And the PR is https://github.com/Codeinwp/feedzy-rss-feeds/pull/73. Don't know how the 73 went missing.

**Comment by selul** [comment]
@contactashish13 do you see them no on #73

**Comment by selul** [comment]
@contactashish13 if you activate the pro version, and enable the agency filter, you will see that we have there also a settings area with the wordai credentials. 

i would like to integrate the settings from lite into this page, as separate tabs and reuse the design from pro settings page. 

also instead of using transients, can we define a constant instead of setting the transient and in the `send_through_proxy` we will use that. the constant can be names  `FEEDZY_PROXY_URLS`

Let me know your thoughts.

**Comment by contactashish13** [comment]
@selul PRs: https://github.com/Codeinwp/feedzy-rss-feeds/pull/74 and https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/50
