### ISSUE TITLE
Feed Categories limit

### ISSUE THREAD

**Issue by purplecodes** [Codeinwp/feedzy-rss-feeds#742]
### Description

Displaying the number of feed categories when importing a post is limited to 100 only although you can create more than a hundred feed categories.

Kindly confirm if this is the desired behavior.

### Step-by-step reproduction instructions

1. Install and activate the Feedzy RSS plugin (free version).
2. Create a feed category by going to the **WordPress Dashboard** > **Feedzy** > **Feed Categories** > **Add new**.
3. Created 105 categories on my test instance. 
4.  Created an import task.
5. When you click the dropdown for **Use Feed Categories** option, it will only display the last 100 categories created.
In my test instance, only categories 6 - 105 are displayed.

<img width="1271" alt="Screenshot 2023-04-04 at 10 06 26 PM" src="https://user-images.githubusercontent.com/32997072/229819022-029deaaf-0947-4218-9e03-dbddef658886.png">

### Screenshots, screen recording, code snippet or Help Scout ticket

Please check this video for reference.

https://vertis.d.pr/v/XjxPvU

Ticket: https://secure.helpscout.net/conversation/2201095476/363962

**Comment by girishpanchal30** [comment]
Hey @purplecodes,

> Kindly confirm if this is the desired behavior.

Yes, we have displayed the latest `100` feed categories.
Ref: https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/admin/feedzy-rss-feeds-import.php#L303

Use the code snippet below to raise the limit if the user wants to show more categories.

```
function fz_increase_category_limit( $wp_query ) {
	global $pagenow;
	if ( ! is_admin() || 'post-new.php' !== $pagenow ) {
		return;
	}
	$post_type = $wp_query->get( 'post_type' );
	if ( 'feedzy_categories' === $post_type ) {
		$wp_query->set( 'posts_per_page', 999 );
	}
}
add_action( 'pre_get_posts', 'fz_increase_category_limit' );
```

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the snippet works as expected 🚀

**Comment by purplecodes** [comment]
@girishpanchal30 thanks for checking! I have tested the code and it now displays all the feed categories.
Will this be included in the next update?
If not, let me know so I can close this issue.

**Comment by vytisbulkevicius** [comment]
@purplecodes,

This code snippet doesn't require a release. We won't update the code in the plugin as 100 categories should be enough for almost all users, and this code can be used to cover those edge cases. We, of course need to document this @AndreeaCristinaRadacina Thanks!

**Comment by AndreeaCristinaRadacina** [comment]
Hi there!
Is there any way to use the feed category as feed source in Elementor Widget?

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina Yes, just add a category slug in the feed source textbox.
Ref: https://tinyurl.com/29g23gpb

**Comment by AndreeaCristinaRadacina** [comment]
I tried like this, but it doesn't seem to work:
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/86592992/230339838-435f5104-53e1-46c0-9163-1ea353889315.png">
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/86592992/230339968-d9c696c8-228b-4d65-9def-73376a4bf5a6.png">
This is why I thought it should be different.

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina 
I tested with [this feed](https://collider.com/feed/) and it seems working for me. I think it might issue with feed or server
Ref: https://tinyurl.com/2cueljjv

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 thank you for checking! I also checked with a different feed and it works as expected.

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Can we also have a filter to increase the number of import jobs, same user is saying that only 100 first imports are run, we have the code here - https://github.com/Codeinwp/feedzy-rss-feeds/blob/master/includes/admin/feedzy-rss-feeds-import.php#L1146

**Comment by girishpanchal30** [comment]
@vytisbulkevicius

```
function fz_increase_category_limit( $wp_query ) {
	$post_type = $wp_query->get( 'post_type' );
	if ( 'feedzy_imports' === $post_type ) {
		$wp_query->set( 'posts_per_page', 999 );
	}
}
add_action( 'pre_get_posts', 'fz_increase_category_limit' );
```

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 is it okay to have the same name as for the feed categories limit function?

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

You're right, you can't use the same name for the function so if you're using both of them name should be different. In documentation it's better to provide different name also to prevent this issue if user needs both of them.

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina

```
function fz_increase_feedzy_imports_limit( $wp_query ) {
	$post_type = $wp_query->get( 'post_type' );
	if ( 'feedzy_imports' === $post_type ) {
		$wp_query->set( 'posts_per_page', 999 );
	}
}
add_action( 'pre_get_posts', 'fz_increase_feedzy_imports_limit' );
```

**Comment by AndreeaCristinaRadacina** [comment]
Thank you both! I've added this in the docs.
