### ISSUE TITLE
Since last update duplicated items are imported and items are weirdly deleted (issues with featured image also)

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#743]
### Description

This has been reported by multiple clients, since the last update, there is an issue that duplicated items are get imported, also items get deleted randomly. Also, featured images missing in some cases.

I was able to kinda replicate this behavior using on of the client's examples.

I set up 3 import jobs each using a single feed:
1. https://hubu.de/tools/xml/?key=zTXWHPI19k7nu6D5PQW2F043XGNVN8gK&cat=sport
2. https://hubu.de/tools/xml/?key=zTXWHPI19k7nu6D5PQW2F043XGNVN8gK&cat=wirtschaft
3.  https://hubu.de/tools/xml/?key=zTXWHPI19k7nu6D5PQW2F043XGNVN8gK&cat=politik

Here is my screencast explaining the problem:
https://vertis.d.pr/v/ZliXi2

In my screencast you can see that each import imports only 1 item and deletes items from other imports. This is different behavior but also a big issue, but many clients reported duplicated items being imported.

Another client reported it this way with the latest update:

> My new website importing 10 blog articles at a time and all those are same article means it's not importing the feed correctly and even without images. When I delete all the imported post and run the import manually then it imports the correct posts with Images. Please fix the issue. We are having the same issue in all of our websites: royalcitizen.ca, blackandwhiteimmigration.com/ etc.

Another:

> My Feedzy seems to be acting p repeating imported posts and not showing featured image. I noticed this first in posts imported from https://eslov.se/nyheter/feed/ and am currently monitoring the site for possible issues with my three other feeds.

Another:

> Since the last update, I'm noticing that a few of my feeds will post the same item multiple times. When I check the feed, it shows the total number pulled in but the "found" "duplicates" and "imported" fields are all 0 (see enclosed screenshot).
> 
> If I click the "run now" button, it seems to fix it for a few hours but then the error happens again. When Feedzy posts duplicate items, the fields above are all 0. This only happens with certain feeds and it's always the same ones.

This one from free user - https://wordpress.org/support/topic/triple-or-double-imports/ (this might be not relevant as it's reported before latest release)

### Step-by-step reproduction instructions

1. Create multiple import jobs using different feeds.
2. Try to run them and see if you see items being imported correctly as posts
3. You should see some posts being imported some get deleted.

### Screenshots, screen recording, code snippet or Help Scout ticket

Screencast - https://vertis.d.pr/v/ZliXi2
Tickets:
https://secure.helpscout.net/conversation/2201120507/363966
https://secure.helpscout.net/conversation/2201857523/364068
https://secure.helpscout.net/conversation/2203822310/364407
https://secure.helpscout.net/conversation/2204326083/364496
https://secure.helpscout.net/conversation/2202757729/364227/
https://secure.helpscout.net/mailbox/dd8c59516d047fb2/chats/f0906ce8-33c7-4c98-99c8-c1a471a42a82 (info@motorhomescampervans.net)

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

This issue occurs when the feed item is missing the `item_url`, Now this issue is fixed with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/744

Please check and do let me know if you have any issues.

Thank

**Comment by MarinescuLucia** [comment]
+1 https://secure.helpscout.net/conversation/2206078324/364744/
