### ISSUE TITLE
Cron does not run all the imports automatically

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#749]
### Description

A few clients reported this recently that cron that runs each hour automatically doesn't trigger all the feeds.

I can replicate the same problem in my test instance:
<img width="1445" alt="image" src="https://user-images.githubusercontent.com/36594177/231602405-d257fd34-ff88-4bc4-9420-427a068bde53.png">

Here is a screencast where I also try to run the cron manually and same thing happens, 2 first imports are run and other two are not:
https://vertis.d.pr/v/tzb2TB (I'm using Crontrol plugin)

The test instance from my screencast will expire in 1 day but here are the credentials:
 Admin area URL: https://combativespot.s2-tastewp.com/wp-admin
 Username: bvytis  
 Password: nd3TVQPtdpk

### Step-by-step reproduction instructions

1. Create several import jobs
2. Try to wait for Feedzy cron to run or trigger Feedzy cron manually to see if all of them run succesfully

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2207473142/364989
https://secure.helpscout.net/conversation/2136450251/353690

### Environment info

https://pastebin.com/AYWUvnkk

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've reviewed this issue and it seems working for me.
Ref: https://tinyurl.com/2nc59vw2

I recommend you use a server real cron job instead of WordPress cron because of some time WordPress not working properly when a site has zero visits or any other resource issue.
Ref: https://www.thewayoftheweb.net/solve-wp-cron-job-errors-caused-by-wordpress-hosting/

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

Thank you for looking into it.

Have you changed anything in that example instance I shared?
I know about WP Cron but still, it was working before and in my screencast 2 out of 4 imports are triggered so it's weird that other 2 are not, I haven't faced such behavior before. Also, those 2 customers reported the same so that's why I suspect a problem.

**Comment by girishpanchal30** [comment]
@vytisbulkevicius

> Have you changed anything in that example instance I shared?

No

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/2202757729/364227

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

I still don't think this is a coincidence or issue with WP Cron as these are not new customers reporting the issue that some of the imports are not running.

Like the last example:
https://vertis.d.pr/i/YH93c6

There should have been a change in latest 2 releases that created this.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've checked this issue with my local and test instance and it seems working fine for me.
But I've added retry cron job option if incase import job failed.

But I've added a retry option in case failed the import job failed.

Please check with the attached PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/752

Thanks

**Comment by vytisbulkevicius** [comment]
Hey @girishpanchal30,

Thank you for checking this but I doubt this gonna help, based on the code change I see that it only triggers running the import again but thing is that import jobs are not triggered even if you manually run Feedzy cron (only some of them are triggered).

I even tried to add the code change on the same test instance I shared on another issue a few minutes ago but it doesn't seem to be helping.

Here are those credentials on this issue also:
https://ti-fantasy-lavu.instawp.xyz/wp-admin
cidecomapi6971
nN5ouBfC62QpYHrLJS7h

Feedzy imports:
https://ti-fantasy-lavu.instawp.xyz/wp-admin/edit.php?post_type=feedzy_imports
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/36594177/232765134-0e18e658-ee6f-4710-a6ab-9e0ee7772419.png">

You can run Feedzy cron manually - https://ti-fantasy-lavu.instawp.xyz/wp-admin/tools.php?page=crontrol_admin_manage_page&s=feedzy
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/36594177/232765310-83f25567-19bb-490d-b09b-690b877fc484.png">

And it only triggers the 1st import not the 2nd one.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

Can you please check with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/751?

Thanks

**Comment by irinelenache** [comment]
@vytisbulkevicius @girishpanchal30 I didn't manage to replicate the issue, i tried using multiple feeds and different cron schedules and it worked as expected for me, using InstaWP

**Comment by MarinescuLucia** [comment]
+1 https://wordpress.org/support/topic/only-the-first-3-feeds-are-imported/
