### ISSUE TITLE
Duplicate items are imported

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#750]
### Description

It's a continuation of the issue addressed here - https://github.com/Codeinwp/feedzy-rss-feeds/issues/743

Some users reported that the fix did not help in their cases.

I'm also able to replicate it now, I created two imports here:

 Admin area URL: https://bathemom.s3-tastewp.com/wp-admin
 Username: bvytis  Password: bZNKnlodqM8
 
 Running Feedzy Cron creates duplicate item in one of the imports.
 
 Here is a screencast: https://vertis.d.pr/v/CwRmzk
 
 Duplicates are imported but they don't appear in the Cumulative items of the import job.

### Step-by-step reproduction instructions

@girishpanchal30,

I tried to replicate it on a fresh instance and recorded the process here - https://vertis.d.pr/v/Yo35zW but it doesn't occur.
While the issue happens in the instance where I had the import configured for a few days and created a new import with different feed.

This issue started for clients with 4.2.2 release: https://github.com/Codeinwp/feedzy-rss-feeds/releases/tag/v4.2.2

Let me know what other details I can ask them to provide if that helps.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://secure.helpscout.net/conversation/2210499937/365466/
https://secure.helpscout.net/conversation/2203822310/364407

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/2208975598/365286/

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2213850958/365902/

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've tried to replicate this issue but I can't manage to reproduce the problem.

In this PR I've made some changes to fix this issue. please check with the build zip and let me know if you have any issues.

Thanks

**Comment by vytisbulkevicius** [comment]
+1 https://secure.helpscout.net/conversation/2211600843/365610/
Tried to add the fix manually on client's website to see if it fixes the issue.

**Comment by MarinescuLucia** [comment]
+1 https://secure.helpscout.net/conversation/2215725710/366267/

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

It still happens, unfortunately, even with that code change.

Do you have any other ideas?
I also have a test instance where it occurs (it's a test one so I can share it here):
https://ti-fantasy-lavu.instawp.xyz/wp-admin
cidecomapi6971
nN5ouBfC62QpYHrLJS7h

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius

I've reviewed the debug.log file and found the fatal error when triggering cron.
Ref: https://tinyurl.com/2clde4ku

Please check with the latest commit and do let me know if you have any issues.

Thanks

**Comment by irinelenache** [comment]
@vytisbulkevicius I tried to test with the feeds & settings you had in the mentioned test instance and it seems to work fine with the latest build. I set up the cron to run every 3 minutes and no duplicates were added. Anyway, i think we shouldn't move this to **Ready to merge** until the fix is confirmed on the users' websites 🙏

**Comment by poonam279** [comment]
+2 https://secure.helpscout.net/conversation/2224522971/367365/
https://secure.helpscout.net/conversation/2223938225/367311/

**Comment by RohanSharma2598** [comment]
+1 https://secure.helpscout.net/conversation/2211600843/365610

**Comment by MarinescuLucia** [comment]
+1 https://secure.helpscout.net/conversation/2224893266/367404/
