### ISSUE TITLE
summarylength parameter does not work for shortcode

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#753]
### Description

In Feedzy shortcode usage we have multiple parameters defined:
https://docs.themeisle.com/article/1130-how-to-use-feedzy-with-a-shortcode

One of them which is `summarylength` doesn't work anymore.

Example shortcode:
`[feedzy-rss feeds="https://www.baristamagazine.com/feed" summary="yes" summarylength="5″]`

So in this case summary should be only 5 characters but full summary is shown, no matter what is the length value.

"summary" parameter works and if you set it to "no" - summary is not shown at all.

### Step-by-step reproduction instructions

1. Use the shortcode provided above and try to control the length of the summary.

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/excerpt-in-shortcode/#post-16645213

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've checked with my local and it seems working fine for me, can you please share your test instance?
Ref: https://tinyurl.com/2b3wm96v

```
[feedzy-rss feeds="https://www.baristamagazine.com/feed" summary="yes" summarylength="5"]
```

Thanks
