### ISSUE TITLE
Missing thumbnails on feed to post for valid source

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/feedzy-rss-feeds#754]
### Description

Thumbnails are not added correctly to the imported posts for a source that works correctly in the Feedzy Gutenberg block.

### Step-by-step reproduction instructions

1. Create a import job with this source - https://www.burningshore.com/feed
2. Run the import; images will be missing.

![missing-img](https://user-images.githubusercontent.com/26867648/232798955-0ae71c06-4dc2-46c6-b5ea-083d867e0c78.png)

3. If you use the same source in the Gutenberg block, everything is fine
![Markup on 2023-04-18 at 16:53:09](https://user-images.githubusercontent.com/26867648/232799131-1e441907-4a2a-4dba-aa48-e3b3e0f51795.png)

### Screenshots, screen recording, code snippet or Help Scout ticket

https://wordpress.org/support/topic/featured-image-not-showing-103/

### Environment info

https://pastebin.com/qhrXM7sY

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

I've checked this issue and it's working fine for me.
Ref: https://tinyurl.com/2yu26t2c

It seems problem with the wp-content/uploads folder permission, can you please verify it here {{site_url}}/wp-admin/media-new.php?
Ref: https://tinyurl.com/2c52er9d

Thanks

**Comment by vytisbulkevicius** [comment]
I can't replicate this either @stefan-cotitosu.

Have you made your test on tastewp? There was a global issue with images on their server that was happening for a few days when no images of a website were loading, but even on tastewp it works fine now.

**Comment by stefan-cotitosu** [comment]
Yes, I tested on Tastewp. I'll try it on my instance too.

**Comment by stefan-cotitosu** [comment]
It happens on my instance but only with some of the images.

![feedzy-missing-images](https://user-images.githubusercontent.com/26867648/233342994-707e6beb-6737-40fe-86fa-1c5e05bebe8a.png)

I can access this URL when I'm logged in to the Dashboard http://feedzy.stefancoti.com/wp-admin/media-new.php

Site Health - https://pastebin.com/4EH15U0d

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/2219097061/366766?folderId=212385

**Comment by stefan-cotitosu** [comment]
Girish, feel free let me know what info I can share to help with the troubleshooting here. Thanks!

**Comment by vytisbulkevicius** [comment]
I'm closing this one as we identified why this is happening, there are some problems with the feed itself.
However, there is still issue with images not being created when cron runs the import, I will create a new issue for it.
