### ISSUE TITLE
Feeds categories not listed in Feedzy block when using FSE

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#759]
### Description

When using a FSE theme and the Feedzy block, you can't see and selected any categories ( there is an error in the console )

### Step-by-step reproduction instructions

1. Use a FSE theme
2. Make sure you have some categories created in Feedzy > Feed Categories
3. Click on Edit site 
4. Add the Feedzy block
5. Click on the dropdown arrow to view the current feed categories => the categories do not show up, and an error appears in the console

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/v/JbnbA3

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @rodica-andronache,

I've reviewed this issue and fixed it with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/760, please check and let me know if you have any issue.

Thanks
