### ISSUE TITLE
Feedzy is visible in the menu, for Editors, but can't be accessed

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/feedzy-rss-feeds#772]
### Description

Users that have the Editor role, can see Feedzy in the WP menu, but can't access it

### Step-by-step reproduction instructions

1. Log in with a user that has the **Editor** role
2. In the menu you will see **Feedzy** https://vertis.d.pr/i/cPQGgb
3. But when you try to access, it says you can't do it https://vertis.d.pr/i/oO3T67

I think it shouldn't be there at all.

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @rodica-andronache,

I've changed the feedzy top level menu capability `manage_options` to `publish_posts`. Now editor role user is able to access the admin page.

Also, I've added a new filter to change the capability.

```
add_filter(
	'feedzy_admin_menu_capability',
	function( $capability ) {
		return 'manage_options';
	}
);
```

Please check with the attached PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/773 and do let me know if you have any issues.

Thanks

**Comment by rodica-andronache** [comment]
@girishpanchal30 thanks! The same issue happens for the Contributor role ( the menu is visible, but can't be accessed ), it should probably be fixed in the same PR. Although I'm not sure, how it should be. If the options should be visible or not for that role.

**Comment by girishpanchal30** [comment]
@rodica-andronache Please add below filter code in your current active theme functions.php file to change the capability.

```
add_filter(
	'feedzy_admin_menu_capability',
	function( $capability ) {
		if ( current_user_can( 'contributor' ) ) {
			return 'edit_posts';
		}
		return $capability;
	}
);
```

**Comment by rodica-andronache** [comment]
@girishpanchal30 I'm not sure what you mean. Shouldn't this be part of the plugins code?

**Comment by girishpanchal30** [comment]
> Shouldn't this be part of the plugins code?

@rodica-andronache we have added new filter support for changing the admin menu page permission in our plugin and the user can change the admin menu page permission using the above mentioned filter.

I hope you understood

**Comment by rodica-andronache** [comment]
@girishpanchal30 but isn't this a bug, and it would have to be fixed in the plugin? as you did for the Editors?

**Comment by rodica-andronache** [comment]
@girishpanchal30 everything's working well 👍

**Comment by vytisbulkevicius** [comment]
@girishpanchal30 the filter provided above should still be working, right? Based on the code changes I think it should but when testing it doesn't work for me.

I think we can still have documentation that shows how to enable access for specific roles like contributor if user wants it, in such case they can use the filter mentioned on this thread:

```
add_filter(
	'feedzy_admin_menu_capability',
	function( $capability ) {
		if ( current_user_can( 'contributor' ) ) {
			return 'edit_posts';
		}
		return $capability;
	}
);
```

But when testing I can't get it working

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Above mentioned filter helps change the feedzy menu register capability. the provider is not changing the role permission.
If your role does not have such capability which is added in filter`edit_posts` then you should add role capability using WP_CLI/Code snippets or User Role Editor plugin.

I hope you understood.

Thanks
