### ISSUE TITLE
Order of items in a valid feed is not respected by the plugin

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/feedzy-rss-feeds#778]
### Description

A customer is using a valid source and some of the items available here have the exact same date and time. The problem is that the order of the feeds is not the same as in the source.

https://app.newsloth.com/aura-com/UlFTUlBU.rss

### Step-by-step reproduction instructions

1. Use the shortcode approach and compare the order with the source
2. Import the feeds with the [#item_content] magic tag and compare the order with the source

### Screenshots, screen recording, code snippet or Help Scout ticket

Reported here: https://secure.helpscout.net/conversation/2297363333/377057/

![Annotation-Annotation on 2023-07-11 at 17-24-21 png](https://github.com/Codeinwp/feedzy-rss-feeds/assets/26867648/0df6eff3-b7b6-4121-88dc-cf448b69310b)

![shortcode-approach-feeds-date](https://github.com/Codeinwp/feedzy-rss-feeds/assets/26867648/4d6f870c-3eb4-48fa-82cc-184719bac17a)

![import-feeds-order](https://github.com/Codeinwp/feedzy-rss-feeds/assets/26867648/2d9c2f3c-8033-4932-bf94-1764a8048bed)

### Environment info

https://pastebin.com/dmjSXLtu

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @stefan-cotitosu,

I've reviewed this issue and found the issue with the default Feedzy/SimplePie date ordering.

Add the below code snippet in your active theme functions.php to disable default ordering.

```
/**
 * Modify feed config.
 *
 * @param object $feed SimplePie object.
 * @return void
 */
function feedzy_modify_feed_config_callback( $feed ) {
	if ( ! $feed->order_by_date ) {
		return;
	}
	$feed->enable_order_by_date( false );
}
add_action( 'feedzy_modify_feed_config', 'feedzy_modify_feed_config_callback' );
```

It seems to order by feed item index once the code snippet was added.
Ref: https://tinyurl.com/2prkglxt

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and the code snippet works as expected 🚀

**Comment by stefan-cotitosu** [comment]
Yes, I can confirm that it worked on the customer website, too.

**Comment by AndreeaCristinaRadacina** [comment]
Hi there @girishpanchal30,

I have a question regarding the code snippet. 
Is it available for shortcode/widgets only? Or should it work for the feed to post too?

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina It's worked for all
