### ISSUE TITLE
[UIX] Minor friction challenges

### ISSUE THREAD

**Issue by mghenciu** [Codeinwp/feedzy-rss-feeds#779]
### What problem does this address?

While testing Feedzy, I think there are some small ares where we can do a better job on the details:

### Improve how the Confirmation Toast looks
Currently we use the Default WP toast, and even if this is recommended - in our case it's a bit strange because it moves and in a way brakes the layout (attached video):

https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/cdf1952c-7b41-4dc8-8501-9ee6f21d72f7

As a potential solution, I think we can use something similar to Spectra (also in the video above at the end) or how the toasts look in the editor:
![Screenshot 2023-07-13 at 18 20 05](https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/2844a1a1-c1d5-44e3-94fe-dc0d205e358d)

This way the toasts won't interfere  with the Feedzy layout.

___

### 2 Primary buttons in the same area
On the Settings page there are 2 Primary buttons in the same area + the Remove image button is visible all the time, even when there are no image added. From an UIX pov, this increases the cognitive load since more buttons look important.
![Screenshot 2023-07-13 at 18 27 14](https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/2d5cf689-add0-445e-9d92-398937de128e)

This could be a potential solution for this:

https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/c6cb274f-aa58-4f29-acfc-3e4b7fe5c89c

___
### Upgrade button opens in the current page
I think as a general rule, we open the upgrade links in a new tab. This doesn't happen in the current Feedzy build, which open the Admin Sidebar upgrade, in the same tab. This may be annoying for the users, since it takes them outside the wordpress context.
![Screenshot 2023-07-13 at 19 40 08](https://github.com/Codeinwp/feedzy-rss-feeds/assets/52494172/692b73f7-99c2-4ba3-ae70-5fe805970a9a)

___

### What is your proposed solution?

Added above.

### Will this feature require documentation? (Optional)

No.

**Comment by girishpanchal30** [comment]
Hey @mghenciu,

I've fixed the mentioned issue/improvement with this PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/781, please check with the attached PR zip, and do let me know if you have any issues.

Thanks

**Comment by mghenciu** [comment]
The changes look good 👏 
Thank you Irinel for testing & @girishpanchal30 for the implementation.
