### ISSUE TITLE
Performance issues related to the lazy endpoint

### ISSUE THREAD

**Issue by RohanSharma2598** [Codeinwp/feedzy-rss-feeds#782]
### Description

This is the Question from the customer that we are not sure how to approach or replicate so I am asking here:

`We've been working through some issues with our site with our host, and one of the things we noticed is the request /wp-json/feedzy/v1/lazy is getting a lot of requests on our site. It actually was the top one by far. We use feedzy pretty extensively throughout our site to pull in feeds from our news site, commonthread.antioch.edu, so we don't really want to navigate away from your plugin. Are there steps we can put in place to minimize uncached server requests in regards to feedzy? We are fine with not having real time feeds if we can cache it in some way. Thank you for any help you provide.`

![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/65424424/84dbd6d3-1709-46a1-ac60-092b77eb516f)

### Step-by-step reproduction instructions

N/A

### Screenshots, screen recording, code snippet or Help Scout ticket

Help Scout: https://secure.helpscout.net/conversation/2307431545/378418?folderId=212385

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

After reviewing this issue, I discovered that the lazy endpoint still calls even when the lazy feed has a valid cache.
Now I've made some changes to avoid lazy API calling if the feed has a valid cache.

Please check with the attached PR and do let me know if found any issues.

Thanks

**Comment by irinelenache** [comment]
@girishpanchal30 Tried to test the fix but i couldn't find the `data-has_valid_cache` attribute, let me know if i didn't correctly understand this

You can check here:
```
https://fz-lazy-issue.vertisite.cloud/new-shortcode/
User: hiwawizeya3073
Password: 04PlCA7u8FLEtMh6THx5
```

**Comment by girishpanchal30** [comment]
@irinelenache It seems issue with transient key and now it fixed with latest commit.

**Comment by irinelenache** [comment]
@girishpanchal30 Now it works fine, thank you 👍
