### ISSUE TITLE
Fatal error when creating a new post using WP versions lower than 5.8

### ISSUE THREAD

**Issue by irinelenache** [Codeinwp/feedzy-rss-feeds#786]
### Description

If Feedzy is installed and i'm using a WordPress version lower than 5.8, there will be a fatal error when creating a new post/page https://vertis.d.pr/i/eJtp4i . On wp.org the minimum WordPress version for Feedzy is [3.7](https://vertis.d.pr/i/ozqBEF) which is pretty old so i think we should change it accordingly

### Step-by-step reproduction instructions

1. Install WordPress 5.7 or lower and Feedzy
2. Try to create a new post/page

### Screenshots, screen recording, code snippet or Help Scout ticket

https://vertis.d.pr/i/eJtp4i

### Environment info

Wordpress 5.7 or lower, PHP 7.4, Feedzy 4.2.8

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
@irinelenache I've reviewed this issue and fixed it with the attached PR https://github.com/Codeinwp/feedzy-rss-feeds/pull/787

**Comment by rodica-andronache** [comment]
@girishpanchal30 everything's working well 👍 As Irinel suggested, I think you can also update Requires at least to 5.7 in the readme file

**Comment by girishpanchal30** [comment]
@rodica-andronache Done!
