### ISSUE TITLE
google news smart max 

### ISSUE THREAD

**Issue by selul** [Codeinwp/feedzy-rss-feeds#79]
when using feeds from google news, and the user is using the max attribute within the shortcode which is greater than the num query argument of the news feed, the feed is still limited to the num query arg, 

E.g [feedzy-rss feeds="http://news.google.com/news?hl=en&gl=us&q=Tourette&num=20&um=1&ie=UTF-8&output=rss" max="30" target="_blank" refresh="1_hours" title="120" meta="yes" summary="yes" summarylength="275" size="160"]

because num=20 the max=30 is ignored as we dont have more than 20 items in the feed.

We should do a smart feed convert, which alter the num query arg if the google news feed is used.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/111

**Comment by selul** [comment]
@contactashish13 i'm getting this -> http://prntscr.com/in18mj 

Also, please make a php unit test which should cover this.

**Comment by contactashish13** [comment]
@selul have fixed that and also added a test case. PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/114

The build is partially failing. I guess this is because google is restricting the hits on its feed. Can you please check?

**Comment by contactashish13** [comment]
@selul thanks, you are right about that logic.

the test cases are still failing but they pass at my end.

**Comment by selul** [comment]
@contactashish13 i have removed the unparse function as it redundant now.

**Comment by selul** [comment]
@contactashish13 i've added this check 
```
$check_travis = getenv( 'TRAVIS' );
if ( boolval( $check_travis ) ) {
	return;
}
```
To remove the test on Travis but keep using it on the local environment. It seems, indeed a Travis issue.
