### ISSUE TITLE
Cypress tests failing

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#798]
### Description

@girishpanchal30 we have Cypress tests failing, for example - https://github.com/Codeinwp/feedzy-rss-feeds/actions/runs/6294733971/job/17086992313#step:8:91

We had this issue on another products, for example here - https://github.com/Codeinwp/templates-patterns-collection/issues/282

Also here - https://github.com/Codeinwp/optimole-wp/issues/674

So it caused some issues with releases on other products that's why we need to make sure we get it fixed. The solution requires upgrade for cypress.

### Step-by-step reproduction instructions

Running job like - https://github.com/Codeinwp/feedzy-rss-feeds/actions/runs/6294733971/job/17086992313#step:8:91

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius,

I've reviewed the cypress issue and fixed it with the below PR, please check and merge it into the development branch

Free - #799
Pro - https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/607

Thanks

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30 both ar merged but I see this one failing the test - https://github.com/Codeinwp/feedzy-rss-feeds/actions/runs/6348551905

**Comment by girishpanchal30** [comment]
@vytisbulkevicius Fixed, Please merge this PR - https://github.com/Codeinwp/feedzy-rss-feeds/pull/800
