### ISSUE TITLE
Space character trimmed in Feed Categories

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/feedzy-rss-feeds#807]
### Description

The following source works properly in the import job and Feedzy Gutenberg block, however, it's trimmed in the Feed Catgeories.

```
https://blogger-developers.googleblog.com/feeds/posts/default/-/Blogger%20Developers?alt=rss
```

The character `%20` is removed from the URL, making the source unsable.

### Step-by-step reproduction instructions

1. Create a Feed Category
2. Use the above URL
3. Save it and edit the category again
4. You will notice the URL being changed from

This doesn't happen in the import job.

```
https://blogger-developers.googleblog.com/feeds/posts/default/-/Blogger%20Developers?alt=rss
```

```
https://blogger-developers.googleblog.com/feeds/posts/default/-/BloggerDevelopers?alt=rss
```

### Screenshots, screen recording, code snippet or Help Scout ticket

![trim-ch](https://github.com/Codeinwp/feedzy-rss-feeds/assets/26867648/6f095be8-891b-4fed-b755-045262dbdb07)

![trim-ch-2](https://github.com/Codeinwp/feedzy-rss-feeds/assets/26867648/e00b49f9-9c08-4939-8f84-f0a09811abbb)

Reported here: https://wordpress.org/support/topic/issues-if-there-is-a-space-character-in-the-feed-url/#post-17132534

### Environment info

https://pastebin.com/hMThcDuK

### Is the issue you are reporting a regression

No

**Comment by irinelenache** [comment]
@girishpanchal30 Tested and this issue is fixed, thank you 👍
