### ISSUE TITLE
Ability to customize the [#item_url] tag

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#813]
### What problem does this address?

Right now, we have the [#item_url] tag that adds a personalized "Read More" link. However, the site admin has no control over the link. 

### What is your proposed solution?

Implement actions modal with some basic actions:

- [ ] link text - write something else instead of Read More
- [ ] opening behavior - in a new tab/same tab
- [ ] link type - follow/nofollow link
- [ ] tracking parameters/UTMs

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2451815076/396690?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2643715617/424596?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/magic-tag-behavior/

**Comment by vytisbulkevicius** [comment]
I think having an action for this is too complicated because we have same actions for all tags and creating new actions just for [#item_url] is too much but I would like to have a filter for this that would allow manipulating data.

@girishpanchal30, do you think we can create such a filter? Something like you suggested for custom tags in the past:
https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/447#issuecomment-1014334516

**Comment by girishpanchal30** [comment]
> @girishpanchal30, do you think we can create such a filter? Something like you suggested for custom tags in the past:

@vytisbulkevicius Yes, It's better to create a new filter rather than a new action for `item_url`.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 amazing!

Everything works well, apart from the link type (rel). I set it to nofollow, but it appears as noopener:

<img width="1680" alt="image" src="https://github.com/user-attachments/assets/023dc0ef-93d1-4bfe-bf92-23b67ab8b8d7">
<img width="827" alt="image" src="https://github.com/user-attachments/assets/db0e21a0-a29a-4f73-9048-434c7e6667e1">

Should I apply other settings for this to work?

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I think it depends on the `_target` value.
Ref: https://wpshout.com/noopener/#gref:~:text=When%20checked%2C%20WordPress%20inserts%20target%3D%22%20_blank%22%20in%20the%20code%2C%20which%20prompts%20the%20browser%20to%20open%20the%20link%20in%20a%20new%20tab.%20As%20a%20bonus%2C%20the%20rel%3D%22noopener%22%20value%20also%20ends%20up%20in%20the%20code%20to%20protect%20from%20security%20threats.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 I also checked a similar guide before, but it's the same when I use _self and 'nofollow'.

Is it something we can control?

**Comment by AndreeaCristinaRadacina** [comment]
I also removed this line: 		$item_link_data['attr']['rel'] = 'nofollow'; // noopener, nofollow.
And the rel attribute remains there, so it's like the above line is not considered at all

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

I tried to play around and I also can't change it with the filter, its something WordPress doesn't want to allow manipulating for security reasons, another thread about it: https://wordpress.com/forums/topic/remove-relnoopener-wtf/


What worked for me and maybe we can recommend those clients who ask for it is using this one and manipulating DOM (it works without re-doing the import):
```
add_filter('the_content', 'ensure_rel_attribute', 20);

function ensure_rel_attribute($content) {
    // Use DOMDocument to ensure 'rel' attribute is set correctly
    $dom = new DOMDocument();
    libxml_use_internal_errors(true);
    $dom->loadHTML('<?xml encoding="utf-8" ?>' . $content);
    libxml_clear_errors();

    $links = $dom->getElementsByTagName('a');

    foreach ($links as $link) {
        if ($link->getAttribute('class') === 'feedzy-rss-link-icon') {
            $rel = $link->getAttribute('rel');
                $link->setAttribute('rel', 'nofollow');
        }
    }

    return $dom->saveHTML();
}

```

I look with it for feedzy-rss-link-icon class which that Read More button has and then change the rel attributes value to nofollow in this case.

@girishpanchal30 what do you think about this approach, any big cons recommending it if someone needs?

**Comment by girishpanchal30** [comment]
@vytisbulkevicius @AndreeaCristinaRadacina I've removed the default WP link rel if found in our filter.

Here: https://github.com/Codeinwp/feedzy-rss-feeds/pull/963/commits/37e3e0d8ec8be67b1dfbdc02c347c294d125b8ac

Please check with the latest build zip.

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 Thank you!

Now, when I use the filter and declare a rel type, nothing is displayed:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/125db70a-a690-4af5-a702-55ee71eb6040">

If I comment that line, the default noopener is displayed:
<img width="1680" alt="image" src="https://github.com/user-attachments/assets/a206af76-e0a0-46b2-8396-84e3a2f12162">
<img width="901" alt="image" src="https://github.com/user-attachments/assets/c65b86fa-c53e-459e-b904-76e233712a68">

Do you have any suggestions? Should I use this in combination with Vytis' code, or should it have worked as a standalone solution?

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina

> Do you have any suggestions? Should I use this in combination with Vytis' code, or should it have worked as a standalone solution?

It should work standalone

I've pushed new changes in PR, Can you please recheck with the latest build zip?

Thanks

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 Great, it works now!

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2655505582/426945?viewId=212385
