### ISSUE TITLE
Loading HTTP images over HTTPS

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#83]
So the plugin, for obvious reasons, can't load HTTP images on a HTTPS website, and that's not plugin's fault. But I have a workaround for this and maybe we can add that to the plugin?

If the site is running on HTTPS and someone tries to fetch a feed which is over HTTP, can we pull the images and display it using a CDN over HTTPS?

@selul @ineagu

**Comment by selul** [comment]
i dont think we can afford to offer a cdn inside a free plugin.

**Comment by HardeepAsrani** [comment]
Can't we use a free CDN?

On Nov 24, 2017 19:17, "Marius Cristea" <notifications@github.com> wrote:

i dont think we can afford to offer a cdn inside a free plugin.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Codeinwp/feedzy-rss-feeds/issues/83#issuecomment-346832277>,
or mute the thread

**Comment by ineagu** [comment]
Makes no sense, the user can use feed to post and import those completely :)

**Comment by HardeepAsrani** [comment]
Ignore this, I was too much sleepy when I thought about this. 😜
