### ISSUE TITLE
(Feed2Post) Timezone/Timestamp offset for imported RSS Feed items

### ISSUE THREAD

**Issue by m-vdv** [Codeinwp/feedzy-rss-feeds#832]
### What problem does this address?

Currently the Feedzy "Import Posts" functionality uses the feed items date and time < pubDate > when Post Date is mapped to [#item_date] under Map content. 
Unfortunately this date and time seems to always be (converted to) UTC timezone. 
Resulting in this UTC date and time being used to create the post in WordPress.
This is not always correct.

### What is your proposed solution?

Please add an option for us to manually offset [#item_date], so we can easily fix timezone related issues.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by DanBtt** [comment]
Yep I'm getting this exact problem. The values in the database just aren't correct. I tried setting the gmt_offset value  in the code for my timezone as I saw there was some code that used that in feedzy but this didn't work either. This is bug really in my view.

**Comment by dangehub** [comment]
+1!
the same problem bothers me. I have spent three days troubleshooting the problem and finally determined that it is a plug-in problem.
