### ISSUE TITLE
(Feed2Post) Change Import Posts frequency (Run importer more than once an hour)

### ISSUE THREAD

**Issue by m-vdv** [Codeinwp/feedzy-rss-feeds#833]
### What problem does this address?

Currently the Import Posts functionality imports new feed items only once an hour (hourly).

The setting under Feedzy > Settings only impacts the Shortcode base RSS Feeds, not the Feed2Post import runs.

### What is your proposed solution?

Please allow us to change the import frequency to different cron job times.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by vytisbulkevicius** [comment]
Hi @m-vdv,

Thank you for posting your suggestion.
Such a feature is already available but it is available with Feedzy PRO version, here is our documentation:
https://docs.themeisle.com/article/1820-how-to-set-scheduler-for-import-cron-jobs-in-feedzy

Let us know if it doesn't work for you, thanks!

**Comment by m-vdv** [comment]
Hi @vytisbulkevicius 

Thanks! Following the [documentation](https://docs.themeisle.com/article/1820-how-to-set-scheduler-for-import-cron-jobs-in-feedzy) you've provided, it now works. I googled, but couldn't find that article.

I've added a new cron interval using a Feedzy filter.
Then I select the newly created schedule from the dropdown under Feedzy > Settings > Schedule.
**Important:** I also had to set a date (in the past) for "First cron execution time". Leaving it empty did not work!

Please update the info text on the Settings page:
**First cron execution time**
When past date will be provided ~~or left empty~~, event will be executed in the next queue.

General tips: 
- Add more links to the documentation where relevant.
- Make it clearer which settings relate to Feed2Post or the Feedzy shortcodes.
