### ISSUE TITLE
Separate settings in General section to prevent confusion

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#836]
### What problem does this address?

From the feedback provided here - https://github.com/Codeinwp/feedzy-rss-feeds/issues/828 it was not clear for Andreea if features are connected and I can relate to this so I think we can make a small adjustment here to make it more clear.

Currently it looks like this:
<img width="1202" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/eef00e4f-455d-4de2-9a50-7abf6910f5c6">

I suggest separating first 2 options, adding this helper text:

> This setting controls whether there are featured images available in the RSS XML Feed of your own website.

And changing helper text below the featured image from:

> ~~This image will be used for the Feed Items that don't have one.~~

to:

> This image will be used for the **imported posts** if an image is not available in the source XML Feed.

And adding form label at the top of the fallback image:

> **Fallback image for imported posts**

Final result:
<img width="1132" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/6d145db3-22ae-4259-b651-8d2495cf2d51">

### Will this feature require documentation? (Optional)

None

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius

I have implemented suggested functionality, Please review with build zip.

Thanks.

**Comment by vytisbulkevicius** [comment]
Hi @girishpanchal30,

I checked the build zip on 2 different instances and I get the same view:
<img width="1244" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/9bcebca9-3732-4412-8424-f8b18ef47b03">


Please check it, thanks.

**Comment by girishpanchal30** [comment]
Hey @vytisbulkevicius

I have fixed PHP warning, Please review with new build zip.

Thanks
