### ISSUE TITLE
Only first <img> in article is scraped

### ISSUE THREAD

**Issue by MS-potilas** [Codeinwp/feedzy-rss-feeds#84]
Function feedzy_return_image (in feedzy-rss-feeds-admin-abstract.php) scrapes only the first `<img>`, and if it is blacklisted, no image is returned. To fix this change this code:

        preg_match( $pattern, $img, $matches );
        if ( isset( $matches[0] ) ) {
            $blacklistCount = 0;
            foreach ( $matches as $matche ) {
                $link      = $this->feedzy_scrape_image( $matche );
to

        preg_match_all( $pattern, $img, $matches );
        if ( isset( $matches[0] ) ) {
            foreach ( $matches[0] as $matche ) {
                $blacklistCount = 0;
                $link      = $this->feedzy_scrape_image( $matche );

This goes through every `<img>` and returns first that is not blacklisted.

**Comment by selul** [comment]
@MS-potilas thanks for your input, we will clearly include this. 

@contactashish13 can you please check also, and if is fine to send a PR with it.

**Comment by contactashish13** [comment]
@selul PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/85
