### ISSUE TITLE
[#item_full_content] displays a smaller version of the YouTube video

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#841]
While working on a ticket, I noticed that the outcome of a YouTube feed import is different for the item's full content. More exactly, the video player is smaller than the for item's content.

I am not sure if it's a bug or it's expected:

<img width="1680" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/07a41e3c-6213-4d81-8322-97d6df09acc9">
<img width="1680" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/8d127e64-067b-4e02-9aad-1a8275a90426">

Ref: https://secure.helpscout.net/conversation/2450796455/396595?viewId=212385

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina, is there any use case where using [#item_full_content] for Youtube feed is needed? 
It gets the same video, there is no other content to retrieve from the URL itself so I don't see any need using it at all but if there is a use case you have in mind we can check why this occurs.

**Comment by AndreeaCristinaRadacina** [comment]
@vytisbulkevicius I also consider it's okay to use the [#item_content] instead of full content, but I thought is good to know there is an issue in such cases.

I noticed that Feedzy also retrieves "Post Content" when we use [#item_content].

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina, I see it happens IF there is no text content, in Youtube Feed case there is only video that gets imported so "Post Content" is imported to each post before the video. 
I created a new issue toa address that bug.
