### ISSUE TITLE
Move updated post at the top

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#854]
### What problem does this address?

A user asked about the possibility of highlighting better when a post imported by Feedzy is updated.

He also set up a connection to send emails when new posts are uploaded.

ref: https://wordpress.org/support/topic/how-to-get-wordpress-to-send-out-a-new-post-email/

### What is your proposed solution?

When the cache period is done, new posts are imported, and old posts are updated if needed; treat updated posts as new posts (move them to the top of the page).

In this way, the emails will also be sent.

Maybe it can be added as a toggle inside the settings area under the cache period.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

I'm trying to understand this better, is there a ticket you can share to see the conversation?

I'm confused by this statement:

> When the cache period is done, new posts are imported, and old posts are updated if needed; treat updated posts as new posts (move them to the top of the page).

We don't have some caching for imports, the import is run periodically and it checks URLs of the import job for new items available, we don't update already imported items.

**Comment by vytisbulkevicius** [comment]
Thanks @AndreeaCristinaRadacina,

I checked the thread and I think user is using the block/shortcode method, not import of posts, that's why he was mentioning cache. I replied there and will be looking for his answer to see if my understanding is correct.
