### ISSUE TITLE
Doesn't work with Site Origin Page Builder

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#86]
If you use the Site Origin's Page Builder, the shortcode button doesn't work. It opens a modal with tags and doens't let you do anything. @selul

**Comment by selul** [comment]
@contactashish13 can you have a look.

**Comment by contactashish13** [comment]
@HardeepAsrani It appears to be a problem with WP 4.9+ only and it does not show a blank modal but loads the dashboard into the modal. More information such as WP version and possibly a screenshot will certainly be more useful in the future :)

@selul PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/88
