### ISSUE TITLE
Audio files not working

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#860]
### Description

A user reported that the audio files from the feed he's using don't work anymore.

I managed to replicate this on my website.
ref: https://secure.helpscout.net/conversation/2484545761/401020?viewId=212385

### Step-by-step reproduction instructions

1. Create a new Feedzy import using this feed: https://video-api.wsj.com/podcast/rss/wsj/whats-news
2. Paste this in the content field: <audio controls><source src="[#item_custom_enclosure@url]" type="audio/mpeg"></audio>
3. Follow the rest of the instructions if needed - https://docs.themeisle.com/article/1682-how-to-import-embedded-audios-to-posts

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="827" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/02167cc8-cd38-4294-a502-2eac87929794">

### Is the issue you are reporting a regression

No

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina,

I've checked and found the `<link>` tag is missing in each feed item. so it will not extract the custom values.
We have used `<link>` tag for a unique identity for each item.

You can compare it with our example feed in the docs.
Ref: http://tinyurl.com/ylk42wcm

cc @vytisbulkevicius

Thanks

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30 thank you for the clarifications! So this means it happens because of the feed, right? And we need another source?

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina

> So this means it happens because of the feed, right?

Yes

> And we need another source?

No, the user who reported the issue needs to include a <link> tag in the feed or maybe notify the feed owner.

**Comment by AndreeaCristinaRadacina** [comment]
Thank you!
