### ISSUE TITLE
Feedzy posts - link the title to the original article - does not work at times

### ISSUE THREAD

**Issue by tio-trom** [Codeinwp/feedzy-rss-feeds#876]
### Description

I am using the "Feedzy posts - link the title to the original article" plugin too, like recommended in your Docs, and it all works well except when it does not. See this page https://tromnews.com/news/ - the news "Shedding: COVID-19 antivax quacks never give up pushing it" and "COVID-19 antivax quacks are now “repurposing” ivermectin for cancer" both link to the post on our website instead of the original source.

Both of these sources seem to be like that regardless of the posts it pulls from them.

They are https://sciencebasedmedicine.org/feed and https://www.respectfulinsolence.com/feed

### Step-by-step reproduction instructions

As described above, add those sources and the  "Feedzy posts - link the title to the original article" plugin  - the posts created from those sources do not link to the original post via the Title of the post.

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Hi @tio-trom,

Thank you for using Feedzy and reporting the issue you're facing.
I tried to replicate the issue, installed Feedzy and the custom code with a plugin that we recommend in docs and imported items as posts, they are visible on the fresh website (homepage) here - https://endurablefront.s1-tastewp.com/

The mentioned article points to the original source, not my website:
<img width="1360" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/13e225df-b68b-4582-b6f2-16fbab054b11">

Do you have any recommendations of how to replicate the issue that you have on your website? Any other customizations that you made?

**Comment by tio-trom** [comment]
Interesting... I have no clue why it does not work on my end. Those feeds are part of a group of feeds, and the vast majority of them work. So same settings for multiple feeds, but only a selected few do not work.

With the same feeds I have observed that if I run the process of updating the feeds manually via RUN NOW it seems to work ok. But if the feeds are imported via the cron we are faced with the above issue.

I could give Feedzy devs temporary admin access to my website or tell me how I can debug this.
