### ISSUE TITLE
Some feeds appear as invalid in Feedzy while they are valid

### ISSUE THREAD

**Issue by vytisbulkevicius** [Codeinwp/feedzy-rss-feeds#880]
### Description

These feeds show up as invalid if you try to save them in Feedzy import:
https://www.osha.gov/laws-regs/federalregisters.xml
https://www.usnews.com/rss/the-report

<img width="686" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/80348054-8601-4d28-b019-dddf6c8c7e5b">

These feeds are valid from what I see, they can be checked on SimplePie as well:
https://simplepie.org/demo/?feed=https%3A%2F%2Fwww.usnews.com%2Frss%2Fthe-report
https://simplepie.org/demo/?feed=https%3A%2F%2Fwww.osha.gov%2Flaws-regs%2Ffederalregisters.xml

### Step-by-step reproduction instructions

1. Try to create a new import and use the feeds I shared above.

### Is the issue you are reporting a regression

No

**Comment by tio-trom** [comment]
I have reported it here https://wordpress.org/support/topic/this-source-has-invalid-urls/#post-17399998 about similar issues for me.

The following fail for me:

    https://www.tromjaro.com/category/apps/feed
    https://forum.tromjaro.com/c/releases.rss
    https://privacyinternational.org/rss.xml
    https://newsrss.bbc.co.uk/rss/newsonline_uk_edition/sci/tech/rss.xml
    https://www.directory.trade-free.org/category/goods-services/feed
    https://www.tiotrom.com/feed

![2024-02-05_22-35](https://github.com/Codeinwp/feedzy-rss-feeds/assets/38043315/bd5659a2-0413-4832-813c-bc547867b781)

**Comment by vytisbulkevicius** [comment]
Thank you for the investigation @Soare-Robert-Daniel.

I see other plugins don't have a more specific error message but it would make sense to modify the message.

In **New Import**:

From:
> This source has invalid URLs. Please correct/remove the following:

To:

> This source has invalid or unreachable by WordPress SimplePie URLs. Please correct/remove the following:

In **block usage**:

From:
> Feed URL is invalid. Invalid feeds will NOT display items.

To:

> Feed URL is invalid or unreachable by WordPress SimplePie and will NOT display items.

When **creating a category:**

From:

> We found the following invalid URLs that we have removed from the list: 

To:

> We found the following invalid or unreachable by WordPress SimplePie URLs that we have removed from the list: 

IMO, it's irritating when you try to save it and only get information that the feed is invalid while you know it's valid.

**Comment by AndreeaCristinaRadacina** [comment]
This issue is happening again on a user's website.

He is using this feed - https://carbuzz.com/feed/, which is valid - https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fcarbuzz.com%2Ffeed%2F

However, he gets these errors - 
<img width="1551" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/eb2aa6ed-da80-423b-ae3c-86b420db4348">
<img width="1680" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/7d067b7d-e8df-4d4d-87a8-177b00f00952">

ref: https://secure.helpscout.net/conversation/2566862890/413423?viewId=212385
