### ISSUE TITLE
Not able to use URL or other tags inside the featured image area

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#893]
### Description

A user reported that the featured image field doesn't allow for text to be added, even if the description mentions it as being possible.

ref: https://secure.helpscout.net/conversation/2517784921/405546?viewId=212385

### Step-by-step reproduction instructions

1. Go to Feedzy > Imports
2. Create a new import
3. Go to the featured image area and try to type in something

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1389" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/b99e096a-43da-4ffe-9ad3-74fb7f180cbc">

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
This was introduced with version - 4.4.0 where we added actions for tags.

We should fix this to allow typing tags there or adding URL as before.

**Comment by stefan-cotitosu** [comment]
I've tested the zip file available [here](https://github.com/Codeinwp/feedzy-rss-feeds/pull/894#issuecomment-1964393471) alongside the latest version of Feedzy Pro, and I'm not able to type in the field where the featured image magic tag is.

**Comment by vytisbulkevicius** [comment]
I'm able to add tags and type text but I'm experiencing a different problem, even if I add some image URL and I don't add image tag, like this:

<img width="1283" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/b8847acd-3ab7-48a0-987a-81046a2ea69e">

I still get images taken from the feed or if there is no image found item is imported without an image. So it looks like we can type now as expected but we don't really check what's added there @Soare-Robert-Daniel

**Comment by Soare-Robert-Daniel** [comment]
@stefan-cotitosu, the tying inside the featured component works for me. Also, I send you a test instance to check. Also, please post further issues inside the PR so that the problems can be associated with the solution from PR.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/unable-to-click-field/

**Comment by stefan-cotitosu** [comment]
+1 https://secure.helpscout.net/conversation/2545926746/410519?viewId=212385
