### ISSUE TITLE
Data left after uninstall?

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/feedzy-rss-feeds#90]
@selul 

This is not a confirmed bug, however, I wanted to ask if we need to remove the plugin data while plugin deletion.

Reference: https://wordpress.org/support/topic/data-left-after-uninstall/

I deleted the plugin from my local and it kept all the data such as feed category and all. 

Please close if we are not removing plugin data intentionally.

**Comment by selul** [comment]
yep, is not that easy to delete all shortcodes references from each post/post_meta, maybe an easy way/fix will be to add a blank feedzy plugin fix which will create the shortcode and return empty, in order to fix their issues. 
i will think about it.

**Comment by HardeepAsrani** [comment]
@selul I think this is about removing data of Feed category from database and not the shortcode.

**Comment by contactashish13** [comment]
@Vishakha-Patel can you please confirm what this issue is about? is this about data being left behind in each post meta or something else?

**Comment by Vishakha-Patel** [comment]
@contactashish13 It is about both posts, post meta and other plugin options such as categories, feeds(import feed settings), etc... 

This is the user message where he mentions about tables he saw Feedzy reference:

>  I just deactivated and uninstalled FEEDZY RSS Feeds Lite.
> It´s been working really great but since we are doing something really basic now we decided to use the core WordPress rss widget instead.
> 
> However after a dry run search and replace for “feedzy” I see that there are lots of references left (141 cells for wp_options, wp_postmeta, wp_posts and wp_usermeta).
> 
> Is that normal?

The solution that I see is to remove at least plugin options and other data(categories, feeds, etc...) other than posts. Because there are some difficulties as Marius said for posts.

**Comment by contactashish13** [comment]
PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/164 and https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/132
