### ISSUE TITLE
Author displayed correctly on dashboard but not while editing the page

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#900]
### Description

A user reported that the original author is not correctly displayed in the backend. It appears correctly on the blog page, but when you try to edit a post, it displays the default admin name.

I was able to replicate this.

ref: https://secure.helpscout.net/conversation/2524868800/406380?viewId=212385

### Step-by-step reproduction instructions

1. Go to Feedzy > Imports
2. Create a new import
3. In the Map Content > Advanced Settings tab, enable both options for the Post Author (backend and frontend)
4. Save everything
5. Check the posts in Dashboard > Posts (you'll see the correct one)
6. Open one of the posts

### Screenshots, screen recording, code snippet or Help Scout ticket

Not correct when you edit a page:
<img width="1678" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/43be295e-ea0d-4985-8dee-474224a04799">

Not correct when you click on Quick Edit:
<img width="1468" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/fa062bcd-b19b-4cc8-87f1-a708cd1ef840">

Correct on the posts area:
<img width="1538" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/f68355d1-203f-4ee9-9fa7-43f6818418a6">

### Is the issue you are reporting a regression

No

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2530708377/407407?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
Hey @vytisbulkevicius,

I am using Neve, and I still encounter this issue. The author is correctly displayed on the post and in the Dashboard; however, if you manually try to edit the post, the admin is displayed as the author.

This also happens for both the first and second tickets. For the second one, I asked him to display the author in the post title, which is correctly displayed there. So, the main problem is that the original author doesn't appear while editing the post.

I will make some tests for the second one to see why it doesn't appear on the single post. However, I still believe the main problem is with the author who appears while editing the post.

**Comment by vytisbulkevicius** [comment]
Yes, that's what I'm saying @AndreeaCristinaRadacina that we hook into display on dashboard (where posts are displayed) and front-end BUT if you edit the post, you see the real author as a WordPress user is visible there, as far as I remember it was working like this.

**Comment by AndreeaCristinaRadacina** [comment]
Okay then, thank you for the clarification! 

Feel free to close the issue.
