### ISSUE TITLE
Layout Conflict with Genesis Blocks in magic tag actions 

### ISSUE THREAD

**Issue by stefan-cotitosu** [Codeinwp/feedzy-rss-feeds#901]
### Description

When Feedzy and Genesis Blocks plugins are both active, the layout of Feedzy options for the magic tags in the import job are displayed mirrored.

### Step-by-step reproduction instructions

1. Install & Activate Feedzy 
2. Install & Activate [Genesis Blocks](https://wordpress.org/plugins/genesis-blocks/)
3. Navigate to the Feedzy import job and check the options in Step 3

 

### Screenshots, screen recording, code snippet or Help Scout ticket

![feedzy-conflict-with-genesis-blocks](https://github.com/Codeinwp/feedzy-rss-feeds/assets/26867648/5c20fca3-e87c-432b-8172-1c057b65b871)

Found it while troubleshooting something, it wasn't reported by a customer.

### Environment info

https://pastebin.com/2WM7JH4A

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
@Soare-Robert-Daniel, I think this is a quick (tiny) CSS fix for us so let's work on it. If for some case there is more work let me know
