### ISSUE TITLE
Date is not conserved when publishing drafts

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#916]
A user reported that the date is not conserved after publishing when he creates imports with Drafts.

ref: https://wordpress.org/support/topic/draft-post-publication-date-reset-to-current-date-on-post-edit/

Replication steps:
1. Create a new import 
2. Set the post status to Draft
3. Save the import and go to the posts; you will see the item date
<img width="1513" alt="Screenshot 2024-04-05 at 18 58 17" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/826d74a9-173b-4f79-9708-d46e03d917fa">
4. If you open a post, its date will turn to Immediately, and the original date will appear when hovering
<img width="1506" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/c4e2aedc-34f7-473f-a280-a5af3a216afb">
5. When you publish, the post's date will become the current date and time; it will not inherit the original item date.
<img width="1526" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/5c24980c-ee57-450b-a9ac-db3259e49203">

The user mentioned that this had worked in the past; I rolled back to version 4.3.5, and the same behavior occurred.

Is this expected?

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius I will remove as it's not an issue. If you draft any post on any past date, the Block Editor will always show Immediately as Publish time.

This makes sense as the Post Date there is the date of the draft. The publish date is when you click on the Publish button. And the user can change the date to past when they publish it.

**Comment by vytisbulkevicius** [comment]
@HardeepAsrani got it.
The logic makes sense but for Feedzy uses cases it also make sense to keep the original date and then be able to modify something (that's why you want to save them as Draft) and only then publish after changes are made but with original date.

However, I only see this as a nice to have, it it's more complicated to have it I wouldn't bother either.

**Comment by HardeepAsrani** [comment]
@vytisbulkevicius We can close this?

**Comment by vytisbulkevicius** [comment]
Yes, I removed from the milestone but thought to keep in the backlog if more users in the future report something like they would like to be able to save the original date and use it as published date later. But we can close and reopen if there is such a need.
