### ISSUE TITLE
Some images are not set as featured when % is in the img src url.

### ISSUE THREAD

**Issue by tio-trom** [Codeinwp/feedzy-rss-feeds#917]
### Description

I noticed that with the following feed - https://fetchrss.com/rss/64e0dbc093190f2b1a5d40b264e22cf23a76e05a277d6673.xml

This one embeds an image for the post content and also imports it into the media library and thus sets it up as a featured image:

```
<item>
<title>The rich and the poor</title>
<link>
https://www.cartoonmovement.com/cartoon/rich-and-poor-7
</link>
<description>
<img src="http://s3-eu-central-1.amazonaws.com/cartoons-s3/styles/large/s3/IMG_2526.jpeg?itok=cQk0peCM" width="480" height="309"><br><br><br/><br/><span style="font-size:12px; color: gray;">(Feed generated with <a href="https://fetchrss.com" target="_blank">FetchRSS</a>)</span>
</description>
<dc:creator>Rahma Cartoons</dc:creator>
<pubDate>Fri, 05 Apr 2024 23:14:22 +0000</pubDate>
<media:content url="http://s3-eu-central-1.amazonaws.com/cartoons-s3/styles/large/s3/IMG_2526.jpeg?itok=cQk0peCM" medium="image" width="480" height="309"/>
<guid isPermaLink="false">
https://www.cartoonmovement.com/cartoon/rich-and-poor-7
</guid>
</item>
```

This one only embeds the image into the post but cannot import it into the media library, and this cannot set it up as a featured image:

```
<item>
<title>
overflowing wealth We want a wealth tax on Europe's richest.
</title>
<link>
https://www.cartoonmovement.com/cartoon/overflowing-wealth
</link>
<description>
<img src="http://s3-eu-central-1.amazonaws.com/cartoons-s3/styles/large/s3/909%20-Saeed%2020%20Jan%20%202012%20-2.jpg?itok=9qzmqslM" width="480" height="679"><br><br><p>We want a wealth tax on Europe's richest.</p><br/><br/><span style="font-size:12px; color: gray;">(Feed generated with <a href="https://fetchrss.com" target="_blank">FetchRSS</a>)</span>
</description>
<dc:creator>Saeed Sadeghi</dc:creator>
<pubDate>Fri, 05 Apr 2024 23:14:22 +0000</pubDate>
<media:content url="http://s3-eu-central-1.amazonaws.com/cartoons-s3/styles/large/s3/909%20-Saeed%2020%20Jan%20%202012%20-2.jpg?itok=9qzmqslM" medium="image" width="480" height="679"/>
<guid isPermaLink="false">
https://www.cartoonmovement.com/cartoon/overflowing-wealth
</guid>
</item>
```

So it is on and off for a bunch of them. Looking at the code the only pattern I see is that it works to import into the wordpress library the photos that do not contain % symbols in the img scr. These are normally spaces in the URL.

Please check if you can.

### Step-by-step reproduction instructions

As described above.

### Is the issue you are reporting a regression

No

**Comment by vytisbulkevicius** [comment]
Thanks for reporting this @tio-trom.
Indeed, in the Error log I see that those characters are the problem and they are converted to space so image becomes invalid:
<img width="490" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/36594177/f279449a-3b0d-480d-8183-82cdad90b776">

We will look into fixing it.

**Comment by tio-trom** [comment]
The issue is solved but I think I caught one more - https://s3-eu-central-1.amazonaws.com/cartoons-s3/styles/product_detail_image/s3/%C3%A7%C3%B6p.jpg?itok=ZYU_ihPB special characters like 

![2024-04-11_06-04](https://github.com/Codeinwp/feedzy-rss-feeds/assets/38043315/779dbb66-274e-48cb-b20f-9cb6c75d057e)

That I cannot even copy here. But follow the link please. They too cannot be added to the library.
