### ISSUE TITLE
Compatibility with SiteOrigin Page Builder is still an issue.

### ISSUE THREAD

**Issue by rockyforever** [Codeinwp/feedzy-rss-feeds#93]
Fix compatibility with SiteOrigin Page Builder.

Still shows a blank (white page) when you try to edit options.
![feed issue](https://user-images.githubusercontent.com/31295639/34707427-514670d4-f4c2-11e7-8e5e-2c939071fdff.PNG)

**Comment by selul** [comment]
@rockyforever it should be fixed in the latest version.
