### ISSUE TITLE
Images no longer imported after the release

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#945]
### Description

A user reported that images are no longer imported after the release.

ref: https://wordpress.org/support/topic/images-in-new-imported-posts-disappeared-after-update/#post-17793775

### Step-by-step reproduction instructions

1. Import a feed with images in 4.4.8
2. Update to 4.4.9 and wait to import new posts

### Screenshots, screen recording, code snippet or Help Scout ticket

<img width="1240" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/3219f7bd-effc-4293-bcb3-5b8977c96662">

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2613096802/420707/

**Comment by tio-trom** [comment]
Same here.... I will revert for now but if needed I can provide whatever debugging help you may need.

**Comment by Soare-Robert-Daniel** [comment]
I tested this, and it seems to be ok. 

@AndreeaCristinaRadacina can you ask the users for settings used on Featured Image along with the feed?

With this PR: https://github.com/Codeinwp/feedzy-rss-feeds/pull/944 if you have some typo in your tag, you might not get the images.

![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/17597852/b6e004ed-740a-49ac-86ae-9dd0342aba92)

@tio-trom, if you can share your configuration, it will be much appreciated 🙏

**Comment by vytisbulkevicius** [comment]
@Soare-Robert-Daniel shared a test instance with you where I can replicate this

**Comment by poonam279** [comment]
+1 https://secure.helpscout.net/conversation/2616380108/421113/

**Comment by tio-trom** [comment]
> @tio-trom, if you can share your configuration, it will be much appreciated 🙏

Perhaps these?

![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/38043315/3ece9279-2a95-43cc-ab38-23505e0fb52b)
![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/38043315/eba0ce6a-a9a1-4fac-82f8-2c438980b04a)
![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/38043315/aa7423cd-0866-4449-806e-741a376a90b4)
![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/38043315/048313b2-bf50-4ce7-ada1-29dc54e9af8f)

**Comment by Soare-Robert-Daniel** [comment]
@tio-trom, thanks for the images.

Instead of tags, you can directly type `[#item_image]` to pull the image, like this: 

![image](https://github.com/Codeinwp/feedzy-rss-feeds/assets/17597852/0cbee5d0-0e9a-4af5-b228-dbc7bd4e8cb9)

This is an alternative method until we release the fix for the image tag if you want it fixed ASAP.

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://secure.helpscout.net/conversation/2631007586/422919?viewId=212385

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/what-tags-feedzy-uses-to-fetch-images/

**Comment by AndreeaCristinaRadacina** [comment]
+1 https://wordpress.org/support/topic/image-does-not-visible/
