### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by contactashish13** [Codeinwp/feedzy-rss-feeds#95]
- [ ] In http://docs.themeisle.com/article/573-how-to-move-feedzy-templates-to-your-theme, add an example specifying the name of a popular theme so that its easy for users to understand. Remove abstract language.

- [ ] Review and update http://docs.themeisle.com/article/540-what-hooks-and-filters-are-available-in-feedzy with more explanation similar to http://docs.themeisle.com/article/663-what-actions-and-filters-are-available-in-pirate-forms

**Comment by selul** [comment]
Hestia sounds fine.

**Comment by rohittm** [comment]
@contactashish13 please check both of them and let me know the suggestions/edits. Thanks.

**Comment by contactashish13** [comment]
@rohittm 

for 1) It is a little confusing if you want the user to move the feedzy templates folder into the new folder or the files from within the folder. Can you add an image too that shows the proposed folder structure? An image for both will help dispel doubts. As a general suggestion, add visual aids wherever possible.

for 2) 

* don't copy/paste directly from the code :)
e.g.
`
apply_filters( 'feedzy_feed_items', $feed->get_items(), $feedURL );
`
should be
`
apply_filters( 'feedzy_feed_items', $items, $feedURL );
`
can you correct all such instances?

* native filters are not required
* no actions?
* can you also follow the same format across all products so that the filters are separated from the actions with proper headings, similar to http://docs.themeisle.com/article/663-what-actions-and-filters-are-available-in-pirate-forms?

**Comment by rohittm** [comment]
1) Making the changes

2) I got it. Also, about the actions, the previous documentation didn't have any. So I just added Filters. Will them as well.

**Comment by rohittm** [comment]
@contactashish13 can you please check both of them again and let me know the suggestions/edits.

**Comment by contactashish13** [comment]
1. looks perfect, well done!

2a. "action: " and  "filter: " are probably not required before every action/filter.
2b. The grammar/punctuation could be improved :) e.g. `$item: an item from The feed items array.`

**Comment by rohittm** [comment]
@contactashish13 , Made the changes.

**Comment by contactashish13** [comment]
@rohittm haven't seen much improvement in 2b but whether that is required or not, you can discuss with @selul

**Comment by rohittm** [comment]
@contactashish13 Can you give another example, of what kind of grammar is to be used?

**Comment by selul** [comment]
@rohittm inside feedzy folder from the theme root there should not be any templates folder, only the 3 php files.

You can follow your doc steps and you will see that the templates are not used in the folder structure that you suggested.

**Comment by rohittm** [comment]
Okay, I'll update that.

**Comment by rohittm** [comment]
@selul Can you check it again, and let me know.

**Comment by selul** [comment]
@rohittm looks great.

**Comment by contactashish13** [comment]
@rohittm I'm reopening this so that we can add real life examples for each hook. Can you please add a fully functional example for each hook?

A few examples you can take inspiration from:

- https://secure.helpscout.net/conversation/577848228/161185/?folderId=212390#thread-1582372155
- https://secure.helpscout.net/conversation/541510231/157086/?folderId=212390#thread-1479327820
- https://secure.helpscout.net/conversation/502206489/151837?folderId=212388#thread-1408181882

Please also create a generic documentation of how to add these snippets to the functions.php of the active theme so that it can be referenced from other places.

CC: @rodica-andronache

**Comment by rodica-andronache** [comment]
Maybe starting from making sure this https://docs.themeisle.com/article/540-what-actions-and-filters-are-available-in-feedzy is updated. With linked examples to other docs.

**Comment by rohittm** [comment]
@rodica-andronache @contactashish13 

Are the tasks same as I asked [here](https://github.com/Codeinwp/wp-product-review/issues/288#issuecomment-390653880)?

**Comment by rodica-andronache** [comment]
@rohittm yes :D

**Comment by rodica-andronache** [comment]
Here we would also need to add 2 examples for the feedzy_thumb_output and feedzy_retrieve_image filters like mentioned here https://github.com/Codeinwp/feedzy-rss-feeds-pro/issues/101

**Comment by contactashish13** [comment]
closing this as this has been done by AC
