### ISSUE TITLE
YouTube content no longer retrieved

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#956]
### Description

A user reported that his posts with YouTube videos no longer contain the videos; only "Post Content" is displayed.

I rolled back a couple of versions, but the situation is the same: video is not retrieved.

### Step-by-step reproduction instructions

1. Install Feedzy free
2. Create an import using this feed - https://www.youtube.com/feeds/videos.xml?channel_id=UCVO0WdTbO4h9mVCk0-lgkzA
3. Use the [#item_content] tag
4. Save and check the results

I also tested with our channel's link - https://www.youtube.com/feeds/videos.xml?channel_id=UCAQcBsP3h6p5yXgFap4LEGA, but got the same results

### Screenshots, screen recording, code snippet or Help Scout ticket

Feedzy Free with [#item_content]:
<img width="1629" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/23ebf357-33bf-42a4-b5e1-a6b138df2bc8">

Feedzy Free + Pro active with [#item_content]:
<img width="1391" alt="image" src="https://github.com/Codeinwp/feedzy-rss-feeds/assets/86592992/489c0be2-6cae-4146-8a82-7cc05fe155f3">

For full content is the same as for [#item_content], it works well.

Documentation - https://docs.themeisle.com/article/1113-how-to-get-videos-from-youtube-with-feedzy

### Is the issue you are reporting a regression

Yes

**Comment by girishpanchal30** [comment]
Hey @AndreeaCristinaRadacina,

I've reviewed and compared the code and I found the YouTube video import features work if the `pro` plugin is activated.
Ref: https://github.com/Codeinwp/feedzy-rss-feeds-pro/blob/master/includes/admin/feedzy-rss-feeds-pro-admin.php#L1918-L1961

Also, I've reviewed some previous tickets and found it requires a pro plugin to import YT videos.
Ref: https://github.com/Codeinwp/feedzy-rss-feeds/issues/842

Should I add support for a free plugin? Please let me know

cc @vytisbulkevicius

Thanks

**Comment by stefan-cotitosu** [comment]
@AndreeaCristinaRadacina, this option is part of the pro plugin. Can you please review this again and confirm if we can close the issue?

- Does the same issue occur with the pro version?
- Did you find any docs or information on the plugin page that this works in the free version?

You can add a notice in the dedicated to mention that it is a pro feature, and include this in the comparison doc:

- https://docs.themeisle.com/article/1113-how-to-get-videos-from-youtube-with-feedzy
- https://docs.themeisle.com/article/1384-feedzy-rss-feeds-free-vs-pro

**Comment by AndreeaCristinaRadacina** [comment]
@stefan-cotitosu I see it is possible to display a YouTube feed using the Feedzy shortcode - [https://root.stefancoti.com/959b8-about/](url).

I will add a note at the beginning of the doc and in free vs pro.

Thanks for checking.
