### ISSUE TITLE
Remove links from the imported posts

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#959]
### What problem does this address?

A user wants to remove the links from the imported posts.

Currently, there is no code snippet/toggle that allows this.
ref: https://secure.helpscout.net/conversation/2650472943/426000?viewId=212385

### What is your proposed solution?

Similar to what we have for shortcode/block - https://docs.themeisle.com/article/942-in-feedzy-how-do-i#remove-links, have a code snippet or a toggle that disables the links from the post.

### Will this feature require documentation? (Optional)

Yes, it requires documentation.

**Comment by vytisbulkevicius** [comment]
@AndreeaCristinaRadacina,

We have this in internal docs (1st one): https://docs.themeisle.com/article/1334-feedzy
Let me know if it doesn't work

**Comment by AndreeaCristinaRadacina** [comment]
It works, thank you. Is it okay to add it to the public troubleshooting guide?

**Comment by vytisbulkevicius** [comment]
Sure

**Comment by AndreeaCristinaRadacina** [comment]
done - https://docs.themeisle.com/article/942-in-feedzy-how-do-i#remove-links-posts
