### ISSUE TITLE
Everyone can access to Import Feed post type

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#96]
All users can access to Import Feed post type from admin menu: https://s.nimbus.everhelper.me/share/1388099/82tf4sfz7npyuuhhd7ea

Even if you're on personal plan. @selul

**Comment by selul** [comment]
good catch @HardeepAsrani. Would you like to try to fix it ? 

We can use the is_business filter return and register or not that post type.
