### ISSUE TITLE
PHP warnings appearing in the dashboard

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#960]
### Description

Some users mention that the latest version of Feedzy contains PHP warnings:
PHP Warning: Undefined variable $version in /wp-content/plugins/feedzy-rss-feeds/includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php on line 79
PHP Warning: Undefined variable $version in /wp-content/plugins/feedzy-rss-feeds/includes/gutenberg/feedzy-rss-feeds-gutenberg-block.php on line 80

I wasn't able to replicate the issue.
ref: https://wordpress.org/support/topic/php-warning-undefined-variable-version/#post-17884659

### Step-by-step reproduction instructions

1. Create a page with Gutenberg and add a Feedzy block
2. Add a feed source and publish 
3. Update Feedzy to the latest version

### Screenshots, screen recording, code snippet or Help Scout ticket

https://plugintests.com/plugins/wporg/feedzy-rss-feeds
https://plugintests.com/plugins/wporg/feedzy-rss-feeds/latest

### Is the issue you are reporting a regression

Yes, this is a regression.

**Comment by vytisbulkevicius** [comment]
I can replicate this on a test instance.

https://sceptical-giraffe-96690f.vertisite.cloud/wp-admin
login: karelitewe0107
pw: 8feIa2CDk1UpHKoPBtl3

When refreshing a post in the dashboard, it's appearing on top: https://sceptical-giraffe-96690f.vertisite.cloud/wp-admin/post.php?post=34&action=edit

<img width="1048" alt="image" src="https://github.com/user-attachments/assets/7fbf0cdb-f458-4921-93a1-9088ead18aa4">

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina @vytisbulkevicius I've reviewed this issue and fixed it here - https://github.com/Codeinwp/feedzy-rss-feeds/pull/961

**Comment by AndreeaCristinaRadacina** [comment]
I tested, and it works fine now. 🚀
