### ISSUE TITLE
Remove the action from the post title dropdown

### ISSUE THREAD

**Issue by AndreeaCristinaRadacina** [Codeinwp/feedzy-rss-feeds#975]
While working on a ticket I noticed that we still display the actions: Title from SpinnerChief, Title from WordAI, etc., in the Post Title dropdown:
<img width="1251" alt="image" src="https://github.com/user-attachments/assets/5a501d2a-3204-4257-b386-b1efecff39fc">

We should remove those from the dropdown, as we have them in the actions modal.

**Comment by vytisbulkevicius** [comment]
I agree that we should remove these to have consistency between Content and Title fields.
It's important to note here that we should just hide them but not make them not working anymore as there are existing users using them and functionality shouldn't break for them.

We did the same for content in the past and left legacy tags supported.

cc @selul

**Comment by girishpanchal30** [comment]
@AndreeaCristinaRadacina I've removed legacy magic tags from the dropdown and also ensured it does not impact existing users.

Please check with the below PRs and let me know if you find any issues.
Free: https://github.com/Codeinwp/feedzy-rss-feeds/pull/977
Pro: https://github.com/Codeinwp/feedzy-rss-feeds-pro/pull/750

Thanks

**Comment by AndreeaCristinaRadacina** [comment]
@girishpanchal30, thank you for taking care! Everything is fine.
