### ISSUE TITLE
Issues in fetching images

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/feedzy-rss-feeds#98]
Feed isn't able to fetch the image when the there's no proper format. Few feeds have thumbnails as: http://website.com/feeditem/thumb/ instead of having a format. Can this work?

@selul

**Comment by contactashish13** [comment]
@HardeepAsrani can you share the feed URLs that might have this kind of format?

**Comment by HardeepAsrani** [comment]
@contactashish13 None other than our own: https://timesofindia.indiatimes.com/rssfeeds/296589292.cms
