### ISSUE TITLE
Medium's feed not working

### ISSUE THREAD

**Issue by Vishakha-Patel** [Codeinwp/feedzy-rss-feeds#99]
Medium feed not working with the plugin: https://medium.com/feed/topic/cryptocurrency.

As Medium is quite famous, it will be helpful if this can be resolved. Ticket: https://secure.helpscout.net/conversation/504029535/152078/

@selul

**Comment by Vishakha-Patel** [comment]
Another famous one: https://news.bitcoin.com/feed/.

**Comment by contactashish13** [comment]
@Vishakha-Patel can you please use the PR to test on a variety of URLs including ones that you know are already working? https://github.com/Codeinwp/feedzy-rss-feeds/pull/102

If anything does not seem to work, can you try on http://simplepie.org/demo/ before you report it as an error? Anything that does not work on http://simplepie.org/demo/ will not work on feedzy as that is the component being used.
